//! Recognising Xenia's own kernel export shims in its COFF symbol table.
//!
//! A title never calls Xenia. It calls *the Xbox 360 kernel*: its XEX import
//! table names `xboxkrnl.exe` ordinals, and Xenia satisfies each one with a
//! C++ function it registers through `xe::cpu::ExportResolver`. Those
//! functions are generated by the `DECLARE_XBOXKRNL_EXPORT` macros and are
//! named `<Export>_entry` inside `xe::kernel::<module>`, so the 2026-09-12
//! image carries 692 of them with addresses Rosette can already resolve.
//!
//! Arming all of them turns the single most opaque thing in a run - what the
//! translated PowerPC is actually *doing* - into a list of names with counts.
//!
//! ## Why the shim, and not the implementation
//!
//! `pkg/common/xenia/guest-milestone-map` arms
//! `xe::kernel::xboxkrnl::VdQueryVideoMode`, which is the implementation. The
//! guest reaches `VdQueryVideoMode_entry`, which is the shim, and the shim
//! calls the implementation. Those are the same event only while the call
//! between them survives optimisation.
//!
//! That distinction has already cost this project one wall.
//! `GraphicsSystem::MarkVblank` was inlined into its only caller and its
//! armed entry count stayed at zero for a whole run while the vblank was
//! ticking nineteen thousand times; the chain called the display clock
//! stopped and put the wall on the wrong owner. A shim whose body is four
//! instructions and one call is exactly the shape an optimiser inlines, and
//! four of the chain's guest-title stages are armed on the implementation
//! side of one.
//!
//! The shim is the better witness for a second reason that has nothing to do
//! with inlining: **it is the boundary**. The implementation can be reached
//! from inside Xenia - `VdQueryVideoMode` is called by `VdInitializeEngines`
//! and by the display code - so its count answers "did this run somewhere",
//! not "did the title ask". Entry into `VdQueryVideoMode_entry` happens on
//! exactly one path: a guest `bl` into the import thunk. Nothing else in the
//! program reaches it.
//!
//! ## What the join against the ordinal table buys
//!
//! Every one of the 692 shim names is an exact member of
//! `pkg/common/xenia/kernel-export-map`'s console tables, and those tables
//! hold 2913 exports. The difference is not a rounding error: the console
//! publishes 73 `Vd*` exports and Xenia implements 23. A title that calls one
//! of the other 50 gets Xenia's unimplemented-export path, and until now
//! nothing in Rosette could say that had happened, or which name it was.
//!
//! ## What this package proves, and what it does not
//!
//! It parses a name and classifies it. It resolves no address, arms nothing,
//! and counts nothing - a symbol it recognises may not be in the image, and a
//! shim in the image may never be entered. Both of those are the caller's
//! facts. It also does not claim a shim is *correct*: entry proves the title
//! asked, never that the answer it got was right.

const std = @import("std");

/// The kernel module a shim belongs to.
///
/// Spelled the same way `pkg/common/xenia/kernel-export-map` spells it, so a
/// caller can join the two without a translation table in between.
pub const Module = enum {
    xboxkrnl,
    xam,
    xbdm,

    /// The identifier Xenia uses as the C++ namespace, which is also the
    /// substring this package matches on.
    pub fn namespaceName(self: Module) []const u8 {
        return switch (self) {
            .xboxkrnl => "xboxkrnl",
            .xam => "xam",
            .xbdm => "xbdm",
        };
    }

    /// What the console calls the module a title imports from.
    pub fn moduleName(self: Module) []const u8 {
        return switch (self) {
            .xboxkrnl => "xboxkrnl.exe",
            .xam => "xam.xex",
            .xbdm => "xbdm.xex",
        };
    }
};

pub const modules = [_]Module{ .xboxkrnl, .xam, .xbdm };

/// What part of the console an export belongs to.
///
/// Coarse on purpose. The question a reader brings to a kernel-call census is
/// "has the title got as far as graphics yet", not "which of the eleven
/// registry calls did it make", and a classification fine enough to answer
/// the second makes the first unreadable. Prefix families are used because
/// the console's own naming is a prefix scheme and it is followed strictly.
pub const Subsystem = enum {
    /// `Vd*`. The chain in `guest-milestone-map` is built out of these.
    video,
    /// `XMA*`, `XAudio*`. The audio chain's guest-side ancestors.
    audio,
    /// `Mm*`. Physical and virtual memory.
    memory,
    /// `Ke*`, `Ki*`, `Kf*`. Threads, events, DPCs, interrupts, the clock.
    scheduling,
    /// `Ob*`. Handle and object management.
    object,
    /// `Nt*`, `Zw*`. The native API: files, memory, events, by handle.
    native,
    /// `Ex*`. The executive: registry, allocation, worker items.
    executive,
    /// `Rtl*` and the C runtime spellings Xenia exports beside them.
    runtime,
    /// `Xex*`. Loading and querying modules.
    module_loader,
    /// `Io*`, `Fsc*`. Device and filesystem I/O.
    io,
    /// `XeCrypt*`, `XeKeys*`.
    crypto,
    /// `Hal*`. Reset, power, and the fatal-error path.
    hardware,
    /// `Dbg*` plus everything `xbdm.xex` publishes.
    debug,
    /// `XamInput*`, `XamUserGetDevice*`. Controllers.
    input,
    /// `XamUser*`, `XamProfile*`. Signed-in players.
    user,
    /// `XamContent*`, `XamLoader*`. Saves, DLC, and title switching.
    content,
    /// `XamShow*`, `XamIs*`, `Xamp*`. The dashboard's own UI.
    shell_ui,
    /// `Net*`, `XNet*`, `XamNet*`, `XOnline*`.
    network,
    /// `XamAvatar*`, `XamNui*`, `XamVoice*`, `XamMedia*`.
    media,
    /// Recognised, but in no family that helps a reader.
    other,

    pub fn label(self: Subsystem) []const u8 {
        return switch (self) {
            .video => "video",
            .audio => "audio",
            .memory => "memory",
            .scheduling => "scheduling",
            .object => "object",
            .native => "native",
            .executive => "executive",
            .runtime => "runtime",
            .module_loader => "module-loader",
            .io => "io",
            .crypto => "crypto",
            .hardware => "hardware",
            .debug => "debug",
            .input => "input",
            .user => "user",
            .content => "content",
            .shell_ui => "shell-ui",
            .network => "network",
            .media => "media",
            .other => "other",
        };
    }

    /// Whether a call in this subsystem is on the path to a picture.
    ///
    /// Used by a report to answer "the title has made 40,000 kernel calls and
    /// none of them was graphics" without the reader counting rows.
    pub fn feedsGuestOutput(self: Subsystem) bool {
        return self == .video;
    }
};

pub const subsystem_count = @typeInfo(Subsystem).@"enum".fields.len;

/// Which of the two symbols an export's entry point is.
///
/// Xenia's `DECLARE_XBOXKRNL_EXPORT` macro does not register `<Export>_entry`
/// with the export resolver. It registers a *trampoline*: a local `struct X`
/// inside a template member function, whose job is to unpack the PowerPC
/// context into typed parameters, optionally log the call, and then call
/// `<Export>_entry`. So the address a title's kernel import resolves to is
/// the trampoline, and `_entry` is a one-line forwarder called from exactly
/// one place - which is the shape an optimiser inlines.
///
/// The 2026-09-12 image proves the point on its own: it carries 694
/// trampolines and only 692 `_entry` symbols, so two exports already have no
/// out-of-line `_entry` at all. Arming only `_entry` would have reported
/// those two as never called whatever the title did.
///
/// The trampoline cannot go the same way. Its address is stored in the export
/// table, so nothing can inline it out of existence, and nothing but the
/// guest's own import reaches it.
pub const EntryKind = enum {
    /// `X::Trampoline` - what the export resolver registers, and what the
    /// title's import actually calls. The authoritative witness.
    trampoline,
    /// `<Export>_entry` - the typed forwarder the trampoline calls. Present
    /// only when the compiler kept it out of line, so its zero is ambiguous
    /// and it is never the primary count.
    shim,

    pub fn label(self: EntryKind) []const u8 {
        return switch (self) {
            .trampoline => "trampoline",
            .shim => "entry",
        };
    }
};

/// One recognised shim symbol, decomposed.
///
/// `export_name` is a borrowed slice of the mangled string that was parsed,
/// so it lives exactly as long as that string does. Every caller in Rosette
/// holds the PE image bytes for the whole run, which is where COFF names
/// live.
pub const Shim = struct {
    module: Module,
    /// Which of the export's two symbols this one is.
    kind: EntryKind = .shim,
    /// The console's name for the export: `VdQueryVideoMode`, never
    /// `VdQueryVideoMode_entry`. This is the spelling `kernel-export-map`
    /// uses, and the spelling a reader recognises.
    export_name: []const u8,
    subsystem: Subsystem,
};

const mangled_prefix = "_ZN2xe6kernel";
const shim_suffix = "_entry";

/// Read a `<length><text>` Itanium name component starting at `offset`.
fn readComponent(mangled: []const u8, offset: usize) ?struct { text: []const u8, next: usize } {
    var cursor = offset;
    var length: usize = 0;
    var digits: usize = 0;
    while (cursor < mangled.len and mangled[cursor] >= '0' and mangled[cursor] <= '9') : (cursor += 1) {
        // A component length wider than four digits is not a Xenia symbol;
        // refusing it keeps the multiply below from ever overflowing.
        if (digits == 4) return null;
        length = length * 10 + (mangled[cursor] - '0');
        digits += 1;
    }
    if (digits == 0 or length == 0) return null;
    if (mangled.len - cursor < length) return null;
    return .{ .text = mangled[cursor .. cursor + length], .next = cursor + length };
}

/// Decompose `_ZN2xe6kernel8xboxkrnl22VdQueryVideoMode_entryE...`, or refuse.
///
/// Strict by design. A near-miss - a helper inside the same namespace, a
/// function whose name merely contains `_entry` - is not a shim, and treating
/// one as a kernel call the title made would put a fact in the census that
/// the guest never caused. Every one of the 692 shims in the 2026-09-12 image
/// matches this shape exactly, and nothing else in the image's 95,512 symbols
/// does.
pub fn parseShimSymbol(mangled: []const u8) ?Shim {
    if (!std.mem.startsWith(u8, mangled, mangled_prefix)) return null;
    const namespace = readComponent(mangled, mangled_prefix.len) orelse return null;
    const module = moduleFromNamespace(namespace.text) orelse return null;
    const name = readComponent(mangled, namespace.next) orelse return null;
    // The component list has to end here. A deeper nesting is a shim's local
    // type or a lambda, not the shim.
    if (name.next >= mangled.len or mangled[name.next] != 'E') return null;
    if (!std.mem.endsWith(u8, name.text, shim_suffix)) return null;
    const export_name = name.text[0 .. name.text.len - shim_suffix.len];
    if (export_name.len == 0) return null;
    return .{
        .module = module,
        .kind = .shim,
        .export_name = export_name,
        .subsystem = subsystemOf(module, export_name),
    };
}

const trampoline_prefix = "_ZZN2xe6kernel4shim21ExportRegistrerHelper";
const trampoline_marker = "10TrampolineE";
const module_id_marker = "14KernelModuleIdE";
const shim_suffix_terminated = shim_suffix ++ "E";

/// Decompose the mangled name of an export's registered trampoline.
///
/// The trampoline is a local class inside a template member function, so its
/// name carries the whole instantiation: the module id as an enum value, the
/// ordinal, every parameter type, and - as the template's function pointer
/// argument - the mangled name of `<Export>_entry`. The export name is read
/// from that argument and the module from the enum value.
///
/// The export name cannot be found by scanning components from the left,
/// because by the time the mangler reaches the function-pointer argument it
/// is emitting substitutions (`SA_`) rather than spelled-out namespaces and
/// there is nothing to walk. It is found from `_entryE` instead, backwards:
/// the component's own length prefix has to agree with the name it precedes,
/// which is a check no coincidence in a mangled string passes.
pub fn parseTrampolineSymbol(mangled: []const u8) ?Shim {
    if (!std.mem.startsWith(u8, mangled, trampoline_prefix)) return null;
    if (std.mem.indexOf(u8, mangled, trampoline_marker) == null) return null;
    const module = trampolineModule(mangled) orelse return null;
    const export_name = trampolineExportName(mangled) orelse return null;
    return .{
        .module = module,
        .kind = .trampoline,
        .export_name = export_name,
        .subsystem = subsystemOf(module, export_name),
    };
}

fn trampolineModule(mangled: []const u8) ?Module {
    const at = std.mem.indexOf(u8, mangled, module_id_marker) orelse return null;
    const digit_at = at + module_id_marker.len;
    if (digit_at + 1 >= mangled.len) return null;
    // `LNS1_14KernelModuleIdE<n>E`: one digit, then the closing E of the
    // enum literal. A wider value is not one of the three modules.
    if (mangled[digit_at + 1] != 'E') return null;
    return switch (mangled[digit_at]) {
        '0' => .xboxkrnl,
        '1' => .xam,
        '2' => .xbdm,
        else => null,
    };
}

fn trampolineExportName(mangled: []const u8) ?[]const u8 {
    const suffix_at = std.mem.indexOf(u8, mangled, shim_suffix_terminated) orelse return null;
    const end = suffix_at + shim_suffix.len;
    // Walk left through the component's characters, and at each candidate
    // start ask whether the digits immediately before it spell this exact
    // length. Only the true boundary can satisfy that.
    var start = end;
    while (start > 0 and isNameByte(mangled[start - 1])) {
        start -= 1;
        var digits_at = start;
        while (digits_at > 0 and isDigit(mangled[digits_at - 1])) digits_at -= 1;
        if (digits_at == start) continue;
        const declared = parseLength(mangled[digits_at..start]) orelse continue;
        if (declared != end - start) continue;
        const name = mangled[start..end];
        if (name.len <= shim_suffix.len) return null;
        return name[0 .. name.len - shim_suffix.len];
    }
    return null;
}

fn isNameByte(byte: u8) bool {
    return byte == '_' or
        (byte >= '0' and byte <= '9') or
        (byte >= 'a' and byte <= 'z') or
        (byte >= 'A' and byte <= 'Z');
}

fn isDigit(byte: u8) bool {
    return byte >= '0' and byte <= '9';
}

fn parseLength(text: []const u8) ?usize {
    if (text.len == 0 or text.len > 4) return null;
    var value: usize = 0;
    for (text) |byte| {
        if (!isDigit(byte)) return null;
        value = value * 10 + (byte - '0');
    }
    return value;
}

/// Either kind of entry point, or null when the symbol is neither.
///
/// The trampoline is tried first: a name that is one cannot also be the
/// other, and the trampoline is the one whose count means "the title asked".
pub fn parseExportEntryPoint(mangled: []const u8) ?Shim {
    if (parseTrampolineSymbol(mangled)) |trampoline| return trampoline;
    return parseShimSymbol(mangled);
}

fn moduleFromNamespace(text: []const u8) ?Module {
    for (modules) |module| {
        if (std.mem.eql(u8, module.namespaceName(), text)) return module;
    }
    return null;
}

fn startsWith(name: []const u8, prefix: []const u8) bool {
    return std.mem.startsWith(u8, name, prefix);
}

fn startsWithAny(name: []const u8, prefixes: []const []const u8) bool {
    for (prefixes) |prefix| {
        if (startsWith(name, prefix)) return true;
    }
    return false;
}

/// Which part of the console an export name belongs to.
///
/// Ordered so a longer, more specific family is tested before the shorter one
/// that would also match it: `XamInputGetState` is input before it is user,
/// and `XeCryptSha` is crypto before `Xe*` falls through to other.
pub fn subsystemOf(module: Module, export_name: []const u8) Subsystem {
    if (module == .xbdm) return .debug;
    if (module == .xam) return xamSubsystem(export_name);
    return xboxkrnlSubsystem(export_name);
}

fn xboxkrnlSubsystem(name: []const u8) Subsystem {
    if (startsWith(name, "Vd")) return .video;
    if (startsWithAny(name, &.{ "XMA", "XAudio" })) return .audio;
    if (startsWith(name, "Mm")) return .memory;
    if (startsWithAny(name, &.{ "Ke", "Ki", "Kf", "Interrupt" })) return .scheduling;
    if (startsWith(name, "Ob")) return .object;
    if (startsWithAny(name, &.{ "Nt", "Zw" })) return .native;
    if (startsWith(name, "Ex")) return .executive;
    if (startsWith(name, "Xex")) return .module_loader;
    if (startsWithAny(name, &.{ "Io", "Fsc" })) return .io;
    if (startsWithAny(name, &.{ "XeCrypt", "XeKeys" })) return .crypto;
    if (startsWith(name, "Hal")) return .hardware;
    if (startsWith(name, "Dbg")) return .debug;
    if (startsWithAny(name, &.{ "Net", "XNet", "XOnline" })) return .network;
    // `Rtl*` last of the prefix families, then the C runtime spellings the
    // kernel publishes beside it: `sprintf`, `_snprintf`, `vswprintf` and
    // friends are `Rtl` functions wearing a C name.
    if (startsWith(name, "Rtl")) return .runtime;
    if (isCRuntimeSpelling(name)) return .runtime;
    return .other;
}

fn isCRuntimeSpelling(name: []const u8) bool {
    if (name.len == 0) return false;
    if (name[0] == '_') return true;
    return startsWithAny(name, &.{ "sprintf", "swprintf", "vsprintf", "vswprintf", "strn", "wcsn", "qsort", "rand", "toupper", "tolower" });
}

fn xamSubsystem(name: []const u8) Subsystem {
    if (startsWithAny(name, &.{ "XamInput", "XamUserGetDevice" })) return .input;
    if (startsWithAny(name, &.{ "XamContent", "XamLoader" })) return .content;
    if (startsWithAny(name, &.{ "XamAvatar", "XamNui", "XamVoice", "XamMedia", "XamMusic" })) return .media;
    if (startsWithAny(name, &.{ "XamShow", "XamIs", "Xamp", "XamNotify", "XamTask", "XamUI" })) return .shell_ui;
    if (startsWithAny(name, &.{ "XamUser", "XamProfile", "XamParty", "XamSession" })) return .user;
    if (startsWithAny(name, &.{ "Net", "XNet", "XOnline", "XamNet", "XMsg", "Xmsg" })) return .network;
    if (startsWithAny(name, &.{ "XamAlloc", "XamFree" })) return .memory;
    if (startsWith(name, "Rtl")) return .runtime;
    if (startsWithAny(name, &.{ "XamGet", "XamSet", "XamBuild", "XamEnum", "Enumerate", "Get", "XGetVideoMode", "XGetAV" })) return .other;
    return .other;
}

// ---------------------------------------------------------------------------
// Witnesses: the shim that proves a milestone the implementation might not
// ---------------------------------------------------------------------------

/// A shim whose entry proves a `guest-milestone-map` stage independently.
///
/// The milestone table arms Xenia-internal functions because they are what a
/// chain stage means. This table names the guest-facing shim that reaches the
/// same conclusion from the other side of the boundary, so a stage has two
/// witnesses that fail differently: the implementation goes quiet when an
/// optimiser inlines it, and the shim goes quiet only when the title stops
/// calling.
///
/// A stage is met when **either** witness fired. That is not double-counting:
/// the two counts are printed side by side, and a stage where they disagree
/// is itself a finding - a shim entered a thousand times whose implementation
/// reads zero is an inlined call, and an implementation entered whose shim
/// reads zero is Xenia calling itself.
pub const Witness = struct {
    /// The console export name, as `parseShimSymbol` returns it.
    export_name: []const u8,
    module: Module,
    /// The `guest-milestone-map` row this witnesses, by mangled name. A
    /// caller joins on this; nothing here validates that the row exists,
    /// because this package cannot see that table without depending on it.
    milestone: []const u8,
    /// What the *shim's* entry proves, which is never quite what the
    /// implementation's entry proves.
    proves: []const u8,
};

pub const witnesses = [_]Witness{
    .{
        .export_name = "VdQueryVideoMode",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb",
        .proves = "the title itself asked the kernel what display it has. The implementation is also called from VdInitializeEngines and from Xenia's own display code, so only the shim's count is the title's act",
    },
    .{
        .export_name = "VdQueryRealVideoMode",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb",
        .proves = "the title asked for the *physical* display mode rather than the emulated one. Titles built against later SDKs call this instead of VdQueryVideoMode, so a chain that watches only the latter can miss a title that did ask",
    },
    .{
        .export_name = "VdSetGraphicsInterruptCallback",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3gpu14GraphicsSystem20SetInterruptCallbackEjj",
        .proves = "the title handed the kernel its GPU interrupt handler. GraphicsSystem::SetInterruptCallback is virtual and reached through a vtable, so its zero and this shim's zero are different claims",
    },
    .{
        .export_name = "VdInitializeRingBuffer",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3gpu14GraphicsSystem20InitializeRingBufferEjj",
        .proves = "the title gave the GPU the address and size of its command ring; this is the title's first GPU act and nothing downstream can happen before it",
    },
    .{
        .export_name = "VdEnableRingBufferRPtrWriteBack",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3gpu14GraphicsSystem26EnableReadPointerWriteBackEjj",
        .proves = "the title asked for the ring read pointer to be written back into its own memory rather than polling a register",
    },
    .{
        .export_name = "VdSwap",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3gpu6vulkan22VulkanCommandProcessor9IssueSwapEjjj",
        .proves = "the title asked for its front buffer to be shown. IssueSwap is reached from the GPU thread when it decodes the swap packet, which is later and can be lost; the shim is the request itself",
    },
    .{
        .export_name = "VdInitializeEngines",
        .module = .xboxkrnl,
        .milestone = "",
        .proves = "the title started the GPU's engines. Not a chain stage - it has no Xenia-side milestone - but it sits between VdQueryVideoMode and VdInitializeRingBuffer in every title's boot, so its count places a stalled title inside that gap",
    },
    .{
        .export_name = "VdCallGraphicsNotificationRoutines",
        .module = .xboxkrnl,
        .milestone = "",
        .proves = "the title told the kernel a display-mode change is happening. D3D does this while it creates its device, so it places a title inside display bring-up; it is not evidence of a render loop, and only VdSwap is",
    },
    .{
        .export_name = "XAudioRegisterRenderDriverClient",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3apu11AudioSystem14RegisterClientEjjPy",
        .proves = "the title asked the kernel for an audio port; Xenia creates no driver and touches no host audio API until this happens",
    },
    .{
        .export_name = "XAudioSubmitRenderDriverFrame",
        .module = .xboxkrnl,
        .milestone = "_ZN2xe3apu11AudioSystem11SubmitFrameEyPf",
        .proves = "the title handed the kernel a buffer of PCM; frames can still be silent, but nothing before this point can be",
    },
};

/// The witness rows for one milestone, if any name it.
///
/// Returns a count rather than a slice because a milestone can have more than
/// one - `VdQueryVideoMode` and `VdQueryRealVideoMode` both prove the title
/// asked about the display - and a caller wants to sum them.
pub fn witnessCountFor(milestone: []const u8) usize {
    if (milestone.len == 0) return 0;
    var total: usize = 0;
    for (witnesses) |witness| {
        if (std.mem.eql(u8, witness.milestone, milestone)) total += 1;
    }
    return total;
}

/// Whether an export name is one of the witnesses for `milestone`.
pub fn witnesses_milestone(export_name: []const u8, milestone: []const u8) bool {
    if (milestone.len == 0) return false;
    for (witnesses) |witness| {
        if (!std.mem.eql(u8, witness.milestone, milestone)) continue;
        if (std.mem.eql(u8, witness.export_name, export_name)) return true;
    }
    return false;
}

/// The witness row for an export name, if this table names it.
pub fn witnessFor(export_name: []const u8) ?Witness {
    for (witnesses) |witness| {
        if (std.mem.eql(u8, witness.export_name, export_name)) return witness;
    }
    return null;
}

// ---------------------------------------------------------------------------
// The boot narrative: where in its own startup a silent title has stopped
// ---------------------------------------------------------------------------

/// How far a title has got, expressed in the kernel calls it has made.
///
/// A count of kernel calls says a title is alive. It does not say *where* it
/// is, and "alive but not drawing" has been this project's state for several
/// runs. Every Xbox 360 title reaches graphics through the same sequence
/// because the D3D runtime it is statically linked against is the same one,
/// so the calls it has and has not made place it in that sequence exactly.
pub const BootPhase = enum {
    /// No kernel call at all. Either the title thread has not run or it is
    /// executing translated code that has not reached an import yet.
    no_kernel_contact,
    /// `XexGetModuleHandle`, `RtlInitializeCriticalSection`, TLS setup: the
    /// CRT and the XDK's own initialisers, before any title code runs.
    runtime_initialisation,
    /// `NtAllocateVirtualMemory`, `MmAllocatePhysicalMemoryEx`: the title is
    /// building its heaps. D3D's command buffer comes out of physical memory,
    /// so this always precedes graphics.
    memory_setup,
    /// `ExCreateThread`, `KeSetAffinityThread`: worker threads are up.
    thread_setup,
    /// `NtOpenFile`, `NtReadFile`, `XamContentCreateEx`: the title is loading
    /// its own assets. A title can sit here for a long time legitimately.
    asset_loading,
    /// `VdQueryVideoMode`, `VdInitializeEngines`: D3D device creation has
    /// begun. This is the phase the guest output chain's wall sits in.
    display_query,
    /// `VdInitializeRingBuffer`, `VdSetGraphicsInterruptCallback`: the GPU is
    /// being handed its ring. After this the command processor has work.
    gpu_handshake,
    /// `VdSwap`: the title is presenting. Anything black from here on is
    /// Rosette's or Xenia's, not the title's.
    rendering,

    pub fn label(self: BootPhase) []const u8 {
        return switch (self) {
            .no_kernel_contact => "no-kernel-contact",
            .runtime_initialisation => "runtime-initialisation",
            .memory_setup => "memory-setup",
            .thread_setup => "thread-setup",
            .asset_loading => "asset-loading",
            .display_query => "display-query",
            .gpu_handshake => "gpu-handshake",
            .rendering => "rendering",
        };
    }

    /// What a reader should do when the title has stopped here.
    pub fn advice(self: BootPhase) []const u8 {
        return switch (self) {
            .no_kernel_contact => "the title has made no kernel call. Either XThread::Execute has not run, or the translated code is running but has not reached an import thunk - read PE64 GUEST THREADS for the title thread's rip and PE64 SPIN ANATOMY for what it is polling",
            .runtime_initialisation => "the title is still inside the XDK's own start-up. Nothing is wrong yet; if it does not leave, the last export it called names the initialiser it is stuck in",
            .memory_setup => "the title is building its heaps. A refused or wrongly-sized allocation here stalls it before it ever asks about the display; read PE64 MEMORY CONTRACT and the guest-heap fatal points",
            .thread_setup => "the title is creating its worker threads. A thread that never starts, or a wait that never returns, holds it here",
            .asset_loading => "the title is reading its own data. This is legitimately slow, and the file exports it is calling say whether it is making progress or retrying one read",
            .display_query => "the title has begun creating its D3D device. This is where the guest output chain's wall sits: read which Vd* exports it has called and which of them Xenia does not implement",
            .gpu_handshake => "the title is handing the GPU its ring. From here the command processor has something to read, and an empty ring is a producer problem",
            .rendering => "the title is presenting. A black window from this phase belongs to Xenia's presenter or to Rosette's bridge, not to the title",
        };
    }
};

pub const boot_phase_count = @typeInfo(BootPhase).@"enum".fields.len;

/// An export whose entry places the title in a phase.
///
/// Deliberately short. A phase marker has to be a call every title makes and
/// makes only in that phase; a call some titles skip would place a healthy
/// title behind where it is.
pub const PhaseMarker = struct {
    export_name: []const u8,
    phase: BootPhase,
};

pub const phase_markers = [_]PhaseMarker{
    // Rendering, first: a title that has reached it has also made every call
    // below, and the furthest phase reached is the answer.
    .{ .export_name = "VdSwap", .phase = .rendering },

    .{ .export_name = "VdInitializeRingBuffer", .phase = .gpu_handshake },
    .{ .export_name = "VdSetGraphicsInterruptCallback", .phase = .gpu_handshake },
    .{ .export_name = "VdEnableRingBufferRPtrWriteBack", .phase = .gpu_handshake },
    .{ .export_name = "VdGetSystemCommandBuffer", .phase = .gpu_handshake },

    .{ .export_name = "VdQueryVideoMode", .phase = .display_query },
    // Called while D3D builds its device, not around a swap. It was a
    // `rendering` marker, and on the 2026-09-13 run that put a title with
    // `VdSwap=0` in the rendering phase and told the reader "the title is
    // presenting" - the exact opposite of what the ring showed.
    .{ .export_name = "VdCallGraphicsNotificationRoutines", .phase = .display_query },
    .{ .export_name = "VdQueryRealVideoMode", .phase = .display_query },
    .{ .export_name = "VdQueryVideoFlags", .phase = .display_query },
    .{ .export_name = "VdInitializeEngines", .phase = .display_query },
    .{ .export_name = "VdGetCurrentDisplayInformation", .phase = .display_query },
    .{ .export_name = "VdGetCurrentDisplayGamma", .phase = .display_query },
    .{ .export_name = "VdIsHSIOTrainingSucceeded", .phase = .display_query },
    .{ .export_name = "VdGetGraphicsAsicID", .phase = .display_query },

    .{ .export_name = "NtOpenFile", .phase = .asset_loading },
    .{ .export_name = "NtReadFile", .phase = .asset_loading },
    .{ .export_name = "NtQueryDirectoryFile", .phase = .asset_loading },
    .{ .export_name = "XamContentCreateEx", .phase = .asset_loading },
    .{ .export_name = "XamContentOpenFile", .phase = .asset_loading },

    .{ .export_name = "ExCreateThread", .phase = .thread_setup },
    .{ .export_name = "KeSetAffinityThread", .phase = .thread_setup },
    .{ .export_name = "NtResumeThread", .phase = .thread_setup },

    .{ .export_name = "NtAllocateVirtualMemory", .phase = .memory_setup },
    .{ .export_name = "MmAllocatePhysicalMemoryEx", .phase = .memory_setup },
    .{ .export_name = "MmAllocatePhysicalMemory", .phase = .memory_setup },
    .{ .export_name = "MmGetPhysicalAddress", .phase = .memory_setup },

    .{ .export_name = "XexGetModuleHandle", .phase = .runtime_initialisation },
    .{ .export_name = "XexGetProcedureAddress", .phase = .runtime_initialisation },
    .{ .export_name = "RtlInitializeCriticalSection", .phase = .runtime_initialisation },
    .{ .export_name = "RtlInitializeCriticalSectionAndSpinCount", .phase = .runtime_initialisation },
    .{ .export_name = "KeTlsAlloc", .phase = .runtime_initialisation },
    .{ .export_name = "ExRegisterTitleTerminateNotification", .phase = .runtime_initialisation },
};

/// The phase an export places the title in, or null when it says nothing.
pub fn phaseOf(export_name: []const u8) ?BootPhase {
    for (phase_markers) |marker| {
        if (std.mem.eql(u8, marker.export_name, export_name)) return marker.phase;
    }
    return null;
}

/// The phase after `phase`, or null when `phase` is the last one.
///
/// A report names the phase the title has *not* reached, which is the one a
/// reader has to act on.
pub fn nextPhase(phase: BootPhase) ?BootPhase {
    const index: usize = @intFromEnum(phase);
    if (index + 1 >= boot_phase_count) return null;
    return @enumFromInt(index + 1);
}

/// How many phase markers exist for a phase, so a report can say "2 of the 8
/// display-query exports have been called" rather than just naming one.
pub fn markerCountFor(phase: BootPhase) usize {
    var total: usize = 0;
    for (phase_markers) |marker| {
        if (marker.phase == phase) total += 1;
    }
    return total;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test "the shim shape every one of the image's 692 exports has" {
    const shim = parseShimSymbol(
        "_ZN2xe6kernel8xboxkrnl22VdQueryVideoMode_entryERKNS0_4shim17TypedPointerParamINS0_12X_VIDEO_MODEEEE",
    ).?;
    try std.testing.expectEqual(Module.xboxkrnl, shim.module);
    try std.testing.expectEqualStrings("VdQueryVideoMode", shim.export_name);
    try std.testing.expectEqual(Subsystem.video, shim.subsystem);

    const xam = parseShimSymbol("_ZN2xe6kernel3xam22XamInputGetState_entryEv").?;
    try std.testing.expectEqual(Module.xam, xam.module);
    try std.testing.expectEqualStrings("XamInputGetState", xam.export_name);
    try std.testing.expectEqual(Subsystem.input, xam.subsystem);

    const xbdm = parseShimSymbol("_ZN2xe6kernel4xbdm18DmGetXbeInfo_entryEv").?;
    try std.testing.expectEqual(Module.xbdm, xbdm.module);
    try std.testing.expectEqual(Subsystem.debug, xbdm.subsystem);
}

test "a near miss is refused, because a false kernel call is a fact the guest never caused" {
    // The implementation, not the shim. It is the symbol the milestone table
    // arms and it must never be counted as a call the title made.
    try std.testing.expectEqual(
        @as(?Shim, null),
        parseShimSymbol("_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb"),
    );
    // Right namespace, deeper nesting: a type or lambda inside a shim.
    try std.testing.expectEqual(
        @as(?Shim, null),
        parseShimSymbol("_ZN2xe6kernel8xboxkrnl16VdQueryVideoMode5InnerEv"),
    );
    // Not the kernel at all.
    try std.testing.expectEqual(
        @as(?Shim, null),
        parseShimSymbol("_ZN2xe3gpu16CommandProcessor10InitializeEv"),
    );
    // A module Xenia does not publish exports for.
    try std.testing.expectEqual(
        @as(?Shim, null),
        parseShimSymbol("_ZN2xe6kernel3xex11Thing_entryEv"),
    );
    try std.testing.expectEqual(@as(?Shim, null), parseShimSymbol(""));
    try std.testing.expectEqual(@as(?Shim, null), parseShimSymbol("_ZN2xe6kernel"));
    // A length that runs past the end of the string must refuse, not read
    // out of bounds.
    try std.testing.expectEqual(@as(?Shim, null), parseShimSymbol("_ZN2xe6kernel8xboxkrnl99Vd_entryE"));
    // A component length wide enough to overflow the accumulator.
    try std.testing.expectEqual(@as(?Shim, null), parseShimSymbol("_ZN2xe6kernel99999999999999xE"));
}

test "the subsystems a chain depends on are the ones a prefix cannot confuse" {
    try std.testing.expectEqual(Subsystem.video, subsystemOf(.xboxkrnl, "VdInitializeRingBuffer"));
    try std.testing.expectEqual(Subsystem.audio, subsystemOf(.xboxkrnl, "XMACreateContext"));
    try std.testing.expectEqual(Subsystem.memory, subsystemOf(.xboxkrnl, "MmAllocatePhysicalMemoryEx"));
    try std.testing.expectEqual(Subsystem.scheduling, subsystemOf(.xboxkrnl, "KeWaitForSingleObject"));
    try std.testing.expectEqual(Subsystem.native, subsystemOf(.xboxkrnl, "NtReadFile"));
    try std.testing.expectEqual(Subsystem.object, subsystemOf(.xboxkrnl, "ObReferenceObjectByHandle"));
    try std.testing.expectEqual(Subsystem.executive, subsystemOf(.xboxkrnl, "ExCreateThread"));
    try std.testing.expectEqual(Subsystem.module_loader, subsystemOf(.xboxkrnl, "XexGetModuleHandle"));
    try std.testing.expectEqual(Subsystem.crypto, subsystemOf(.xboxkrnl, "XeCryptSha"));
    try std.testing.expectEqual(Subsystem.runtime, subsystemOf(.xboxkrnl, "RtlInitializeCriticalSection"));
    try std.testing.expectEqual(Subsystem.runtime, subsystemOf(.xboxkrnl, "_snprintf"));
    try std.testing.expectEqual(Subsystem.runtime, subsystemOf(.xboxkrnl, "vswprintf"));
    try std.testing.expectEqual(Subsystem.hardware, subsystemOf(.xboxkrnl, "HalReturnToFirmware"));

    // `XeCrypt` must beat the bare `Xe` fall-through, and `XexGet` must not
    // be read as crypto.
    try std.testing.expectEqual(Subsystem.module_loader, subsystemOf(.xboxkrnl, "XexLoadImage"));
    try std.testing.expect(subsystemOf(.xboxkrnl, "XeKeysGetKey") == .crypto);

    // Only video feeds the guest output chain, and it must.
    try std.testing.expect(Subsystem.video.feedsGuestOutput());
    try std.testing.expect(!Subsystem.audio.feedsGuestOutput());
    try std.testing.expect(!Subsystem.other.feedsGuestOutput());
}

test "xam's families do not swallow each other" {
    try std.testing.expectEqual(Subsystem.input, subsystemOf(.xam, "XamInputGetCapabilities"));
    // Shares the `XamUser` prefix with the user family and must stay input.
    try std.testing.expectEqual(Subsystem.input, subsystemOf(.xam, "XamUserGetDeviceContext"));
    try std.testing.expectEqual(Subsystem.user, subsystemOf(.xam, "XamUserGetSigninState"));
    try std.testing.expectEqual(Subsystem.content, subsystemOf(.xam, "XamContentCreateEx"));
    try std.testing.expectEqual(Subsystem.media, subsystemOf(.xam, "XamAvatarInitialize"));
    try std.testing.expectEqual(Subsystem.shell_ui, subsystemOf(.xam, "XamShowMessageBoxUI"));
    try std.testing.expectEqual(Subsystem.network, subsystemOf(.xam, "NetDll_socket"));
    try std.testing.expectEqual(Subsystem.debug, subsystemOf(.xbdm, "DmWalkLoadedModules"));
}

test "every subsystem has a label and no two share one" {
    inline for (@typeInfo(Subsystem).@"enum".fields, 0..) |field, index| {
        const subsystem: Subsystem = @enumFromInt(field.value);
        try std.testing.expect(subsystem.label().len != 0);
        inline for (@typeInfo(Subsystem).@"enum".fields, 0..) |other, other_index| {
            if (other_index >= index) continue;
            const earlier: Subsystem = @enumFromInt(other.value);
            try std.testing.expect(!std.mem.eql(u8, earlier.label(), subsystem.label()));
        }
    }
    try std.testing.expectEqual(@as(usize, 20), subsystem_count);
}

test "the wall's stage has a shim witness, because its implementation may be inlined" {
    // The whole reason this package exists: on the 2026-09-12 run
    // `title_queried_video_mode` was the wall and its evidence was an entry
    // count on the implementation. If the shim's one call to it was inlined,
    // that zero measured the build.
    const video_mode = "_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb";
    try std.testing.expectEqual(@as(usize, 2), witnessCountFor(video_mode));
    try std.testing.expect(witnesses_milestone("VdQueryVideoMode", video_mode));
    try std.testing.expect(witnesses_milestone("VdQueryRealVideoMode", video_mode));
    try std.testing.expect(!witnesses_milestone("VdSwap", video_mode));
    try std.testing.expectEqual(@as(usize, 0), witnessCountFor(""));

    // Each of the four guest-title stages downstream of the wall too.
    try std.testing.expect(witnessCountFor("_ZN2xe3gpu14GraphicsSystem20SetInterruptCallbackEjj") >= 1);
    try std.testing.expect(witnessCountFor("_ZN2xe3gpu14GraphicsSystem20InitializeRingBufferEjj") >= 1);
    try std.testing.expect(witnessCountFor("_ZN2xe3gpu6vulkan22VulkanCommandProcessor9IssueSwapEjjj") >= 1);
}

test "every witness names a video or audio export and says what its own entry proves" {
    for (witnesses, 0..) |witness, index| {
        try std.testing.expect(witness.export_name.len != 0);
        try std.testing.expect(witness.proves.len != 0);
        const subsystem = subsystemOf(witness.module, witness.export_name);
        try std.testing.expect(subsystem == .video or subsystem == .audio or subsystem == .other);
        for (witnesses[0..index]) |earlier| {
            try std.testing.expect(!std.mem.eql(u8, earlier.export_name, witness.export_name));
        }
        try std.testing.expectEqualStrings(witness.export_name, witnessFor(witness.export_name).?.export_name);
    }
    try std.testing.expectEqual(@as(?Witness, null), witnessFor("NtReadFile"));
}

test "the boot phases are ordered and every one carries advice" {
    // The furthest phase reached is the answer, so the enum's order is load
    // bearing: a report takes the maximum.
    try std.testing.expect(@intFromEnum(BootPhase.no_kernel_contact) < @intFromEnum(BootPhase.display_query));
    try std.testing.expect(@intFromEnum(BootPhase.display_query) < @intFromEnum(BootPhase.gpu_handshake));
    try std.testing.expect(@intFromEnum(BootPhase.gpu_handshake) < @intFromEnum(BootPhase.rendering));
    try std.testing.expectEqual(@as(?BootPhase, null), nextPhase(.rendering));
    try std.testing.expectEqual(BootPhase.gpu_handshake, nextPhase(.display_query).?);

    inline for (@typeInfo(BootPhase).@"enum".fields) |field| {
        const phase: BootPhase = @enumFromInt(field.value);
        try std.testing.expect(phase.label().len != 0);
        try std.testing.expect(phase.advice().len != 0);
    }
}

test "a phase marker is an export in that phase's own subsystem" {
    for (phase_markers, 0..) |marker, index| {
        try std.testing.expect(marker.export_name.len != 0);
        // A marker listed twice would let one call advance two phases.
        for (phase_markers[0..index]) |earlier| {
            try std.testing.expect(!std.mem.eql(u8, earlier.export_name, marker.export_name));
        }
        try std.testing.expectEqual(marker.phase, phaseOf(marker.export_name).?);
        if (marker.phase == .display_query or marker.phase == .gpu_handshake or marker.phase == .rendering) {
            try std.testing.expectEqual(Subsystem.video, subsystemOf(.xboxkrnl, marker.export_name));
        }
    }
    // `no_kernel_contact` is the absence of every marker, so it must have
    // none of its own.
    try std.testing.expectEqual(@as(usize, 0), markerCountFor(.no_kernel_contact));
    try std.testing.expect(markerCountFor(.display_query) >= 6);
    try std.testing.expectEqual(@as(?BootPhase, null), phaseOf("NtClose"));
}

test "the trampoline is the symbol the title's import actually resolves to" {
    // The exact spelling from the 2026-09-12 image. `X::Trampoline` is a
    // local class inside a template member function, so the export name is
    // present only as the template's function-pointer argument.
    const tramp = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJKNS1_17TypedPointerParamINS0_12X_VIDEO_MODEEEEEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryERS7_EELj983042EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
    const parsed = parseTrampolineSymbol(tramp).?;
    try std.testing.expectEqual(Module.xboxkrnl, parsed.module);
    try std.testing.expectEqual(EntryKind.trampoline, parsed.kind);
    try std.testing.expectEqualStrings("VdQueryVideoMode", parsed.export_name);
    try std.testing.expectEqual(Subsystem.video, parsed.subsystem);
    try std.testing.expectEqualStrings("VdQueryVideoMode", parseExportEntryPoint(tramp).?.export_name);

    // By the time the mangler reaches the function-pointer argument it is
    // emitting substitutions rather than namespaces, so nothing can be read
    // by walking components from the left. This one spells the module as
    // `SA_` and is the case that broke the first attempt.
    const substituted = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE1ELt25ENS1_10ResultBaseIjEEJKNS1_9ParamBaseIjEES8_KNS1_17TypedPointerParamINS0_3xam7XWSABUFEEES8_EE14RegisterExportIXadL_ZNSA_22NetDll_WSASendTo_entryERS8_SR_EELj720897EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSX_3ppc12PPCContext_sE";
    const net = parseTrampolineSymbol(substituted).?;
    try std.testing.expectEqual(Module.xam, net.module);
    try std.testing.expectEqualStrings("NetDll_WSASendTo", net.export_name);
    try std.testing.expectEqual(Subsystem.network, net.subsystem);
}

test "a trampoline and an entry are different kinds of the same export" {
    const tramp = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
    const entry = "_ZN2xe6kernel8xboxkrnl22VdQueryVideoMode_entryERKNS0_4shim17TypedPointerParamINS0_12X_VIDEO_MODEEEE";
    try std.testing.expectEqualStrings(
        parseTrampolineSymbol(tramp).?.export_name,
        parseShimSymbol(entry).?.export_name,
    );
    // Neither recogniser may claim the other's symbol: they are counted
    // separately, and a name matched by both would be counted twice.
    try std.testing.expectEqual(@as(?Shim, null), parseShimSymbol(tramp));
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(entry));
    try std.testing.expectEqual(EntryKind.shim, parseExportEntryPoint(entry).?.kind);
}

test "a trampoline-shaped name that is missing a part is refused" {
    const base = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
    try std.testing.expect(parseTrampolineSymbol(base) != null);
    // No trampoline marker: this is the enclosing RegisterExport function
    // itself, which runs once at start-up and is not a kernel call.
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(
        "_ZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryEvEELj1EEEPNS_3cpu6ExportEPKcE",
    ));
    // A module id outside the three Xenia publishes.
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(
        "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE7ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryEvEEEEN1X10TrampolineEv",
    ));
    // A length prefix that disagrees with the name it precedes. This is the
    // check that makes the backwards scan safe: no coincidence in a mangled
    // string passes it.
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(
        "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl99VdQueryVideoMode_entryEvEEEEN1X10TrampolineEv",
    ));
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(""));
    try std.testing.expectEqual(@as(?Shim, null), parseTrampolineSymbol(trampoline_prefix));
}

test "both entry kinds carry a label and they differ" {
    try std.testing.expect(!std.mem.eql(u8, EntryKind.trampoline.label(), EntryKind.shim.label()));
    try std.testing.expect(EntryKind.trampoline.label().len != 0);
    try std.testing.expect(EntryKind.shim.label().len != 0);
}

test "only a swap places a title in the rendering phase" {
    // The one phase whose advice tells a reader to stop suspecting the title.
    // A marker that can fire before the first swap puts the blame on Xenia's
    // presenter while the title has not presented anything.
    for (phase_markers) |marker| {
        if (marker.phase != .rendering) continue;
        try std.testing.expectEqualStrings("VdSwap", marker.export_name);
    }
    try std.testing.expectEqual(@as(usize, 1), markerCountFor(.rendering));
    try std.testing.expectEqual(BootPhase.display_query, phaseOf("VdCallGraphicsNotificationRoutines").?);
}
