const std = @import("std");
const runtime_abi = @import("runtime_abi_handshake");

// Generated by tools/gen_ppc_isa.py from tools/ppc_isa_spec.txt. Do not edit by hand.

const add_addcx = @import("ADD/ADDCX.zig");
const add_addex = @import("ADD/ADDEX.zig");
const add_addi = @import("ADD/ADDI.zig");
const add_addic = @import("ADD/ADDIC.zig");
const add_addicx = @import("ADD/ADDICX.zig");
const add_addis = @import("ADD/ADDIS.zig");
const add_addmex = @import("ADD/ADDMEX.zig");
const add_addx = @import("ADD/ADDX.zig");
const add_addzex = @import("ADD/ADDZEX.zig");
const atomic_ldarx = @import("ATOMIC/LDARX.zig");
const atomic_lwarx = @import("ATOMIC/LWARX.zig");
const atomic_stdcx = @import("ATOMIC/STDCX.zig");
const atomic_stwcx = @import("ATOMIC/STWCX.zig");
const branch_bcctrx = @import("BRANCH/BCCTRX.zig");
const branch_bclrx = @import("BRANCH/BCLRX.zig");
const branch_bcx = @import("BRANCH/BCX.zig");
const branch_bx = @import("BRANCH/BX.zig");
const byte_reverse_ldbrx = @import("BYTE_REVERSE/LDBRX.zig");
const byte_reverse_lhbrx = @import("BYTE_REVERSE/LHBRX.zig");
const byte_reverse_lwbrx = @import("BYTE_REVERSE/LWBRX.zig");
const byte_reverse_stdbrx = @import("BYTE_REVERSE/STDBRX.zig");
const byte_reverse_sthbrx = @import("BYTE_REVERSE/STHBRX.zig");
const byte_reverse_stwbrx = @import("BYTE_REVERSE/STWBRX.zig");
const cache_dcbf = @import("CACHE/DCBF.zig");
const cache_dcbi = @import("CACHE/DCBI.zig");
const cache_dcbst = @import("CACHE/DCBST.zig");
const cache_dcbt = @import("CACHE/DCBT.zig");
const cache_dcbtst = @import("CACHE/DCBTST.zig");
const cache_dcbz = @import("CACHE/DCBZ.zig");
const cache_dcbz128 = @import("CACHE/DCBZ128.zig");
const cache_icbi = @import("CACHE/ICBI.zig");
const cmp_cmp = @import("CMP/CMP.zig");
const cmp_cmpi = @import("CMP/CMPI.zig");
const cmp_cmpl = @import("CMP/CMPL.zig");
const cmp_cmpli = @import("CMP/CMPLI.zig");
const condition_register_crand = @import("CONDITION_REGISTER/CRAND.zig");
const condition_register_crandc = @import("CONDITION_REGISTER/CRANDC.zig");
const condition_register_creqv = @import("CONDITION_REGISTER/CREQV.zig");
const condition_register_crnand = @import("CONDITION_REGISTER/CRNAND.zig");
const condition_register_crnor = @import("CONDITION_REGISTER/CRNOR.zig");
const condition_register_cror = @import("CONDITION_REGISTER/CROR.zig");
const condition_register_crorc = @import("CONDITION_REGISTER/CRORC.zig");
const condition_register_crxor = @import("CONDITION_REGISTER/CRXOR.zig");
const condition_register_mcrf = @import("CONDITION_REGISTER/MCRF.zig");
const condition_register_mcrxr = @import("CONDITION_REGISTER/MCRXR.zig");
const condition_register_mfcr = @import("CONDITION_REGISTER/MFCR.zig");
const condition_register_mtcrf = @import("CONDITION_REGISTER/MTCRF.zig");
const count_cntlzdx = @import("COUNT/CNTLZDX.zig");
const count_cntlzwx = @import("COUNT/CNTLZWX.zig");
const div_divdux = @import("DIV/DIVDUX.zig");
const div_divdx = @import("DIV/DIVDX.zig");
const div_divwux = @import("DIV/DIVWUX.zig");
const div_divwx = @import("DIV/DIVWX.zig");
const extend_extsbx = @import("EXTEND/EXTSBX.zig");
const extend_extshx = @import("EXTEND/EXTSHX.zig");
const extend_extswx = @import("EXTEND/EXTSWX.zig");
const fp_arith_faddsx = @import("FP_ARITH/FADDSX.zig");
const fp_arith_faddx = @import("FP_ARITH/FADDX.zig");
const fp_arith_fdivsx = @import("FP_ARITH/FDIVSX.zig");
const fp_arith_fdivx = @import("FP_ARITH/FDIVX.zig");
const fp_arith_fmulsx = @import("FP_ARITH/FMULSX.zig");
const fp_arith_fmulx = @import("FP_ARITH/FMULX.zig");
const fp_arith_fresx = @import("FP_ARITH/FRESX.zig");
const fp_arith_frsqrtex = @import("FP_ARITH/FRSQRTEX.zig");
const fp_arith_fsqrtsx = @import("FP_ARITH/FSQRTSX.zig");
const fp_arith_fsqrtx = @import("FP_ARITH/FSQRTX.zig");
const fp_arith_fsubsx = @import("FP_ARITH/FSUBSX.zig");
const fp_arith_fsubx = @import("FP_ARITH/FSUBX.zig");
const fp_compare_fcmpo = @import("FP_COMPARE/FCMPO.zig");
const fp_compare_fcmpu = @import("FP_COMPARE/FCMPU.zig");
const fp_convert_fcfidx = @import("FP_CONVERT/FCFIDX.zig");
const fp_convert_fctidx = @import("FP_CONVERT/FCTIDX.zig");
const fp_convert_fctidzx = @import("FP_CONVERT/FCTIDZX.zig");
const fp_convert_fctiwx = @import("FP_CONVERT/FCTIWX.zig");
const fp_convert_fctiwzx = @import("FP_CONVERT/FCTIWZX.zig");
const fp_convert_frspx = @import("FP_CONVERT/FRSPX.zig");
const fp_load_lfd = @import("FP_LOAD/LFD.zig");
const fp_load_lfdu = @import("FP_LOAD/LFDU.zig");
const fp_load_lfdux = @import("FP_LOAD/LFDUX.zig");
const fp_load_lfdx = @import("FP_LOAD/LFDX.zig");
const fp_load_lfs = @import("FP_LOAD/LFS.zig");
const fp_load_lfsu = @import("FP_LOAD/LFSU.zig");
const fp_load_lfsux = @import("FP_LOAD/LFSUX.zig");
const fp_load_lfsx = @import("FP_LOAD/LFSX.zig");
const fp_move_fabsx = @import("FP_MOVE/FABSX.zig");
const fp_move_fmrx = @import("FP_MOVE/FMRX.zig");
const fp_move_fnabsx = @import("FP_MOVE/FNABSX.zig");
const fp_move_fnegx = @import("FP_MOVE/FNEGX.zig");
const fp_move_fselx = @import("FP_MOVE/FSELX.zig");
const fp_multiply_add_fmaddsx = @import("FP_MULTIPLY_ADD/FMADDSX.zig");
const fp_multiply_add_fmaddx = @import("FP_MULTIPLY_ADD/FMADDX.zig");
const fp_multiply_add_fmsubsx = @import("FP_MULTIPLY_ADD/FMSUBSX.zig");
const fp_multiply_add_fmsubx = @import("FP_MULTIPLY_ADD/FMSUBX.zig");
const fp_multiply_add_fnmaddsx = @import("FP_MULTIPLY_ADD/FNMADDSX.zig");
const fp_multiply_add_fnmaddx = @import("FP_MULTIPLY_ADD/FNMADDX.zig");
const fp_multiply_add_fnmsubsx = @import("FP_MULTIPLY_ADD/FNMSUBSX.zig");
const fp_multiply_add_fnmsubx = @import("FP_MULTIPLY_ADD/FNMSUBX.zig");
const fp_status_mcrfs = @import("FP_STATUS/MCRFS.zig");
const fp_status_mffsx = @import("FP_STATUS/MFFSX.zig");
const fp_status_mtfsb0x = @import("FP_STATUS/MTFSB0X.zig");
const fp_status_mtfsb1x = @import("FP_STATUS/MTFSB1X.zig");
const fp_status_mtfsfix = @import("FP_STATUS/MTFSFIX.zig");
const fp_status_mtfsfx = @import("FP_STATUS/MTFSFX.zig");
const fp_store_stfd = @import("FP_STORE/STFD.zig");
const fp_store_stfdu = @import("FP_STORE/STFDU.zig");
const fp_store_stfdux = @import("FP_STORE/STFDUX.zig");
const fp_store_stfdx = @import("FP_STORE/STFDX.zig");
const fp_store_stfiwx = @import("FP_STORE/STFIWX.zig");
const fp_store_stfs = @import("FP_STORE/STFS.zig");
const fp_store_stfsu = @import("FP_STORE/STFSU.zig");
const fp_store_stfsux = @import("FP_STORE/STFSUX.zig");
const fp_store_stfsx = @import("FP_STORE/STFSX.zig");
const load_lbz = @import("LOAD/LBZ.zig");
const load_lbzu = @import("LOAD/LBZU.zig");
const load_ld = @import("LOAD/LD.zig");
const load_ldu = @import("LOAD/LDU.zig");
const load_lha = @import("LOAD/LHA.zig");
const load_lhau = @import("LOAD/LHAU.zig");
const load_lhz = @import("LOAD/LHZ.zig");
const load_lhzu = @import("LOAD/LHZU.zig");
const load_lwa = @import("LOAD/LWA.zig");
const load_lwz = @import("LOAD/LWZ.zig");
const load_lwzu = @import("LOAD/LWZU.zig");
const load_indexed_lbzux = @import("LOAD_INDEXED/LBZUX.zig");
const load_indexed_lbzx = @import("LOAD_INDEXED/LBZX.zig");
const load_indexed_ldux = @import("LOAD_INDEXED/LDUX.zig");
const load_indexed_ldx = @import("LOAD_INDEXED/LDX.zig");
const load_indexed_lhaux = @import("LOAD_INDEXED/LHAUX.zig");
const load_indexed_lhax = @import("LOAD_INDEXED/LHAX.zig");
const load_indexed_lhzux = @import("LOAD_INDEXED/LHZUX.zig");
const load_indexed_lhzx = @import("LOAD_INDEXED/LHZX.zig");
const load_indexed_lwaux = @import("LOAD_INDEXED/LWAUX.zig");
const load_indexed_lwax = @import("LOAD_INDEXED/LWAX.zig");
const load_indexed_lwzux = @import("LOAD_INDEXED/LWZUX.zig");
const load_indexed_lwzx = @import("LOAD_INDEXED/LWZX.zig");
const load_multiple_lmw = @import("LOAD_MULTIPLE/LMW.zig");
const load_multiple_lswi = @import("LOAD_MULTIPLE/LSWI.zig");
const load_multiple_lswx = @import("LOAD_MULTIPLE/LSWX.zig");
const logical_andcx = @import("LOGICAL/ANDCX.zig");
const logical_andisx = @import("LOGICAL/ANDISX.zig");
const logical_andix = @import("LOGICAL/ANDIX.zig");
const logical_andx = @import("LOGICAL/ANDX.zig");
const logical_eqvx = @import("LOGICAL/EQVX.zig");
const logical_nandx = @import("LOGICAL/NANDX.zig");
const logical_norx = @import("LOGICAL/NORX.zig");
const logical_orcx = @import("LOGICAL/ORCX.zig");
const logical_ori = @import("LOGICAL/ORI.zig");
const logical_oris = @import("LOGICAL/ORIS.zig");
const logical_orx = @import("LOGICAL/ORX.zig");
const logical_xori = @import("LOGICAL/XORI.zig");
const logical_xoris = @import("LOGICAL/XORIS.zig");
const logical_xorx = @import("LOGICAL/XORX.zig");
const mul_mulhdux = @import("MUL/MULHDUX.zig");
const mul_mulhdx = @import("MUL/MULHDX.zig");
const mul_mulhwux = @import("MUL/MULHWUX.zig");
const mul_mulhwx = @import("MUL/MULHWX.zig");
const mul_mulldx = @import("MUL/MULLDX.zig");
const mul_mulli = @import("MUL/MULLI.zig");
const mul_mullwx = @import("MUL/MULLWX.zig");
const rotate_rldclx = @import("ROTATE/RLDCLX.zig");
const rotate_rldcrx = @import("ROTATE/RLDCRX.zig");
const rotate_rldiclx = @import("ROTATE/RLDICLX.zig");
const rotate_rldicrx = @import("ROTATE/RLDICRX.zig");
const rotate_rldicx = @import("ROTATE/RLDICX.zig");
const rotate_rldimix = @import("ROTATE/RLDIMIX.zig");
const rotate_rlwimix = @import("ROTATE/RLWIMIX.zig");
const rotate_rlwinmx = @import("ROTATE/RLWINMX.zig");
const rotate_rlwnmx = @import("ROTATE/RLWNMX.zig");
const shift_sldx = @import("SHIFT/SLDX.zig");
const shift_slwx = @import("SHIFT/SLWX.zig");
const shift_sradix = @import("SHIFT/SRADIX.zig");
const shift_sradx = @import("SHIFT/SRADX.zig");
const shift_srawix = @import("SHIFT/SRAWIX.zig");
const shift_srawx = @import("SHIFT/SRAWX.zig");
const shift_srdx = @import("SHIFT/SRDX.zig");
const shift_srwx = @import("SHIFT/SRWX.zig");
const spr_mfspr = @import("SPR/MFSPR.zig");
const spr_mftb = @import("SPR/MFTB.zig");
const spr_mtspr = @import("SPR/MTSPR.zig");
const store_stb = @import("STORE/STB.zig");
const store_stbu = @import("STORE/STBU.zig");
const store_std = @import("STORE/STD.zig");
const store_stdu = @import("STORE/STDU.zig");
const store_sth = @import("STORE/STH.zig");
const store_sthu = @import("STORE/STHU.zig");
const store_stw = @import("STORE/STW.zig");
const store_stwu = @import("STORE/STWU.zig");
const store_indexed_stbux = @import("STORE_INDEXED/STBUX.zig");
const store_indexed_stbx = @import("STORE_INDEXED/STBX.zig");
const store_indexed_stdux = @import("STORE_INDEXED/STDUX.zig");
const store_indexed_stdx = @import("STORE_INDEXED/STDX.zig");
const store_indexed_sthux = @import("STORE_INDEXED/STHUX.zig");
const store_indexed_sthx = @import("STORE_INDEXED/STHX.zig");
const store_indexed_stwux = @import("STORE_INDEXED/STWUX.zig");
const store_indexed_stwx = @import("STORE_INDEXED/STWX.zig");
const store_multiple_stmw = @import("STORE_MULTIPLE/STMW.zig");
const store_multiple_stswi = @import("STORE_MULTIPLE/STSWI.zig");
const store_multiple_stswx = @import("STORE_MULTIPLE/STSWX.zig");
const sub_negx = @import("SUB/NEGX.zig");
const sub_subfcx = @import("SUB/SUBFCX.zig");
const sub_subfex = @import("SUB/SUBFEX.zig");
const sub_subfmex = @import("SUB/SUBFMEX.zig");
const sub_subfx = @import("SUB/SUBFX.zig");
const sub_subfzex = @import("SUB/SUBFZEX.zig");
const sync_eieio = @import("SYNC/EIEIO.zig");
const sync_isync = @import("SYNC/ISYNC.zig");
const sync_sync = @import("SYNC/SYNC.zig");
const system_mfmsr = @import("SYSTEM/MFMSR.zig");
const system_mtmsr = @import("SYSTEM/MTMSR.zig");
const system_mtmsrd = @import("SYSTEM/MTMSRD.zig");
const system_sc = @import("SYSTEM/SC.zig");
const system_subficx = @import("SYSTEM/SUBFICX.zig");
const trap_td = @import("TRAP/TD.zig");
const trap_tdi = @import("TRAP/TDI.zig");
const trap_tw = @import("TRAP/TW.zig");
const trap_twi = @import("TRAP/TWI.zig");
const vmx128_lvewx128 = @import("VMX128/LVEWX128.zig");
const vmx128_lvlx128 = @import("VMX128/LVLX128.zig");
const vmx128_lvlxl128 = @import("VMX128/LVLXL128.zig");
const vmx128_lvrx128 = @import("VMX128/LVRX128.zig");
const vmx128_lvrxl128 = @import("VMX128/LVRXL128.zig");
const vmx128_lvsl128 = @import("VMX128/LVSL128.zig");
const vmx128_lvsr128 = @import("VMX128/LVSR128.zig");
const vmx128_lvx128 = @import("VMX128/LVX128.zig");
const vmx128_lvxl128 = @import("VMX128/LVXL128.zig");
const vmx128_stvewx128 = @import("VMX128/STVEWX128.zig");
const vmx128_stvlx128 = @import("VMX128/STVLX128.zig");
const vmx128_stvlxl128 = @import("VMX128/STVLXL128.zig");
const vmx128_stvrx128 = @import("VMX128/STVRX128.zig");
const vmx128_stvrxl128 = @import("VMX128/STVRXL128.zig");
const vmx128_stvx128 = @import("VMX128/STVX128.zig");
const vmx128_stvxl128 = @import("VMX128/STVXL128.zig");
const vmx128_vaddfp128 = @import("VMX128/VADDFP128.zig");
const vmx128_vand128 = @import("VMX128/VAND128.zig");
const vmx128_vandc128 = @import("VMX128/VANDC128.zig");
const vmx128_vcfpsxws128 = @import("VMX128/VCFPSXWS128.zig");
const vmx128_vcfpuxws128 = @import("VMX128/VCFPUXWS128.zig");
const vmx128_vcmpbfp128 = @import("VMX128/VCMPBFP128.zig");
const vmx128_vcmpeqfp128 = @import("VMX128/VCMPEQFP128.zig");
const vmx128_vcmpequw128 = @import("VMX128/VCMPEQUW128.zig");
const vmx128_vcmpgefp128 = @import("VMX128/VCMPGEFP128.zig");
const vmx128_vcmpgtfp128 = @import("VMX128/VCMPGTFP128.zig");
const vmx128_vcsxwfp128 = @import("VMX128/VCSXWFP128.zig");
const vmx128_vcuxwfp128 = @import("VMX128/VCUXWFP128.zig");
const vmx128_vexptefp128 = @import("VMX128/VEXPTEFP128.zig");
const vmx128_vlogefp128 = @import("VMX128/VLOGEFP128.zig");
const vmx128_vmaddcfp128 = @import("VMX128/VMADDCFP128.zig");
const vmx128_vmaddfp128 = @import("VMX128/VMADDFP128.zig");
const vmx128_vmaxfp128 = @import("VMX128/VMAXFP128.zig");
const vmx128_vminfp128 = @import("VMX128/VMINFP128.zig");
const vmx128_vmrghw128 = @import("VMX128/VMRGHW128.zig");
const vmx128_vmrglw128 = @import("VMX128/VMRGLW128.zig");
const vmx128_vmsum3fp128 = @import("VMX128/VMSUM3FP128.zig");
const vmx128_vmsum4fp128 = @import("VMX128/VMSUM4FP128.zig");
const vmx128_vmulfp128 = @import("VMX128/VMULFP128.zig");
const vmx128_vnmsubfp128 = @import("VMX128/VNMSUBFP128.zig");
const vmx128_vnor128 = @import("VMX128/VNOR128.zig");
const vmx128_vor128 = @import("VMX128/VOR128.zig");
const vmx128_vperm128 = @import("VMX128/VPERM128.zig");
const vmx128_vpermwi128 = @import("VMX128/VPERMWI128.zig");
const vmx128_vpkd3d128 = @import("VMX128/VPKD3D128.zig");
const vmx128_vpkshss128 = @import("VMX128/VPKSHSS128.zig");
const vmx128_vpkshus128 = @import("VMX128/VPKSHUS128.zig");
const vmx128_vpkswss128 = @import("VMX128/VPKSWSS128.zig");
const vmx128_vpkswus128 = @import("VMX128/VPKSWUS128.zig");
const vmx128_vpkuhum128 = @import("VMX128/VPKUHUM128.zig");
const vmx128_vpkuhus128 = @import("VMX128/VPKUHUS128.zig");
const vmx128_vpkuwum128 = @import("VMX128/VPKUWUM128.zig");
const vmx128_vpkuwus128 = @import("VMX128/VPKUWUS128.zig");
const vmx128_vrefp128 = @import("VMX128/VREFP128.zig");
const vmx128_vrfim128 = @import("VMX128/VRFIM128.zig");
const vmx128_vrfin128 = @import("VMX128/VRFIN128.zig");
const vmx128_vrfip128 = @import("VMX128/VRFIP128.zig");
const vmx128_vrfiz128 = @import("VMX128/VRFIZ128.zig");
const vmx128_vrlimi128 = @import("VMX128/VRLIMI128.zig");
const vmx128_vrlw128 = @import("VMX128/VRLW128.zig");
const vmx128_vrsqrtefp128 = @import("VMX128/VRSQRTEFP128.zig");
const vmx128_vsel128 = @import("VMX128/VSEL128.zig");
const vmx128_vsldoi128 = @import("VMX128/VSLDOI128.zig");
const vmx128_vslo128 = @import("VMX128/VSLO128.zig");
const vmx128_vslw128 = @import("VMX128/VSLW128.zig");
const vmx128_vspltisw128 = @import("VMX128/VSPLTISW128.zig");
const vmx128_vspltw128 = @import("VMX128/VSPLTW128.zig");
const vmx128_vsraw128 = @import("VMX128/VSRAW128.zig");
const vmx128_vsro128 = @import("VMX128/VSRO128.zig");
const vmx128_vsrw128 = @import("VMX128/VSRW128.zig");
const vmx128_vsubfp128 = @import("VMX128/VSUBFP128.zig");
const vmx128_vupkd3d128 = @import("VMX128/VUPKD3D128.zig");
const vmx128_vupkhsb128 = @import("VMX128/VUPKHSB128.zig");
const vmx128_vupklsb128 = @import("VMX128/VUPKLSB128.zig");
const vmx128_vxor128 = @import("VMX128/VXOR128.zig");
const vmx_arith_vaddcuw = @import("VMX_ARITH/VADDCUW.zig");
const vmx_arith_vaddfp = @import("VMX_ARITH/VADDFP.zig");
const vmx_arith_vaddsbs = @import("VMX_ARITH/VADDSBS.zig");
const vmx_arith_vaddshs = @import("VMX_ARITH/VADDSHS.zig");
const vmx_arith_vaddsws = @import("VMX_ARITH/VADDSWS.zig");
const vmx_arith_vaddubm = @import("VMX_ARITH/VADDUBM.zig");
const vmx_arith_vaddubs = @import("VMX_ARITH/VADDUBS.zig");
const vmx_arith_vadduhm = @import("VMX_ARITH/VADDUHM.zig");
const vmx_arith_vadduhs = @import("VMX_ARITH/VADDUHS.zig");
const vmx_arith_vadduwm = @import("VMX_ARITH/VADDUWM.zig");
const vmx_arith_vadduws = @import("VMX_ARITH/VADDUWS.zig");
const vmx_arith_vavgsb = @import("VMX_ARITH/VAVGSB.zig");
const vmx_arith_vavgsh = @import("VMX_ARITH/VAVGSH.zig");
const vmx_arith_vavgsw = @import("VMX_ARITH/VAVGSW.zig");
const vmx_arith_vavgub = @import("VMX_ARITH/VAVGUB.zig");
const vmx_arith_vavguh = @import("VMX_ARITH/VAVGUH.zig");
const vmx_arith_vavguw = @import("VMX_ARITH/VAVGUW.zig");
const vmx_arith_vmaxfp = @import("VMX_ARITH/VMAXFP.zig");
const vmx_arith_vmaxsb = @import("VMX_ARITH/VMAXSB.zig");
const vmx_arith_vmaxsh = @import("VMX_ARITH/VMAXSH.zig");
const vmx_arith_vmaxsw = @import("VMX_ARITH/VMAXSW.zig");
const vmx_arith_vmaxub = @import("VMX_ARITH/VMAXUB.zig");
const vmx_arith_vmaxuh = @import("VMX_ARITH/VMAXUH.zig");
const vmx_arith_vmaxuw = @import("VMX_ARITH/VMAXUW.zig");
const vmx_arith_vminfp = @import("VMX_ARITH/VMINFP.zig");
const vmx_arith_vminsb = @import("VMX_ARITH/VMINSB.zig");
const vmx_arith_vminsh = @import("VMX_ARITH/VMINSH.zig");
const vmx_arith_vminsw = @import("VMX_ARITH/VMINSW.zig");
const vmx_arith_vminub = @import("VMX_ARITH/VMINUB.zig");
const vmx_arith_vminuh = @import("VMX_ARITH/VMINUH.zig");
const vmx_arith_vminuw = @import("VMX_ARITH/VMINUW.zig");
const vmx_arith_vmulesb = @import("VMX_ARITH/VMULESB.zig");
const vmx_arith_vmulesh = @import("VMX_ARITH/VMULESH.zig");
const vmx_arith_vmuleub = @import("VMX_ARITH/VMULEUB.zig");
const vmx_arith_vmuleuh = @import("VMX_ARITH/VMULEUH.zig");
const vmx_arith_vmulosb = @import("VMX_ARITH/VMULOSB.zig");
const vmx_arith_vmulosh = @import("VMX_ARITH/VMULOSH.zig");
const vmx_arith_vmuloub = @import("VMX_ARITH/VMULOUB.zig");
const vmx_arith_vmulouh = @import("VMX_ARITH/VMULOUH.zig");
const vmx_arith_vsubcuw = @import("VMX_ARITH/VSUBCUW.zig");
const vmx_arith_vsubfp = @import("VMX_ARITH/VSUBFP.zig");
const vmx_arith_vsubsbs = @import("VMX_ARITH/VSUBSBS.zig");
const vmx_arith_vsubshs = @import("VMX_ARITH/VSUBSHS.zig");
const vmx_arith_vsubsws = @import("VMX_ARITH/VSUBSWS.zig");
const vmx_arith_vsububm = @import("VMX_ARITH/VSUBUBM.zig");
const vmx_arith_vsububs = @import("VMX_ARITH/VSUBUBS.zig");
const vmx_arith_vsubuhm = @import("VMX_ARITH/VSUBUHM.zig");
const vmx_arith_vsubuhs = @import("VMX_ARITH/VSUBUHS.zig");
const vmx_arith_vsubuwm = @import("VMX_ARITH/VSUBUWM.zig");
const vmx_arith_vsubuws = @import("VMX_ARITH/VSUBUWS.zig");
const vmx_compare_vcmpbfp = @import("VMX_COMPARE/VCMPBFP.zig");
const vmx_compare_vcmpeqfp = @import("VMX_COMPARE/VCMPEQFP.zig");
const vmx_compare_vcmpequb = @import("VMX_COMPARE/VCMPEQUB.zig");
const vmx_compare_vcmpequh = @import("VMX_COMPARE/VCMPEQUH.zig");
const vmx_compare_vcmpequw = @import("VMX_COMPARE/VCMPEQUW.zig");
const vmx_compare_vcmpgefp = @import("VMX_COMPARE/VCMPGEFP.zig");
const vmx_compare_vcmpgtfp = @import("VMX_COMPARE/VCMPGTFP.zig");
const vmx_compare_vcmpgtsb = @import("VMX_COMPARE/VCMPGTSB.zig");
const vmx_compare_vcmpgtsh = @import("VMX_COMPARE/VCMPGTSH.zig");
const vmx_compare_vcmpgtsw = @import("VMX_COMPARE/VCMPGTSW.zig");
const vmx_compare_vcmpgtub = @import("VMX_COMPARE/VCMPGTUB.zig");
const vmx_compare_vcmpgtuh = @import("VMX_COMPARE/VCMPGTUH.zig");
const vmx_compare_vcmpgtuw = @import("VMX_COMPARE/VCMPGTUW.zig");
const vmx_convert_vcfsx = @import("VMX_CONVERT/VCFSX.zig");
const vmx_convert_vcfux = @import("VMX_CONVERT/VCFUX.zig");
const vmx_convert_vctsxs = @import("VMX_CONVERT/VCTSXS.zig");
const vmx_convert_vctuxs = @import("VMX_CONVERT/VCTUXS.zig");
const vmx_convert_vrfim = @import("VMX_CONVERT/VRFIM.zig");
const vmx_convert_vrfin = @import("VMX_CONVERT/VRFIN.zig");
const vmx_convert_vrfip = @import("VMX_CONVERT/VRFIP.zig");
const vmx_convert_vrfiz = @import("VMX_CONVERT/VRFIZ.zig");
const vmx_estimate_vexptefp = @import("VMX_ESTIMATE/VEXPTEFP.zig");
const vmx_estimate_vlogefp = @import("VMX_ESTIMATE/VLOGEFP.zig");
const vmx_estimate_vrefp = @import("VMX_ESTIMATE/VREFP.zig");
const vmx_estimate_vrsqrtefp = @import("VMX_ESTIMATE/VRSQRTEFP.zig");
const vmx_load_lvebx = @import("VMX_LOAD/LVEBX.zig");
const vmx_load_lvehx = @import("VMX_LOAD/LVEHX.zig");
const vmx_load_lvewx = @import("VMX_LOAD/LVEWX.zig");
const vmx_load_lvlx = @import("VMX_LOAD/LVLX.zig");
const vmx_load_lvlxl = @import("VMX_LOAD/LVLXL.zig");
const vmx_load_lvrx = @import("VMX_LOAD/LVRX.zig");
const vmx_load_lvrxl = @import("VMX_LOAD/LVRXL.zig");
const vmx_load_lvsl = @import("VMX_LOAD/LVSL.zig");
const vmx_load_lvsr = @import("VMX_LOAD/LVSR.zig");
const vmx_load_lvx = @import("VMX_LOAD/LVX.zig");
const vmx_load_lvxl = @import("VMX_LOAD/LVXL.zig");
const vmx_logical_vand = @import("VMX_LOGICAL/VAND.zig");
const vmx_logical_vandc = @import("VMX_LOGICAL/VANDC.zig");
const vmx_logical_vnor = @import("VMX_LOGICAL/VNOR.zig");
const vmx_logical_vor = @import("VMX_LOGICAL/VOR.zig");
const vmx_logical_vxor = @import("VMX_LOGICAL/VXOR.zig");
const vmx_multiply_add_vmaddfp = @import("VMX_MULTIPLY_ADD/VMADDFP.zig");
const vmx_multiply_add_vmhaddshs = @import("VMX_MULTIPLY_ADD/VMHADDSHS.zig");
const vmx_multiply_add_vmhraddshs = @import("VMX_MULTIPLY_ADD/VMHRADDSHS.zig");
const vmx_multiply_add_vmladduhm = @import("VMX_MULTIPLY_ADD/VMLADDUHM.zig");
const vmx_multiply_add_vmsummbm = @import("VMX_MULTIPLY_ADD/VMSUMMBM.zig");
const vmx_multiply_add_vmsumshm = @import("VMX_MULTIPLY_ADD/VMSUMSHM.zig");
const vmx_multiply_add_vmsumshs = @import("VMX_MULTIPLY_ADD/VMSUMSHS.zig");
const vmx_multiply_add_vmsumubm = @import("VMX_MULTIPLY_ADD/VMSUMUBM.zig");
const vmx_multiply_add_vmsumuhm = @import("VMX_MULTIPLY_ADD/VMSUMUHM.zig");
const vmx_multiply_add_vmsumuhs = @import("VMX_MULTIPLY_ADD/VMSUMUHS.zig");
const vmx_multiply_add_vnmsubfp = @import("VMX_MULTIPLY_ADD/VNMSUBFP.zig");
const vmx_multiply_add_vsum2sws = @import("VMX_MULTIPLY_ADD/VSUM2SWS.zig");
const vmx_multiply_add_vsum4sbs = @import("VMX_MULTIPLY_ADD/VSUM4SBS.zig");
const vmx_multiply_add_vsum4shs = @import("VMX_MULTIPLY_ADD/VSUM4SHS.zig");
const vmx_multiply_add_vsum4ubs = @import("VMX_MULTIPLY_ADD/VSUM4UBS.zig");
const vmx_multiply_add_vsumsws = @import("VMX_MULTIPLY_ADD/VSUMSWS.zig");
const vmx_pack_vpkpx = @import("VMX_PACK/VPKPX.zig");
const vmx_pack_vpkshss = @import("VMX_PACK/VPKSHSS.zig");
const vmx_pack_vpkshus = @import("VMX_PACK/VPKSHUS.zig");
const vmx_pack_vpkswss = @import("VMX_PACK/VPKSWSS.zig");
const vmx_pack_vpkswus = @import("VMX_PACK/VPKSWUS.zig");
const vmx_pack_vpkuhum = @import("VMX_PACK/VPKUHUM.zig");
const vmx_pack_vpkuhus = @import("VMX_PACK/VPKUHUS.zig");
const vmx_pack_vpkuwum = @import("VMX_PACK/VPKUWUM.zig");
const vmx_pack_vpkuwus = @import("VMX_PACK/VPKUWUS.zig");
const vmx_pack_vupkhpx = @import("VMX_PACK/VUPKHPX.zig");
const vmx_pack_vupkhsb = @import("VMX_PACK/VUPKHSB.zig");
const vmx_pack_vupkhsh = @import("VMX_PACK/VUPKHSH.zig");
const vmx_pack_vupklpx = @import("VMX_PACK/VUPKLPX.zig");
const vmx_pack_vupklsb = @import("VMX_PACK/VUPKLSB.zig");
const vmx_pack_vupklsh = @import("VMX_PACK/VUPKLSH.zig");
const vmx_permute_vmrghb = @import("VMX_PERMUTE/VMRGHB.zig");
const vmx_permute_vmrghh = @import("VMX_PERMUTE/VMRGHH.zig");
const vmx_permute_vmrghw = @import("VMX_PERMUTE/VMRGHW.zig");
const vmx_permute_vmrglb = @import("VMX_PERMUTE/VMRGLB.zig");
const vmx_permute_vmrglh = @import("VMX_PERMUTE/VMRGLH.zig");
const vmx_permute_vmrglw = @import("VMX_PERMUTE/VMRGLW.zig");
const vmx_permute_vperm = @import("VMX_PERMUTE/VPERM.zig");
const vmx_permute_vsel = @import("VMX_PERMUTE/VSEL.zig");
const vmx_permute_vsldoi = @import("VMX_PERMUTE/VSLDOI.zig");
const vmx_shift_vrlb = @import("VMX_SHIFT/VRLB.zig");
const vmx_shift_vrlh = @import("VMX_SHIFT/VRLH.zig");
const vmx_shift_vrlw = @import("VMX_SHIFT/VRLW.zig");
const vmx_shift_vsl = @import("VMX_SHIFT/VSL.zig");
const vmx_shift_vslb = @import("VMX_SHIFT/VSLB.zig");
const vmx_shift_vslh = @import("VMX_SHIFT/VSLH.zig");
const vmx_shift_vslo = @import("VMX_SHIFT/VSLO.zig");
const vmx_shift_vslw = @import("VMX_SHIFT/VSLW.zig");
const vmx_shift_vsr = @import("VMX_SHIFT/VSR.zig");
const vmx_shift_vsrab = @import("VMX_SHIFT/VSRAB.zig");
const vmx_shift_vsrah = @import("VMX_SHIFT/VSRAH.zig");
const vmx_shift_vsraw = @import("VMX_SHIFT/VSRAW.zig");
const vmx_shift_vsrb = @import("VMX_SHIFT/VSRB.zig");
const vmx_shift_vsrh = @import("VMX_SHIFT/VSRH.zig");
const vmx_shift_vsro = @import("VMX_SHIFT/VSRO.zig");
const vmx_shift_vsrw = @import("VMX_SHIFT/VSRW.zig");
const vmx_splat_vspltb = @import("VMX_SPLAT/VSPLTB.zig");
const vmx_splat_vsplth = @import("VMX_SPLAT/VSPLTH.zig");
const vmx_splat_vspltisb = @import("VMX_SPLAT/VSPLTISB.zig");
const vmx_splat_vspltish = @import("VMX_SPLAT/VSPLTISH.zig");
const vmx_splat_vspltisw = @import("VMX_SPLAT/VSPLTISW.zig");
const vmx_splat_vspltw = @import("VMX_SPLAT/VSPLTW.zig");
const vmx_status_mfvscr = @import("VMX_STATUS/MFVSCR.zig");
const vmx_status_mtvscr = @import("VMX_STATUS/MTVSCR.zig");
const vmx_store_stvebx = @import("VMX_STORE/STVEBX.zig");
const vmx_store_stvehx = @import("VMX_STORE/STVEHX.zig");
const vmx_store_stvewx = @import("VMX_STORE/STVEWX.zig");
const vmx_store_stvlx = @import("VMX_STORE/STVLX.zig");
const vmx_store_stvlxl = @import("VMX_STORE/STVLXL.zig");
const vmx_store_stvrx = @import("VMX_STORE/STVRX.zig");
const vmx_store_stvrxl = @import("VMX_STORE/STVRXL.zig");
const vmx_store_stvx = @import("VMX_STORE/STVX.zig");
const vmx_store_stvxl = @import("VMX_STORE/STVXL.zig");

pub const TableMetadata = struct {
    name: []const u8,
    mnemonic: []const u8,
    category: []const u8,
    form: []const u8,
    handler: []const u8,
    jit_lowering: []const u8,
    encoding_count: usize,
    source_path: []const u8,
    primary_opcode: u8,
    has_semantic: bool,
    has_registers: bool,
    has_condition_model: bool,
};

pub const InstructionTable = struct {
    family: []const u8,
    path: []const u8,
    source: []const u8,

    pub fn metadata(self: InstructionTable) TableMetadata {
        return .{
            .name = stringAssignment(self.source, "name") orelse mnemonicFromPath(self.path),
            .mnemonic = stringAssignment(self.source, "mnemonic") orelse mnemonicFromPath(self.path),
            .category = stringAssignment(self.source, "category") orelse "documented_contract",
            .form = stringAssignment(self.source, "form") orelse "unknown",
            .handler = anyStringAssignment(self.source, &[_][]const u8{ "handler", "ppc_handler" }) orelse "ppc_documented_contract_handler",
            .jit_lowering = anyStringAssignment(self.source, &[_][]const u8{ "jit_lowering", "neon_lowering", "arm64_lowering" }) orelse "arm64_documented_contract_fallback",
            .encoding_count = countEncodingRows(self.source),
            .source_path = self.path,
            .primary_opcode = numberAssignment(self.source, "primary_opcode") orelse 0xFF,
            .has_semantic = hasAnyAssignment(self.source, &[_][]const u8{ "semantic", "operation" }),
            .has_registers = hasAnyAssignment(self.source, &[_][]const u8{ "reads", "writes" }),
            .has_condition_model = hasAnyAssignment(self.source, &[_][]const u8{ "flags_written", "special_registers" }),
        };
    }

    pub fn validate(self: InstructionTable) void {
        const meta = self.metadata();
        runtime_abi.isa.validatePpcTable(.{
            .name = meta.name,
            .mnemonic = meta.mnemonic,
            .category = meta.category,
            .form = meta.form,
            .handler = meta.handler,
            .jit_lowering = meta.jit_lowering,
            .source_path = meta.source_path,
            .encoding_count = meta.encoding_count,
            .primary_opcode = meta.primary_opcode,
            .has_semantic = meta.has_semantic,
            .has_registers = meta.has_registers,
            .has_condition_model = meta.has_condition_model,
        });
    }
};

pub const tables = blk: {
    @setEvalBranchQuota(27300);
    break :blk [_]InstructionTable{
        entry(add_addcx.family, add_addcx.path, add_addcx.source),
        entry(add_addex.family, add_addex.path, add_addex.source),
        entry(add_addi.family, add_addi.path, add_addi.source),
        entry(add_addic.family, add_addic.path, add_addic.source),
        entry(add_addicx.family, add_addicx.path, add_addicx.source),
        entry(add_addis.family, add_addis.path, add_addis.source),
        entry(add_addmex.family, add_addmex.path, add_addmex.source),
        entry(add_addx.family, add_addx.path, add_addx.source),
        entry(add_addzex.family, add_addzex.path, add_addzex.source),
        entry(atomic_ldarx.family, atomic_ldarx.path, atomic_ldarx.source),
        entry(atomic_lwarx.family, atomic_lwarx.path, atomic_lwarx.source),
        entry(atomic_stdcx.family, atomic_stdcx.path, atomic_stdcx.source),
        entry(atomic_stwcx.family, atomic_stwcx.path, atomic_stwcx.source),
        entry(branch_bcctrx.family, branch_bcctrx.path, branch_bcctrx.source),
        entry(branch_bclrx.family, branch_bclrx.path, branch_bclrx.source),
        entry(branch_bcx.family, branch_bcx.path, branch_bcx.source),
        entry(branch_bx.family, branch_bx.path, branch_bx.source),
        entry(byte_reverse_ldbrx.family, byte_reverse_ldbrx.path, byte_reverse_ldbrx.source),
        entry(byte_reverse_lhbrx.family, byte_reverse_lhbrx.path, byte_reverse_lhbrx.source),
        entry(byte_reverse_lwbrx.family, byte_reverse_lwbrx.path, byte_reverse_lwbrx.source),
        entry(byte_reverse_stdbrx.family, byte_reverse_stdbrx.path, byte_reverse_stdbrx.source),
        entry(byte_reverse_sthbrx.family, byte_reverse_sthbrx.path, byte_reverse_sthbrx.source),
        entry(byte_reverse_stwbrx.family, byte_reverse_stwbrx.path, byte_reverse_stwbrx.source),
        entry(cache_dcbf.family, cache_dcbf.path, cache_dcbf.source),
        entry(cache_dcbi.family, cache_dcbi.path, cache_dcbi.source),
        entry(cache_dcbst.family, cache_dcbst.path, cache_dcbst.source),
        entry(cache_dcbt.family, cache_dcbt.path, cache_dcbt.source),
        entry(cache_dcbtst.family, cache_dcbtst.path, cache_dcbtst.source),
        entry(cache_dcbz.family, cache_dcbz.path, cache_dcbz.source),
        entry(cache_dcbz128.family, cache_dcbz128.path, cache_dcbz128.source),
        entry(cache_icbi.family, cache_icbi.path, cache_icbi.source),
        entry(cmp_cmp.family, cmp_cmp.path, cmp_cmp.source),
        entry(cmp_cmpi.family, cmp_cmpi.path, cmp_cmpi.source),
        entry(cmp_cmpl.family, cmp_cmpl.path, cmp_cmpl.source),
        entry(cmp_cmpli.family, cmp_cmpli.path, cmp_cmpli.source),
        entry(condition_register_crand.family, condition_register_crand.path, condition_register_crand.source),
        entry(condition_register_crandc.family, condition_register_crandc.path, condition_register_crandc.source),
        entry(condition_register_creqv.family, condition_register_creqv.path, condition_register_creqv.source),
        entry(condition_register_crnand.family, condition_register_crnand.path, condition_register_crnand.source),
        entry(condition_register_crnor.family, condition_register_crnor.path, condition_register_crnor.source),
        entry(condition_register_cror.family, condition_register_cror.path, condition_register_cror.source),
        entry(condition_register_crorc.family, condition_register_crorc.path, condition_register_crorc.source),
        entry(condition_register_crxor.family, condition_register_crxor.path, condition_register_crxor.source),
        entry(condition_register_mcrf.family, condition_register_mcrf.path, condition_register_mcrf.source),
        entry(condition_register_mcrxr.family, condition_register_mcrxr.path, condition_register_mcrxr.source),
        entry(condition_register_mfcr.family, condition_register_mfcr.path, condition_register_mfcr.source),
        entry(condition_register_mtcrf.family, condition_register_mtcrf.path, condition_register_mtcrf.source),
        entry(count_cntlzdx.family, count_cntlzdx.path, count_cntlzdx.source),
        entry(count_cntlzwx.family, count_cntlzwx.path, count_cntlzwx.source),
        entry(div_divdux.family, div_divdux.path, div_divdux.source),
        entry(div_divdx.family, div_divdx.path, div_divdx.source),
        entry(div_divwux.family, div_divwux.path, div_divwux.source),
        entry(div_divwx.family, div_divwx.path, div_divwx.source),
        entry(extend_extsbx.family, extend_extsbx.path, extend_extsbx.source),
        entry(extend_extshx.family, extend_extshx.path, extend_extshx.source),
        entry(extend_extswx.family, extend_extswx.path, extend_extswx.source),
        entry(fp_arith_faddsx.family, fp_arith_faddsx.path, fp_arith_faddsx.source),
        entry(fp_arith_faddx.family, fp_arith_faddx.path, fp_arith_faddx.source),
        entry(fp_arith_fdivsx.family, fp_arith_fdivsx.path, fp_arith_fdivsx.source),
        entry(fp_arith_fdivx.family, fp_arith_fdivx.path, fp_arith_fdivx.source),
        entry(fp_arith_fmulsx.family, fp_arith_fmulsx.path, fp_arith_fmulsx.source),
        entry(fp_arith_fmulx.family, fp_arith_fmulx.path, fp_arith_fmulx.source),
        entry(fp_arith_fresx.family, fp_arith_fresx.path, fp_arith_fresx.source),
        entry(fp_arith_frsqrtex.family, fp_arith_frsqrtex.path, fp_arith_frsqrtex.source),
        entry(fp_arith_fsqrtsx.family, fp_arith_fsqrtsx.path, fp_arith_fsqrtsx.source),
        entry(fp_arith_fsqrtx.family, fp_arith_fsqrtx.path, fp_arith_fsqrtx.source),
        entry(fp_arith_fsubsx.family, fp_arith_fsubsx.path, fp_arith_fsubsx.source),
        entry(fp_arith_fsubx.family, fp_arith_fsubx.path, fp_arith_fsubx.source),
        entry(fp_compare_fcmpo.family, fp_compare_fcmpo.path, fp_compare_fcmpo.source),
        entry(fp_compare_fcmpu.family, fp_compare_fcmpu.path, fp_compare_fcmpu.source),
        entry(fp_convert_fcfidx.family, fp_convert_fcfidx.path, fp_convert_fcfidx.source),
        entry(fp_convert_fctidx.family, fp_convert_fctidx.path, fp_convert_fctidx.source),
        entry(fp_convert_fctidzx.family, fp_convert_fctidzx.path, fp_convert_fctidzx.source),
        entry(fp_convert_fctiwx.family, fp_convert_fctiwx.path, fp_convert_fctiwx.source),
        entry(fp_convert_fctiwzx.family, fp_convert_fctiwzx.path, fp_convert_fctiwzx.source),
        entry(fp_convert_frspx.family, fp_convert_frspx.path, fp_convert_frspx.source),
        entry(fp_load_lfd.family, fp_load_lfd.path, fp_load_lfd.source),
        entry(fp_load_lfdu.family, fp_load_lfdu.path, fp_load_lfdu.source),
        entry(fp_load_lfdux.family, fp_load_lfdux.path, fp_load_lfdux.source),
        entry(fp_load_lfdx.family, fp_load_lfdx.path, fp_load_lfdx.source),
        entry(fp_load_lfs.family, fp_load_lfs.path, fp_load_lfs.source),
        entry(fp_load_lfsu.family, fp_load_lfsu.path, fp_load_lfsu.source),
        entry(fp_load_lfsux.family, fp_load_lfsux.path, fp_load_lfsux.source),
        entry(fp_load_lfsx.family, fp_load_lfsx.path, fp_load_lfsx.source),
        entry(fp_move_fabsx.family, fp_move_fabsx.path, fp_move_fabsx.source),
        entry(fp_move_fmrx.family, fp_move_fmrx.path, fp_move_fmrx.source),
        entry(fp_move_fnabsx.family, fp_move_fnabsx.path, fp_move_fnabsx.source),
        entry(fp_move_fnegx.family, fp_move_fnegx.path, fp_move_fnegx.source),
        entry(fp_move_fselx.family, fp_move_fselx.path, fp_move_fselx.source),
        entry(fp_multiply_add_fmaddsx.family, fp_multiply_add_fmaddsx.path, fp_multiply_add_fmaddsx.source),
        entry(fp_multiply_add_fmaddx.family, fp_multiply_add_fmaddx.path, fp_multiply_add_fmaddx.source),
        entry(fp_multiply_add_fmsubsx.family, fp_multiply_add_fmsubsx.path, fp_multiply_add_fmsubsx.source),
        entry(fp_multiply_add_fmsubx.family, fp_multiply_add_fmsubx.path, fp_multiply_add_fmsubx.source),
        entry(fp_multiply_add_fnmaddsx.family, fp_multiply_add_fnmaddsx.path, fp_multiply_add_fnmaddsx.source),
        entry(fp_multiply_add_fnmaddx.family, fp_multiply_add_fnmaddx.path, fp_multiply_add_fnmaddx.source),
        entry(fp_multiply_add_fnmsubsx.family, fp_multiply_add_fnmsubsx.path, fp_multiply_add_fnmsubsx.source),
        entry(fp_multiply_add_fnmsubx.family, fp_multiply_add_fnmsubx.path, fp_multiply_add_fnmsubx.source),
        entry(fp_status_mcrfs.family, fp_status_mcrfs.path, fp_status_mcrfs.source),
        entry(fp_status_mffsx.family, fp_status_mffsx.path, fp_status_mffsx.source),
        entry(fp_status_mtfsb0x.family, fp_status_mtfsb0x.path, fp_status_mtfsb0x.source),
        entry(fp_status_mtfsb1x.family, fp_status_mtfsb1x.path, fp_status_mtfsb1x.source),
        entry(fp_status_mtfsfix.family, fp_status_mtfsfix.path, fp_status_mtfsfix.source),
        entry(fp_status_mtfsfx.family, fp_status_mtfsfx.path, fp_status_mtfsfx.source),
        entry(fp_store_stfd.family, fp_store_stfd.path, fp_store_stfd.source),
        entry(fp_store_stfdu.family, fp_store_stfdu.path, fp_store_stfdu.source),
        entry(fp_store_stfdux.family, fp_store_stfdux.path, fp_store_stfdux.source),
        entry(fp_store_stfdx.family, fp_store_stfdx.path, fp_store_stfdx.source),
        entry(fp_store_stfiwx.family, fp_store_stfiwx.path, fp_store_stfiwx.source),
        entry(fp_store_stfs.family, fp_store_stfs.path, fp_store_stfs.source),
        entry(fp_store_stfsu.family, fp_store_stfsu.path, fp_store_stfsu.source),
        entry(fp_store_stfsux.family, fp_store_stfsux.path, fp_store_stfsux.source),
        entry(fp_store_stfsx.family, fp_store_stfsx.path, fp_store_stfsx.source),
        entry(load_lbz.family, load_lbz.path, load_lbz.source),
        entry(load_lbzu.family, load_lbzu.path, load_lbzu.source),
        entry(load_ld.family, load_ld.path, load_ld.source),
        entry(load_ldu.family, load_ldu.path, load_ldu.source),
        entry(load_lha.family, load_lha.path, load_lha.source),
        entry(load_lhau.family, load_lhau.path, load_lhau.source),
        entry(load_lhz.family, load_lhz.path, load_lhz.source),
        entry(load_lhzu.family, load_lhzu.path, load_lhzu.source),
        entry(load_lwa.family, load_lwa.path, load_lwa.source),
        entry(load_lwz.family, load_lwz.path, load_lwz.source),
        entry(load_lwzu.family, load_lwzu.path, load_lwzu.source),
        entry(load_indexed_lbzux.family, load_indexed_lbzux.path, load_indexed_lbzux.source),
        entry(load_indexed_lbzx.family, load_indexed_lbzx.path, load_indexed_lbzx.source),
        entry(load_indexed_ldux.family, load_indexed_ldux.path, load_indexed_ldux.source),
        entry(load_indexed_ldx.family, load_indexed_ldx.path, load_indexed_ldx.source),
        entry(load_indexed_lhaux.family, load_indexed_lhaux.path, load_indexed_lhaux.source),
        entry(load_indexed_lhax.family, load_indexed_lhax.path, load_indexed_lhax.source),
        entry(load_indexed_lhzux.family, load_indexed_lhzux.path, load_indexed_lhzux.source),
        entry(load_indexed_lhzx.family, load_indexed_lhzx.path, load_indexed_lhzx.source),
        entry(load_indexed_lwaux.family, load_indexed_lwaux.path, load_indexed_lwaux.source),
        entry(load_indexed_lwax.family, load_indexed_lwax.path, load_indexed_lwax.source),
        entry(load_indexed_lwzux.family, load_indexed_lwzux.path, load_indexed_lwzux.source),
        entry(load_indexed_lwzx.family, load_indexed_lwzx.path, load_indexed_lwzx.source),
        entry(load_multiple_lmw.family, load_multiple_lmw.path, load_multiple_lmw.source),
        entry(load_multiple_lswi.family, load_multiple_lswi.path, load_multiple_lswi.source),
        entry(load_multiple_lswx.family, load_multiple_lswx.path, load_multiple_lswx.source),
        entry(logical_andcx.family, logical_andcx.path, logical_andcx.source),
        entry(logical_andisx.family, logical_andisx.path, logical_andisx.source),
        entry(logical_andix.family, logical_andix.path, logical_andix.source),
        entry(logical_andx.family, logical_andx.path, logical_andx.source),
        entry(logical_eqvx.family, logical_eqvx.path, logical_eqvx.source),
        entry(logical_nandx.family, logical_nandx.path, logical_nandx.source),
        entry(logical_norx.family, logical_norx.path, logical_norx.source),
        entry(logical_orcx.family, logical_orcx.path, logical_orcx.source),
        entry(logical_ori.family, logical_ori.path, logical_ori.source),
        entry(logical_oris.family, logical_oris.path, logical_oris.source),
        entry(logical_orx.family, logical_orx.path, logical_orx.source),
        entry(logical_xori.family, logical_xori.path, logical_xori.source),
        entry(logical_xoris.family, logical_xoris.path, logical_xoris.source),
        entry(logical_xorx.family, logical_xorx.path, logical_xorx.source),
        entry(mul_mulhdux.family, mul_mulhdux.path, mul_mulhdux.source),
        entry(mul_mulhdx.family, mul_mulhdx.path, mul_mulhdx.source),
        entry(mul_mulhwux.family, mul_mulhwux.path, mul_mulhwux.source),
        entry(mul_mulhwx.family, mul_mulhwx.path, mul_mulhwx.source),
        entry(mul_mulldx.family, mul_mulldx.path, mul_mulldx.source),
        entry(mul_mulli.family, mul_mulli.path, mul_mulli.source),
        entry(mul_mullwx.family, mul_mullwx.path, mul_mullwx.source),
        entry(rotate_rldclx.family, rotate_rldclx.path, rotate_rldclx.source),
        entry(rotate_rldcrx.family, rotate_rldcrx.path, rotate_rldcrx.source),
        entry(rotate_rldiclx.family, rotate_rldiclx.path, rotate_rldiclx.source),
        entry(rotate_rldicrx.family, rotate_rldicrx.path, rotate_rldicrx.source),
        entry(rotate_rldicx.family, rotate_rldicx.path, rotate_rldicx.source),
        entry(rotate_rldimix.family, rotate_rldimix.path, rotate_rldimix.source),
        entry(rotate_rlwimix.family, rotate_rlwimix.path, rotate_rlwimix.source),
        entry(rotate_rlwinmx.family, rotate_rlwinmx.path, rotate_rlwinmx.source),
        entry(rotate_rlwnmx.family, rotate_rlwnmx.path, rotate_rlwnmx.source),
        entry(shift_sldx.family, shift_sldx.path, shift_sldx.source),
        entry(shift_slwx.family, shift_slwx.path, shift_slwx.source),
        entry(shift_sradix.family, shift_sradix.path, shift_sradix.source),
        entry(shift_sradx.family, shift_sradx.path, shift_sradx.source),
        entry(shift_srawix.family, shift_srawix.path, shift_srawix.source),
        entry(shift_srawx.family, shift_srawx.path, shift_srawx.source),
        entry(shift_srdx.family, shift_srdx.path, shift_srdx.source),
        entry(shift_srwx.family, shift_srwx.path, shift_srwx.source),
        entry(spr_mfspr.family, spr_mfspr.path, spr_mfspr.source),
        entry(spr_mftb.family, spr_mftb.path, spr_mftb.source),
        entry(spr_mtspr.family, spr_mtspr.path, spr_mtspr.source),
        entry(store_stb.family, store_stb.path, store_stb.source),
        entry(store_stbu.family, store_stbu.path, store_stbu.source),
        entry(store_std.family, store_std.path, store_std.source),
        entry(store_stdu.family, store_stdu.path, store_stdu.source),
        entry(store_sth.family, store_sth.path, store_sth.source),
        entry(store_sthu.family, store_sthu.path, store_sthu.source),
        entry(store_stw.family, store_stw.path, store_stw.source),
        entry(store_stwu.family, store_stwu.path, store_stwu.source),
        entry(store_indexed_stbux.family, store_indexed_stbux.path, store_indexed_stbux.source),
        entry(store_indexed_stbx.family, store_indexed_stbx.path, store_indexed_stbx.source),
        entry(store_indexed_stdux.family, store_indexed_stdux.path, store_indexed_stdux.source),
        entry(store_indexed_stdx.family, store_indexed_stdx.path, store_indexed_stdx.source),
        entry(store_indexed_sthux.family, store_indexed_sthux.path, store_indexed_sthux.source),
        entry(store_indexed_sthx.family, store_indexed_sthx.path, store_indexed_sthx.source),
        entry(store_indexed_stwux.family, store_indexed_stwux.path, store_indexed_stwux.source),
        entry(store_indexed_stwx.family, store_indexed_stwx.path, store_indexed_stwx.source),
        entry(store_multiple_stmw.family, store_multiple_stmw.path, store_multiple_stmw.source),
        entry(store_multiple_stswi.family, store_multiple_stswi.path, store_multiple_stswi.source),
        entry(store_multiple_stswx.family, store_multiple_stswx.path, store_multiple_stswx.source),
        entry(sub_negx.family, sub_negx.path, sub_negx.source),
        entry(sub_subfcx.family, sub_subfcx.path, sub_subfcx.source),
        entry(sub_subfex.family, sub_subfex.path, sub_subfex.source),
        entry(sub_subfmex.family, sub_subfmex.path, sub_subfmex.source),
        entry(sub_subfx.family, sub_subfx.path, sub_subfx.source),
        entry(sub_subfzex.family, sub_subfzex.path, sub_subfzex.source),
        entry(sync_eieio.family, sync_eieio.path, sync_eieio.source),
        entry(sync_isync.family, sync_isync.path, sync_isync.source),
        entry(sync_sync.family, sync_sync.path, sync_sync.source),
        entry(system_mfmsr.family, system_mfmsr.path, system_mfmsr.source),
        entry(system_mtmsr.family, system_mtmsr.path, system_mtmsr.source),
        entry(system_mtmsrd.family, system_mtmsrd.path, system_mtmsrd.source),
        entry(system_sc.family, system_sc.path, system_sc.source),
        entry(system_subficx.family, system_subficx.path, system_subficx.source),
        entry(trap_td.family, trap_td.path, trap_td.source),
        entry(trap_tdi.family, trap_tdi.path, trap_tdi.source),
        entry(trap_tw.family, trap_tw.path, trap_tw.source),
        entry(trap_twi.family, trap_twi.path, trap_twi.source),
        entry(vmx128_lvewx128.family, vmx128_lvewx128.path, vmx128_lvewx128.source),
        entry(vmx128_lvlx128.family, vmx128_lvlx128.path, vmx128_lvlx128.source),
        entry(vmx128_lvlxl128.family, vmx128_lvlxl128.path, vmx128_lvlxl128.source),
        entry(vmx128_lvrx128.family, vmx128_lvrx128.path, vmx128_lvrx128.source),
        entry(vmx128_lvrxl128.family, vmx128_lvrxl128.path, vmx128_lvrxl128.source),
        entry(vmx128_lvsl128.family, vmx128_lvsl128.path, vmx128_lvsl128.source),
        entry(vmx128_lvsr128.family, vmx128_lvsr128.path, vmx128_lvsr128.source),
        entry(vmx128_lvx128.family, vmx128_lvx128.path, vmx128_lvx128.source),
        entry(vmx128_lvxl128.family, vmx128_lvxl128.path, vmx128_lvxl128.source),
        entry(vmx128_stvewx128.family, vmx128_stvewx128.path, vmx128_stvewx128.source),
        entry(vmx128_stvlx128.family, vmx128_stvlx128.path, vmx128_stvlx128.source),
        entry(vmx128_stvlxl128.family, vmx128_stvlxl128.path, vmx128_stvlxl128.source),
        entry(vmx128_stvrx128.family, vmx128_stvrx128.path, vmx128_stvrx128.source),
        entry(vmx128_stvrxl128.family, vmx128_stvrxl128.path, vmx128_stvrxl128.source),
        entry(vmx128_stvx128.family, vmx128_stvx128.path, vmx128_stvx128.source),
        entry(vmx128_stvxl128.family, vmx128_stvxl128.path, vmx128_stvxl128.source),
        entry(vmx128_vaddfp128.family, vmx128_vaddfp128.path, vmx128_vaddfp128.source),
        entry(vmx128_vand128.family, vmx128_vand128.path, vmx128_vand128.source),
        entry(vmx128_vandc128.family, vmx128_vandc128.path, vmx128_vandc128.source),
        entry(vmx128_vcfpsxws128.family, vmx128_vcfpsxws128.path, vmx128_vcfpsxws128.source),
        entry(vmx128_vcfpuxws128.family, vmx128_vcfpuxws128.path, vmx128_vcfpuxws128.source),
        entry(vmx128_vcmpbfp128.family, vmx128_vcmpbfp128.path, vmx128_vcmpbfp128.source),
        entry(vmx128_vcmpeqfp128.family, vmx128_vcmpeqfp128.path, vmx128_vcmpeqfp128.source),
        entry(vmx128_vcmpequw128.family, vmx128_vcmpequw128.path, vmx128_vcmpequw128.source),
        entry(vmx128_vcmpgefp128.family, vmx128_vcmpgefp128.path, vmx128_vcmpgefp128.source),
        entry(vmx128_vcmpgtfp128.family, vmx128_vcmpgtfp128.path, vmx128_vcmpgtfp128.source),
        entry(vmx128_vcsxwfp128.family, vmx128_vcsxwfp128.path, vmx128_vcsxwfp128.source),
        entry(vmx128_vcuxwfp128.family, vmx128_vcuxwfp128.path, vmx128_vcuxwfp128.source),
        entry(vmx128_vexptefp128.family, vmx128_vexptefp128.path, vmx128_vexptefp128.source),
        entry(vmx128_vlogefp128.family, vmx128_vlogefp128.path, vmx128_vlogefp128.source),
        entry(vmx128_vmaddcfp128.family, vmx128_vmaddcfp128.path, vmx128_vmaddcfp128.source),
        entry(vmx128_vmaddfp128.family, vmx128_vmaddfp128.path, vmx128_vmaddfp128.source),
        entry(vmx128_vmaxfp128.family, vmx128_vmaxfp128.path, vmx128_vmaxfp128.source),
        entry(vmx128_vminfp128.family, vmx128_vminfp128.path, vmx128_vminfp128.source),
        entry(vmx128_vmrghw128.family, vmx128_vmrghw128.path, vmx128_vmrghw128.source),
        entry(vmx128_vmrglw128.family, vmx128_vmrglw128.path, vmx128_vmrglw128.source),
        entry(vmx128_vmsum3fp128.family, vmx128_vmsum3fp128.path, vmx128_vmsum3fp128.source),
        entry(vmx128_vmsum4fp128.family, vmx128_vmsum4fp128.path, vmx128_vmsum4fp128.source),
        entry(vmx128_vmulfp128.family, vmx128_vmulfp128.path, vmx128_vmulfp128.source),
        entry(vmx128_vnmsubfp128.family, vmx128_vnmsubfp128.path, vmx128_vnmsubfp128.source),
        entry(vmx128_vnor128.family, vmx128_vnor128.path, vmx128_vnor128.source),
        entry(vmx128_vor128.family, vmx128_vor128.path, vmx128_vor128.source),
        entry(vmx128_vperm128.family, vmx128_vperm128.path, vmx128_vperm128.source),
        entry(vmx128_vpermwi128.family, vmx128_vpermwi128.path, vmx128_vpermwi128.source),
        entry(vmx128_vpkd3d128.family, vmx128_vpkd3d128.path, vmx128_vpkd3d128.source),
        entry(vmx128_vpkshss128.family, vmx128_vpkshss128.path, vmx128_vpkshss128.source),
        entry(vmx128_vpkshus128.family, vmx128_vpkshus128.path, vmx128_vpkshus128.source),
        entry(vmx128_vpkswss128.family, vmx128_vpkswss128.path, vmx128_vpkswss128.source),
        entry(vmx128_vpkswus128.family, vmx128_vpkswus128.path, vmx128_vpkswus128.source),
        entry(vmx128_vpkuhum128.family, vmx128_vpkuhum128.path, vmx128_vpkuhum128.source),
        entry(vmx128_vpkuhus128.family, vmx128_vpkuhus128.path, vmx128_vpkuhus128.source),
        entry(vmx128_vpkuwum128.family, vmx128_vpkuwum128.path, vmx128_vpkuwum128.source),
        entry(vmx128_vpkuwus128.family, vmx128_vpkuwus128.path, vmx128_vpkuwus128.source),
        entry(vmx128_vrefp128.family, vmx128_vrefp128.path, vmx128_vrefp128.source),
        entry(vmx128_vrfim128.family, vmx128_vrfim128.path, vmx128_vrfim128.source),
        entry(vmx128_vrfin128.family, vmx128_vrfin128.path, vmx128_vrfin128.source),
        entry(vmx128_vrfip128.family, vmx128_vrfip128.path, vmx128_vrfip128.source),
        entry(vmx128_vrfiz128.family, vmx128_vrfiz128.path, vmx128_vrfiz128.source),
        entry(vmx128_vrlimi128.family, vmx128_vrlimi128.path, vmx128_vrlimi128.source),
        entry(vmx128_vrlw128.family, vmx128_vrlw128.path, vmx128_vrlw128.source),
        entry(vmx128_vrsqrtefp128.family, vmx128_vrsqrtefp128.path, vmx128_vrsqrtefp128.source),
        entry(vmx128_vsel128.family, vmx128_vsel128.path, vmx128_vsel128.source),
        entry(vmx128_vsldoi128.family, vmx128_vsldoi128.path, vmx128_vsldoi128.source),
        entry(vmx128_vslo128.family, vmx128_vslo128.path, vmx128_vslo128.source),
        entry(vmx128_vslw128.family, vmx128_vslw128.path, vmx128_vslw128.source),
        entry(vmx128_vspltisw128.family, vmx128_vspltisw128.path, vmx128_vspltisw128.source),
        entry(vmx128_vspltw128.family, vmx128_vspltw128.path, vmx128_vspltw128.source),
        entry(vmx128_vsraw128.family, vmx128_vsraw128.path, vmx128_vsraw128.source),
        entry(vmx128_vsro128.family, vmx128_vsro128.path, vmx128_vsro128.source),
        entry(vmx128_vsrw128.family, vmx128_vsrw128.path, vmx128_vsrw128.source),
        entry(vmx128_vsubfp128.family, vmx128_vsubfp128.path, vmx128_vsubfp128.source),
        entry(vmx128_vupkd3d128.family, vmx128_vupkd3d128.path, vmx128_vupkd3d128.source),
        entry(vmx128_vupkhsb128.family, vmx128_vupkhsb128.path, vmx128_vupkhsb128.source),
        entry(vmx128_vupklsb128.family, vmx128_vupklsb128.path, vmx128_vupklsb128.source),
        entry(vmx128_vxor128.family, vmx128_vxor128.path, vmx128_vxor128.source),
        entry(vmx_arith_vaddcuw.family, vmx_arith_vaddcuw.path, vmx_arith_vaddcuw.source),
        entry(vmx_arith_vaddfp.family, vmx_arith_vaddfp.path, vmx_arith_vaddfp.source),
        entry(vmx_arith_vaddsbs.family, vmx_arith_vaddsbs.path, vmx_arith_vaddsbs.source),
        entry(vmx_arith_vaddshs.family, vmx_arith_vaddshs.path, vmx_arith_vaddshs.source),
        entry(vmx_arith_vaddsws.family, vmx_arith_vaddsws.path, vmx_arith_vaddsws.source),
        entry(vmx_arith_vaddubm.family, vmx_arith_vaddubm.path, vmx_arith_vaddubm.source),
        entry(vmx_arith_vaddubs.family, vmx_arith_vaddubs.path, vmx_arith_vaddubs.source),
        entry(vmx_arith_vadduhm.family, vmx_arith_vadduhm.path, vmx_arith_vadduhm.source),
        entry(vmx_arith_vadduhs.family, vmx_arith_vadduhs.path, vmx_arith_vadduhs.source),
        entry(vmx_arith_vadduwm.family, vmx_arith_vadduwm.path, vmx_arith_vadduwm.source),
        entry(vmx_arith_vadduws.family, vmx_arith_vadduws.path, vmx_arith_vadduws.source),
        entry(vmx_arith_vavgsb.family, vmx_arith_vavgsb.path, vmx_arith_vavgsb.source),
        entry(vmx_arith_vavgsh.family, vmx_arith_vavgsh.path, vmx_arith_vavgsh.source),
        entry(vmx_arith_vavgsw.family, vmx_arith_vavgsw.path, vmx_arith_vavgsw.source),
        entry(vmx_arith_vavgub.family, vmx_arith_vavgub.path, vmx_arith_vavgub.source),
        entry(vmx_arith_vavguh.family, vmx_arith_vavguh.path, vmx_arith_vavguh.source),
        entry(vmx_arith_vavguw.family, vmx_arith_vavguw.path, vmx_arith_vavguw.source),
        entry(vmx_arith_vmaxfp.family, vmx_arith_vmaxfp.path, vmx_arith_vmaxfp.source),
        entry(vmx_arith_vmaxsb.family, vmx_arith_vmaxsb.path, vmx_arith_vmaxsb.source),
        entry(vmx_arith_vmaxsh.family, vmx_arith_vmaxsh.path, vmx_arith_vmaxsh.source),
        entry(vmx_arith_vmaxsw.family, vmx_arith_vmaxsw.path, vmx_arith_vmaxsw.source),
        entry(vmx_arith_vmaxub.family, vmx_arith_vmaxub.path, vmx_arith_vmaxub.source),
        entry(vmx_arith_vmaxuh.family, vmx_arith_vmaxuh.path, vmx_arith_vmaxuh.source),
        entry(vmx_arith_vmaxuw.family, vmx_arith_vmaxuw.path, vmx_arith_vmaxuw.source),
        entry(vmx_arith_vminfp.family, vmx_arith_vminfp.path, vmx_arith_vminfp.source),
        entry(vmx_arith_vminsb.family, vmx_arith_vminsb.path, vmx_arith_vminsb.source),
        entry(vmx_arith_vminsh.family, vmx_arith_vminsh.path, vmx_arith_vminsh.source),
        entry(vmx_arith_vminsw.family, vmx_arith_vminsw.path, vmx_arith_vminsw.source),
        entry(vmx_arith_vminub.family, vmx_arith_vminub.path, vmx_arith_vminub.source),
        entry(vmx_arith_vminuh.family, vmx_arith_vminuh.path, vmx_arith_vminuh.source),
        entry(vmx_arith_vminuw.family, vmx_arith_vminuw.path, vmx_arith_vminuw.source),
        entry(vmx_arith_vmulesb.family, vmx_arith_vmulesb.path, vmx_arith_vmulesb.source),
        entry(vmx_arith_vmulesh.family, vmx_arith_vmulesh.path, vmx_arith_vmulesh.source),
        entry(vmx_arith_vmuleub.family, vmx_arith_vmuleub.path, vmx_arith_vmuleub.source),
        entry(vmx_arith_vmuleuh.family, vmx_arith_vmuleuh.path, vmx_arith_vmuleuh.source),
        entry(vmx_arith_vmulosb.family, vmx_arith_vmulosb.path, vmx_arith_vmulosb.source),
        entry(vmx_arith_vmulosh.family, vmx_arith_vmulosh.path, vmx_arith_vmulosh.source),
        entry(vmx_arith_vmuloub.family, vmx_arith_vmuloub.path, vmx_arith_vmuloub.source),
        entry(vmx_arith_vmulouh.family, vmx_arith_vmulouh.path, vmx_arith_vmulouh.source),
        entry(vmx_arith_vsubcuw.family, vmx_arith_vsubcuw.path, vmx_arith_vsubcuw.source),
        entry(vmx_arith_vsubfp.family, vmx_arith_vsubfp.path, vmx_arith_vsubfp.source),
        entry(vmx_arith_vsubsbs.family, vmx_arith_vsubsbs.path, vmx_arith_vsubsbs.source),
        entry(vmx_arith_vsubshs.family, vmx_arith_vsubshs.path, vmx_arith_vsubshs.source),
        entry(vmx_arith_vsubsws.family, vmx_arith_vsubsws.path, vmx_arith_vsubsws.source),
        entry(vmx_arith_vsububm.family, vmx_arith_vsububm.path, vmx_arith_vsububm.source),
        entry(vmx_arith_vsububs.family, vmx_arith_vsububs.path, vmx_arith_vsububs.source),
        entry(vmx_arith_vsubuhm.family, vmx_arith_vsubuhm.path, vmx_arith_vsubuhm.source),
        entry(vmx_arith_vsubuhs.family, vmx_arith_vsubuhs.path, vmx_arith_vsubuhs.source),
        entry(vmx_arith_vsubuwm.family, vmx_arith_vsubuwm.path, vmx_arith_vsubuwm.source),
        entry(vmx_arith_vsubuws.family, vmx_arith_vsubuws.path, vmx_arith_vsubuws.source),
        entry(vmx_compare_vcmpbfp.family, vmx_compare_vcmpbfp.path, vmx_compare_vcmpbfp.source),
        entry(vmx_compare_vcmpeqfp.family, vmx_compare_vcmpeqfp.path, vmx_compare_vcmpeqfp.source),
        entry(vmx_compare_vcmpequb.family, vmx_compare_vcmpequb.path, vmx_compare_vcmpequb.source),
        entry(vmx_compare_vcmpequh.family, vmx_compare_vcmpequh.path, vmx_compare_vcmpequh.source),
        entry(vmx_compare_vcmpequw.family, vmx_compare_vcmpequw.path, vmx_compare_vcmpequw.source),
        entry(vmx_compare_vcmpgefp.family, vmx_compare_vcmpgefp.path, vmx_compare_vcmpgefp.source),
        entry(vmx_compare_vcmpgtfp.family, vmx_compare_vcmpgtfp.path, vmx_compare_vcmpgtfp.source),
        entry(vmx_compare_vcmpgtsb.family, vmx_compare_vcmpgtsb.path, vmx_compare_vcmpgtsb.source),
        entry(vmx_compare_vcmpgtsh.family, vmx_compare_vcmpgtsh.path, vmx_compare_vcmpgtsh.source),
        entry(vmx_compare_vcmpgtsw.family, vmx_compare_vcmpgtsw.path, vmx_compare_vcmpgtsw.source),
        entry(vmx_compare_vcmpgtub.family, vmx_compare_vcmpgtub.path, vmx_compare_vcmpgtub.source),
        entry(vmx_compare_vcmpgtuh.family, vmx_compare_vcmpgtuh.path, vmx_compare_vcmpgtuh.source),
        entry(vmx_compare_vcmpgtuw.family, vmx_compare_vcmpgtuw.path, vmx_compare_vcmpgtuw.source),
        entry(vmx_convert_vcfsx.family, vmx_convert_vcfsx.path, vmx_convert_vcfsx.source),
        entry(vmx_convert_vcfux.family, vmx_convert_vcfux.path, vmx_convert_vcfux.source),
        entry(vmx_convert_vctsxs.family, vmx_convert_vctsxs.path, vmx_convert_vctsxs.source),
        entry(vmx_convert_vctuxs.family, vmx_convert_vctuxs.path, vmx_convert_vctuxs.source),
        entry(vmx_convert_vrfim.family, vmx_convert_vrfim.path, vmx_convert_vrfim.source),
        entry(vmx_convert_vrfin.family, vmx_convert_vrfin.path, vmx_convert_vrfin.source),
        entry(vmx_convert_vrfip.family, vmx_convert_vrfip.path, vmx_convert_vrfip.source),
        entry(vmx_convert_vrfiz.family, vmx_convert_vrfiz.path, vmx_convert_vrfiz.source),
        entry(vmx_estimate_vexptefp.family, vmx_estimate_vexptefp.path, vmx_estimate_vexptefp.source),
        entry(vmx_estimate_vlogefp.family, vmx_estimate_vlogefp.path, vmx_estimate_vlogefp.source),
        entry(vmx_estimate_vrefp.family, vmx_estimate_vrefp.path, vmx_estimate_vrefp.source),
        entry(vmx_estimate_vrsqrtefp.family, vmx_estimate_vrsqrtefp.path, vmx_estimate_vrsqrtefp.source),
        entry(vmx_load_lvebx.family, vmx_load_lvebx.path, vmx_load_lvebx.source),
        entry(vmx_load_lvehx.family, vmx_load_lvehx.path, vmx_load_lvehx.source),
        entry(vmx_load_lvewx.family, vmx_load_lvewx.path, vmx_load_lvewx.source),
        entry(vmx_load_lvlx.family, vmx_load_lvlx.path, vmx_load_lvlx.source),
        entry(vmx_load_lvlxl.family, vmx_load_lvlxl.path, vmx_load_lvlxl.source),
        entry(vmx_load_lvrx.family, vmx_load_lvrx.path, vmx_load_lvrx.source),
        entry(vmx_load_lvrxl.family, vmx_load_lvrxl.path, vmx_load_lvrxl.source),
        entry(vmx_load_lvsl.family, vmx_load_lvsl.path, vmx_load_lvsl.source),
        entry(vmx_load_lvsr.family, vmx_load_lvsr.path, vmx_load_lvsr.source),
        entry(vmx_load_lvx.family, vmx_load_lvx.path, vmx_load_lvx.source),
        entry(vmx_load_lvxl.family, vmx_load_lvxl.path, vmx_load_lvxl.source),
        entry(vmx_logical_vand.family, vmx_logical_vand.path, vmx_logical_vand.source),
        entry(vmx_logical_vandc.family, vmx_logical_vandc.path, vmx_logical_vandc.source),
        entry(vmx_logical_vnor.family, vmx_logical_vnor.path, vmx_logical_vnor.source),
        entry(vmx_logical_vor.family, vmx_logical_vor.path, vmx_logical_vor.source),
        entry(vmx_logical_vxor.family, vmx_logical_vxor.path, vmx_logical_vxor.source),
        entry(vmx_multiply_add_vmaddfp.family, vmx_multiply_add_vmaddfp.path, vmx_multiply_add_vmaddfp.source),
        entry(vmx_multiply_add_vmhaddshs.family, vmx_multiply_add_vmhaddshs.path, vmx_multiply_add_vmhaddshs.source),
        entry(vmx_multiply_add_vmhraddshs.family, vmx_multiply_add_vmhraddshs.path, vmx_multiply_add_vmhraddshs.source),
        entry(vmx_multiply_add_vmladduhm.family, vmx_multiply_add_vmladduhm.path, vmx_multiply_add_vmladduhm.source),
        entry(vmx_multiply_add_vmsummbm.family, vmx_multiply_add_vmsummbm.path, vmx_multiply_add_vmsummbm.source),
        entry(vmx_multiply_add_vmsumshm.family, vmx_multiply_add_vmsumshm.path, vmx_multiply_add_vmsumshm.source),
        entry(vmx_multiply_add_vmsumshs.family, vmx_multiply_add_vmsumshs.path, vmx_multiply_add_vmsumshs.source),
        entry(vmx_multiply_add_vmsumubm.family, vmx_multiply_add_vmsumubm.path, vmx_multiply_add_vmsumubm.source),
        entry(vmx_multiply_add_vmsumuhm.family, vmx_multiply_add_vmsumuhm.path, vmx_multiply_add_vmsumuhm.source),
        entry(vmx_multiply_add_vmsumuhs.family, vmx_multiply_add_vmsumuhs.path, vmx_multiply_add_vmsumuhs.source),
        entry(vmx_multiply_add_vnmsubfp.family, vmx_multiply_add_vnmsubfp.path, vmx_multiply_add_vnmsubfp.source),
        entry(vmx_multiply_add_vsum2sws.family, vmx_multiply_add_vsum2sws.path, vmx_multiply_add_vsum2sws.source),
        entry(vmx_multiply_add_vsum4sbs.family, vmx_multiply_add_vsum4sbs.path, vmx_multiply_add_vsum4sbs.source),
        entry(vmx_multiply_add_vsum4shs.family, vmx_multiply_add_vsum4shs.path, vmx_multiply_add_vsum4shs.source),
        entry(vmx_multiply_add_vsum4ubs.family, vmx_multiply_add_vsum4ubs.path, vmx_multiply_add_vsum4ubs.source),
        entry(vmx_multiply_add_vsumsws.family, vmx_multiply_add_vsumsws.path, vmx_multiply_add_vsumsws.source),
        entry(vmx_pack_vpkpx.family, vmx_pack_vpkpx.path, vmx_pack_vpkpx.source),
        entry(vmx_pack_vpkshss.family, vmx_pack_vpkshss.path, vmx_pack_vpkshss.source),
        entry(vmx_pack_vpkshus.family, vmx_pack_vpkshus.path, vmx_pack_vpkshus.source),
        entry(vmx_pack_vpkswss.family, vmx_pack_vpkswss.path, vmx_pack_vpkswss.source),
        entry(vmx_pack_vpkswus.family, vmx_pack_vpkswus.path, vmx_pack_vpkswus.source),
        entry(vmx_pack_vpkuhum.family, vmx_pack_vpkuhum.path, vmx_pack_vpkuhum.source),
        entry(vmx_pack_vpkuhus.family, vmx_pack_vpkuhus.path, vmx_pack_vpkuhus.source),
        entry(vmx_pack_vpkuwum.family, vmx_pack_vpkuwum.path, vmx_pack_vpkuwum.source),
        entry(vmx_pack_vpkuwus.family, vmx_pack_vpkuwus.path, vmx_pack_vpkuwus.source),
        entry(vmx_pack_vupkhpx.family, vmx_pack_vupkhpx.path, vmx_pack_vupkhpx.source),
        entry(vmx_pack_vupkhsb.family, vmx_pack_vupkhsb.path, vmx_pack_vupkhsb.source),
        entry(vmx_pack_vupkhsh.family, vmx_pack_vupkhsh.path, vmx_pack_vupkhsh.source),
        entry(vmx_pack_vupklpx.family, vmx_pack_vupklpx.path, vmx_pack_vupklpx.source),
        entry(vmx_pack_vupklsb.family, vmx_pack_vupklsb.path, vmx_pack_vupklsb.source),
        entry(vmx_pack_vupklsh.family, vmx_pack_vupklsh.path, vmx_pack_vupklsh.source),
        entry(vmx_permute_vmrghb.family, vmx_permute_vmrghb.path, vmx_permute_vmrghb.source),
        entry(vmx_permute_vmrghh.family, vmx_permute_vmrghh.path, vmx_permute_vmrghh.source),
        entry(vmx_permute_vmrghw.family, vmx_permute_vmrghw.path, vmx_permute_vmrghw.source),
        entry(vmx_permute_vmrglb.family, vmx_permute_vmrglb.path, vmx_permute_vmrglb.source),
        entry(vmx_permute_vmrglh.family, vmx_permute_vmrglh.path, vmx_permute_vmrglh.source),
        entry(vmx_permute_vmrglw.family, vmx_permute_vmrglw.path, vmx_permute_vmrglw.source),
        entry(vmx_permute_vperm.family, vmx_permute_vperm.path, vmx_permute_vperm.source),
        entry(vmx_permute_vsel.family, vmx_permute_vsel.path, vmx_permute_vsel.source),
        entry(vmx_permute_vsldoi.family, vmx_permute_vsldoi.path, vmx_permute_vsldoi.source),
        entry(vmx_shift_vrlb.family, vmx_shift_vrlb.path, vmx_shift_vrlb.source),
        entry(vmx_shift_vrlh.family, vmx_shift_vrlh.path, vmx_shift_vrlh.source),
        entry(vmx_shift_vrlw.family, vmx_shift_vrlw.path, vmx_shift_vrlw.source),
        entry(vmx_shift_vsl.family, vmx_shift_vsl.path, vmx_shift_vsl.source),
        entry(vmx_shift_vslb.family, vmx_shift_vslb.path, vmx_shift_vslb.source),
        entry(vmx_shift_vslh.family, vmx_shift_vslh.path, vmx_shift_vslh.source),
        entry(vmx_shift_vslo.family, vmx_shift_vslo.path, vmx_shift_vslo.source),
        entry(vmx_shift_vslw.family, vmx_shift_vslw.path, vmx_shift_vslw.source),
        entry(vmx_shift_vsr.family, vmx_shift_vsr.path, vmx_shift_vsr.source),
        entry(vmx_shift_vsrab.family, vmx_shift_vsrab.path, vmx_shift_vsrab.source),
        entry(vmx_shift_vsrah.family, vmx_shift_vsrah.path, vmx_shift_vsrah.source),
        entry(vmx_shift_vsraw.family, vmx_shift_vsraw.path, vmx_shift_vsraw.source),
        entry(vmx_shift_vsrb.family, vmx_shift_vsrb.path, vmx_shift_vsrb.source),
        entry(vmx_shift_vsrh.family, vmx_shift_vsrh.path, vmx_shift_vsrh.source),
        entry(vmx_shift_vsro.family, vmx_shift_vsro.path, vmx_shift_vsro.source),
        entry(vmx_shift_vsrw.family, vmx_shift_vsrw.path, vmx_shift_vsrw.source),
        entry(vmx_splat_vspltb.family, vmx_splat_vspltb.path, vmx_splat_vspltb.source),
        entry(vmx_splat_vsplth.family, vmx_splat_vsplth.path, vmx_splat_vsplth.source),
        entry(vmx_splat_vspltisb.family, vmx_splat_vspltisb.path, vmx_splat_vspltisb.source),
        entry(vmx_splat_vspltish.family, vmx_splat_vspltish.path, vmx_splat_vspltish.source),
        entry(vmx_splat_vspltisw.family, vmx_splat_vspltisw.path, vmx_splat_vspltisw.source),
        entry(vmx_splat_vspltw.family, vmx_splat_vspltw.path, vmx_splat_vspltw.source),
        entry(vmx_status_mfvscr.family, vmx_status_mfvscr.path, vmx_status_mfvscr.source),
        entry(vmx_status_mtvscr.family, vmx_status_mtvscr.path, vmx_status_mtvscr.source),
        entry(vmx_store_stvebx.family, vmx_store_stvebx.path, vmx_store_stvebx.source),
        entry(vmx_store_stvehx.family, vmx_store_stvehx.path, vmx_store_stvehx.source),
        entry(vmx_store_stvewx.family, vmx_store_stvewx.path, vmx_store_stvewx.source),
        entry(vmx_store_stvlx.family, vmx_store_stvlx.path, vmx_store_stvlx.source),
        entry(vmx_store_stvlxl.family, vmx_store_stvlxl.path, vmx_store_stvlxl.source),
        entry(vmx_store_stvrx.family, vmx_store_stvrx.path, vmx_store_stvrx.source),
        entry(vmx_store_stvrxl.family, vmx_store_stvrxl.path, vmx_store_stvrxl.source),
        entry(vmx_store_stvx.family, vmx_store_stvx.path, vmx_store_stvx.source),
        entry(vmx_store_stvxl.family, vmx_store_stvxl.path, vmx_store_stvxl.source),
    };
};

pub fn tableCount() usize {
    return tables.len;
}

pub fn findByName(name: []const u8) ?InstructionTable {
    for (tables) |table| {
        if (std.mem.eql(u8, table.metadata().name, name)) return table;
    }
    return null;
}

pub fn findByPath(path: []const u8) ?InstructionTable {
    for (tables) |table| {
        if (std.mem.eql(u8, table.path, path)) return table;
    }
    return null;
}

pub fn validateAll() void {
    for (tables) |table| table.validate();
}

fn entry(family: []const u8, path: []const u8, source: []const u8) InstructionTable {
    return .{ .family = family, .path = path, .source = source };
}

fn stripLineComment(line: []const u8) []const u8 {
    if (std.mem.indexOf(u8, line, "//")) |idx| return line[0..idx];
    return line;
}

fn assignmentName(line: []const u8) ?[]const u8 {
    const eq = std.mem.indexOfScalar(u8, line, '=') orelse return null;
    const name = std.mem.trim(u8, line[0..eq], " \t");
    if (name.len == 0) return null;
    for (name) |ch| {
        const ok = (ch >= 'a' and ch <= 'z') or (ch >= 'A' and ch <= 'Z') or
            (ch >= '0' and ch <= '9') or ch == '_';
        if (!ok) return null;
    }
    return name;
}

fn stringAssignment(source: []const u8, key: []const u8) ?[]const u8 {
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, stripLineComment(raw_line), " \t\r");
        const name = assignmentName(line) orelse continue;
        if (!std.mem.eql(u8, name, key)) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const value = std.mem.trim(u8, line[eq + 1 ..], " \t");
        if (value.len < 2 or value[0] != '"') continue;
        const end = std.mem.indexOfScalar(u8, value[1..], '"') orelse continue;
        return value[1 .. 1 + end];
    }
    return null;
}

fn anyStringAssignment(source: []const u8, keys: []const []const u8) ?[]const u8 {
    for (keys) |key| if (stringAssignment(source, key)) |value| return value;
    return null;
}

fn numberAssignment(source: []const u8, key: []const u8) ?u8 {
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, stripLineComment(raw_line), " \t\r");
        const name = assignmentName(line) orelse continue;
        if (!std.mem.eql(u8, name, key)) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const value = std.mem.trim(u8, line[eq + 1 ..], " \t");
        return std.fmt.parseInt(u8, value, 10) catch null;
    }
    return null;
}

fn hasAssignment(source: []const u8, key: []const u8) bool {
    var lines = std.mem.splitScalar(u8, source, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, stripLineComment(raw_line), " \t\r");
        const name = assignmentName(line) orelse continue;
        if (std.mem.eql(u8, name, key)) return true;
    }
    return false;
}

fn hasAnyAssignment(source: []const u8, keys: []const []const u8) bool {
    for (keys) |key| if (hasAssignment(source, key)) return true;
    return false;
}

fn blockAssignment(source: []const u8, key: []const u8) ?[]const u8 {
    const start = std.mem.indexOf(u8, source, key) orelse return null;
    const open_rel = std.mem.indexOf(u8, source[start..], "\"\"\"") orelse return null;
    const body_start = start + open_rel + 3;
    const close_rel = std.mem.indexOf(u8, source[body_start..], "\"\"\"") orelse return null;
    return std.mem.trim(u8, source[body_start .. body_start + close_rel], " \t\r\n");
}

fn countEncodingRows(source: []const u8) usize {
    var lines = std.mem.splitScalar(u8, source, '\n');
    var in_block = false;
    var count: usize = 0;
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, stripLineComment(raw_line), " \t\r");
        if (!in_block) {
            const name = assignmentName(line) orelse continue;
            if (!std.mem.eql(u8, name, "encodings")) continue;
            const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
            const rhs = std.mem.trim(u8, line[eq + 1 ..], " \t");
            if (rhs.len == 0 or rhs[0] != '[') continue;
            in_block = true;
            continue;
        }
        if (std.mem.startsWith(u8, line, "{")) {
            count += 1;
            continue;
        }
        if (line.len >= 1 and line[0] == ']') break;
    }
    return count;
}

fn mnemonicFromPath(path: []const u8) []const u8 {
    const slash = std.mem.lastIndexOfScalar(u8, path, '/') orelse 0;
    const start = if (path[slash] == '/') slash + 1 else slash;
    const dot = std.mem.lastIndexOfScalar(u8, path, '.') orelse path.len;
    return path[start..dot];
}

test "PPC ISA tables expose required metadata" {
    try std.testing.expectEqual(@as(usize, 455), tableCount());
    runtime_abi.isa.init();
    defer runtime_abi.isa.deinit();
    validateAll();
    const add = (findByName("addx") orelse return error.MissingAdd).metadata();
    try std.testing.expectEqualStrings("ppc_addx", add.handler);
    try std.testing.expectEqualStrings("add", add.mnemonic);
    try std.testing.expectEqual(@as(u8, 31), add.primary_opcode);
    try std.testing.expect(add.encoding_count >= 1);
}

test "every PPC table names a real primary opcode and a handler" {
    for (tables) |table| {
        const meta = table.metadata();
        try std.testing.expect(meta.primary_opcode <= 63);
        try std.testing.expect(meta.handler.len > 0);
        try std.testing.expect(meta.encoding_count >= 1);
        try std.testing.expect(meta.has_semantic);
    }
}
