const std = @import("std");
const types = @import("types.zig");
pub const AVX = @import("AVX/root.zig");
pub const AVX2 = @import("AVX2/root.zig");
// GATHER and SCATTER now live in AVX512F/root.zig
pub const AVX512F = @import("AVX512F/root.zig");
pub const AVX512DQ = @import("AVX512DQ/root.zig");
pub const AVX512BW = @import("AVX512BW/root.zig");
pub const AVX512BF16 = @import("AVX512BF16/root.zig");
pub const VAES = @import("VAES/root.zig");
pub const GFNI = @import("GFNI/root.zig");
pub const SHA = @import("SHA/root.zig");
pub const SYSTEM = @import("SYSTEM/root.zig");

pub const metas = [_]types.InstructionMeta{
    AVX.ADDPD.meta,
    AVX.ADDPS.meta,
    AVX.ADDSUBPD.meta,
    AVX.ADDSUBPS.meta,
    AVX.ANDNPD.meta,
    AVX.ANDNPS.meta,
    AVX.ANDPD.meta,
    AVX.ANDPS.meta,
    AVX.BLENDPD.meta,
    AVX.BLENDPS.meta,
    AVX.BLENDVPD.meta,
    AVX.BLENDVPS.meta,
    AVX.CMPPD.meta,
    AVX.CMPPS.meta,
    AVX.DIVPD.meta,
    AVX.DIVPS.meta,
    AVX.DPPS.meta,
    AVX.LDDQU.meta,
    AVX.MOVAPD.meta,
    AVX.MOVAPS.meta,
    AVX.MOVDDUP.meta,
    AVX.MOVMSKPD.meta,
    AVX.MOVMSKPS.meta,
    AVX.MULPD.meta,
    AVX.MULPS.meta,
    AVX.MOVNTPD.meta,
    AVX.MOVNTPS.meta,
    AVX.MOVSHDUP.meta,
    AVX.MOVSLDUP.meta,
    AVX.MOVUPD.meta,
    AVX.MOVUPS.meta,
    AVX.ORPD.meta,
    AVX.ORPS.meta,
    AVX.SQRTPD.meta,
    AVX.SQRTPS.meta,
    AVX.SUBPD.meta,
    AVX.SUBPS.meta,
    AVX.VMOVAPD.meta,
    AVX.VMOVAPS.meta,
    AVX.VMOVDDUP.meta,
    AVX.VMOVMSKPD.meta,
    AVX.VMOVMSKPS.meta,
    AVX.VMOVNTPD.meta,
    AVX.VMOVNTPS.meta,
    AVX.VMOVSHDUP.meta,
    AVX.VMOVSLDUP.meta,
    AVX.VMOVUPD.meta,
    AVX.VMOVUPS.meta,
    AVX.SHUFPD.meta,
    AVX.SHUFPS.meta,
    AVX.XORPD.meta,
    AVX.XORPS.meta,
    AVX.VFMADD132PD.meta,
    AVX.VFMADD132PS.meta,
    AVX.VFMADD213PD.meta,
    AVX.VFMADD213PS.meta,
    AVX.VFMADD231PD.meta,
    AVX.VFMADD231PS.meta,
    AVX.VFMSUB132PD.meta,
    AVX.VFMSUB132PS.meta,
    AVX.VFMSUB213PD.meta,
    AVX.VFMSUB213PS.meta,
    AVX.VFMSUB231PD.meta,
    AVX.VFMSUB231PS.meta,
    AVX.VFNMADD132PD.meta,
    AVX.VFNMADD132PS.meta,
    AVX.VFNMADD213PD.meta,
    AVX.VFNMADD213PS.meta,
    AVX.VFNMADD231PD.meta,
    AVX.VFNMADD231PS.meta,
    AVX.VFNMSUB132PD.meta,
    AVX.VFNMSUB132PS.meta,
    AVX.VFNMSUB213PD.meta,
    AVX.VFNMSUB213PS.meta,
    AVX.VFNMSUB231PD.meta,
    AVX.VFNMSUB231PS.meta,
    AVX.VFMADDSUB132PD.meta,
    AVX.VFMADDSUB132PS.meta,
    AVX.VFMADDSUB213PD.meta,
    AVX.VFMADDSUB213PS.meta,
    AVX.VFMADDSUB231PD.meta,
    AVX.VFMADDSUB231PS.meta,
    AVX.VFMSUBADD132PD.meta,
    AVX.VFMSUBADD132PS.meta,
    AVX.VFMSUBADD213PD.meta,
    AVX.VFMSUBADD213PS.meta,
    AVX.VFMSUBADD231PD.meta,
    AVX.VFMSUBADD231PS.meta,
    AVX.VFMADDRND231PD.meta,
    AVX2.MOVDQA.meta,
    AVX2.MOVDQU.meta,
    AVX2.MOVNTDQ.meta,
    AVX2.MOVNTDQA.meta,
    AVX2.PMAXSB.meta,
    AVX2.PMAXSD.meta,
    AVX2.PMAXSW.meta,
    AVX2.PMAXUB.meta,
    AVX2.PMAXUD.meta,
    AVX2.PMAXUW.meta,
    AVX2.PMINSB.meta,
    AVX2.PMINSD.meta,
    AVX2.PMINSW.meta,
    AVX2.PMINUB.meta,
    AVX2.PMINUD.meta,
    AVX2.PMINUW.meta,
    AVX2.VMOVDQA.meta,
    AVX2.VMOVDQU.meta,
    AVX2.VMOVNTDQ.meta,
    AVX2.VMOVNTDQA.meta,
    AVX2.VPADDB.meta,
    AVX2.VPADDW.meta,
    AVX2.VPADDD.meta,
    AVX2.VPADDQ.meta,
    AVX2.VPSUBB.meta,
    AVX2.VPSUBW.meta,
    AVX2.VPSUBD.meta,
    AVX2.VPSUBQ.meta,
    AVX2.VPCMPEQB.meta,
    AVX2.VPCMPEQW.meta,
    AVX2.VPCMPEQD.meta,
    AVX2.VPCMPEQQ.meta,
    AVX2.VPCMPGTB.meta,
    AVX2.VPCMPGTW.meta,
    AVX2.VPCMPGTD.meta,
    AVX2.VPCMPGTQ.meta,
    AVX2.VPMULLW.meta,
    AVX2.VPMULLD.meta,
    AVX2.VPOR.meta,
    AVX2.VPSUBSB.meta,
    AVX2.VPSUBSW.meta,
    AVX2.VPSUBUSB.meta,
    AVX2.VPSUBUSW.meta,
    AVX512F.ADDPD.meta,
    AVX512F.ADDPS.meta,
    AVX512F.CMPPD.meta,
    AVX512F.CMPPS.meta,
    AVX512F.DIVPD.meta,
    AVX512F.DIVPS.meta,
    AVX512F.MULPD.meta,
    AVX512F.MULPS.meta,
    AVX512F.PMAXSD.meta,
    AVX512F.PMAXSQ.meta,
    AVX512F.PMAXUD.meta,
    AVX512F.PMAXUQ.meta,
    AVX512F.PMINSD.meta,
    AVX512F.PMINSQ.meta,
    AVX512F.PMINUD.meta,
    AVX512F.PMINUQ.meta,
    AVX512F.SHUFPD.meta,
    AVX512F.SHUFPS.meta,
    AVX512F.SQRTPD.meta,
    AVX512F.SQRTPS.meta,
    AVX512F.VMOVDQA32.meta,
    AVX512F.VMOVDQA64.meta,
    AVX512F.VMOVDQU32.meta,
    AVX512F.VMOVDQU64.meta,
    AVX512F.VPORD.meta,
    AVX512F.VPORQ.meta,
    AVX512F.SUBPD.meta,
    AVX512F.SUBPS.meta,
    AVX512F.VPADDD.meta,
    AVX512F.VPADDQ.meta,
    AVX512F.VPSUBD.meta,
    AVX512F.VPSUBQ.meta,
    AVX512F.VPCMPEQD.meta,
    AVX512F.VPCMPEQQ.meta,
    AVX512F.VPCMPGTD.meta,
    AVX512F.VPCMPGTQ.meta,
    AVX512F.VPMULLD.meta,
    AVX512F.VFMADD132PD.meta,
    AVX512F.VFMADD132PS.meta,
    AVX512F.VFMADD213PD.meta,
    AVX512F.VFMADD213PS.meta,
    AVX512F.VFMADD231PD.meta,
    AVX512F.VFMADD231PS.meta,
    AVX512F.VFMSUB132PD.meta,
    AVX512F.VFMSUB132PS.meta,
    AVX512F.VFMSUB213PD.meta,
    AVX512F.VFMSUB213PS.meta,
    AVX512F.VFMSUB231PD.meta,
    AVX512F.VFMSUB231PS.meta,
    AVX512F.VFNMADD132PD.meta,
    AVX512F.VFNMADD132PS.meta,
    AVX512F.VFNMADD213PD.meta,
    AVX512F.VFNMADD213PS.meta,
    AVX512F.VFNMADD231PD.meta,
    AVX512F.VFNMADD231PS.meta,
    AVX512F.VFNMSUB132PD.meta,
    AVX512F.VFNMSUB132PS.meta,
    AVX512F.VFNMSUB213PD.meta,
    AVX512F.VFNMSUB213PS.meta,
    AVX512F.VFNMSUB231PD.meta,
    AVX512F.VFNMSUB231PS.meta,
    AVX512F.VFMADDSUB132PD.meta,
    AVX512F.VFMADDSUB132PS.meta,
    AVX512F.VFMADDSUB213PD.meta,
    AVX512F.VFMADDSUB213PS.meta,
    AVX512F.VFMADDSUB231PD.meta,
    AVX512F.VFMADDSUB231PS.meta,
    AVX512F.VFMSUBADD132PD.meta,
    AVX512F.VFMSUBADD132PS.meta,
    AVX512F.VFMSUBADD213PD.meta,
    AVX512F.VFMSUBADD213PS.meta,
    AVX512F.VFMSUBADD231PD.meta,
    AVX512F.VFMSUBADD231PS.meta,
    AVX512F.VFMADDRND231PD.meta,
    AVX512DQ.ORPD.meta,
    AVX512DQ.ORPS.meta,
    AVX512DQ.XORPD.meta,
    AVX512DQ.XORPS.meta,
    AVX512DQ.ANDPS.meta,
    AVX512DQ.ANDPD.meta,
    AVX512DQ.ANDNPS.meta,
    AVX512DQ.ANDNPD.meta,
    AVX512BW.PMAXSB.meta,
    AVX512BW.PMAXSW.meta,
    AVX512BW.PMAXUB.meta,
    AVX512BW.PMAXUW.meta,
    AVX512BW.PMINSB.meta,
    AVX512BW.PMINSW.meta,
    AVX512BW.PMINUB.meta,
    AVX512BW.PMINUW.meta,
    AVX512BW.VPADDB.meta,
    AVX512BW.VPADDW.meta,
    AVX512BW.VPSUBB.meta,
    AVX512BW.VPSUBW.meta,
    AVX512BW.VPCMPEQB.meta,
    AVX512BW.VPCMPEQW.meta,
    AVX512BW.VPCMPGTB.meta,
    AVX512BW.VPCMPGTW.meta,
    AVX512BW.VPMULLW.meta,
    AVX512BW.VPSUBSB.meta,
    AVX512BW.VPSUBSW.meta,
    AVX512BW.VPSUBUSB.meta,
    AVX512BW.VPSUBUSW.meta,
    AVX512BW.VMOVDQU8.meta,
    AVX512BW.VMOVDQU16.meta,
    AVX512BF16.VDPBF16PS.meta,
    VAES.AESDEC.meta,
    VAES.AESDECLAST.meta,
    VAES.AESENC.meta,
    VAES.AESENCLAST.meta,
    SYSTEM.LDTILECFG.meta,
    SYSTEM.LOADIWKEY.meta,
    SYSTEM.MOVDIR64B.meta,
    // CONVERT group (P0 — critical)
    AVX512F.CVTPD2PS.meta,
    AVX512F.CVTPS2PD.meta,
    AVX512F.CVTDQ2PS.meta,
    AVX512F.CVTPS2DQ.meta,
    AVX512F.CVTTPS2DQ.meta,
    // SHIFT group (P0 — packed shifts)
    AVX512F.VPSLLD.meta,
    AVX512F.VPSRAD.meta,
    AVX512F.VPSRLD.meta,
    // PACK group (P0 — saturating pack)
    AVX512F.VPACKSSDW.meta,
    AVX512F.VPACKUSDW.meta,
    // AVX CONVERT variants (256-bit)
    AVX.VCVTPD2PS.meta,
    AVX.VCVTPS2PD.meta,
    AVX.VCVTDQ2PS.meta,
    AVX.VCVTPS2DQ.meta,
    AVX.VCVTTPS2DQ.meta,
    // AVX2 SHIFT + PACK variants (256-bit)
    AVX2.VPSLLD.meta,
    AVX2.VPSRAD.meta,
    AVX2.VPSRLD.meta,
    AVX2.VPACKSSDW.meta,
    AVX2.VPACKUSDW.meta,
    // AVX512F COMPUTE stubs (registered, not yet implemented)
    AVX512F.VSCALEFPS.meta,
    AVX512F.VSCALEFPD.meta,
    AVX512F.VRANGEPS.meta,
    AVX512F.VRANGEPD.meta,
    AVX512F.VFIXUPIMMPS.meta,
    AVX512F.VFIXUPIMMPD.meta,
    AVX512F.VCOMPRESSPD.meta,
    AVX512F.VCOMPRESSPS.meta,
    AVX512F.VEXPANDPD.meta,
    AVX512F.VEXPANDPS.meta,
    AVX512F.VALIGND.meta,
    AVX512F.VALIGNQ.meta,
    AVX512F.VPERMD.meta,
    AVX512F.VPERMQ.meta,
    // P1: ABSOLUTE — absolute value
    AVX2.VPABSB.meta,
    AVX2.VPABSW.meta,
    AVX2.VPABSD.meta,
    AVX512F.VPABSD.meta,
    AVX512F.VPABSQ.meta,
    AVX512BW.VPABSB.meta,
    AVX512BW.VPABSW.meta,
    // P1: REVERSE — sign negation
    AVX2.VPSIGNB.meta,
    AVX2.VPSIGNW.meta,
    AVX2.VPSIGND.meta,
    // P1: PERMUTE — immediate permute (VPERMIL)
    AVX.VPERMILPS.meta,
    AVX.VPERMILPD.meta,
    // P1: INSERT — element + block insertion
    AVX.PINSRB.meta,
    AVX.PINSRD.meta,
    AVX.PINSRQ.meta,
    AVX.PINSRW.meta,
    AVX.INSERTPS.meta,
    AVX.VINSERTF128.meta,
    // LOAD — broadcast
    AVX.VBROADCASTSS.meta,
    AVX.VBROADCASTSD.meta,
    AVX.VBROADCASTF128.meta,
    // MOV — partial register moves
    AVX.MOVHLPS.meta,
    AVX.VMOVHLPS.meta,
    AVX.MOVLHPS.meta,
    AVX.VMOVLHPS.meta,
    AVX.MOVHPD.meta,
    AVX.VMOVHPD.meta,
    AVX.MOVHPS.meta,
    AVX.VMOVHPS.meta,
    AVX.MOVLPD.meta,
    AVX.VMOVLPD.meta,
    AVX.MOVLPS.meta,
    AVX.VMOVLPS.meta,
    AVX.MOVSD.meta,
    AVX.VMOVSD.meta,
    AVX.MOVSS.meta,
    AVX.VMOVSS.meta,
    AVX2.VBROADCASTI128.meta,
    AVX2.VINSERTI128.meta,
    AVX512F.VBROADCASTF32X2.meta,
    AVX512F.VBROADCASTF32X4.meta,
    AVX512F.VBROADCASTF32X8.meta,
    AVX512F.VBROADCASTF64X2.meta,
    AVX512F.VBROADCASTF64X4.meta,
    AVX512F.VBROADCASTI32x2.meta,
    AVX512F.VBROADCASTI32X4.meta,
    AVX512F.VBROADCASTI32X8.meta,
    AVX512F.VBROADCASTI64X2.meta,
    AVX512F.VBROADCASTI64X4.meta,
    AVX512F.VINSERTF32X4.meta,
    AVX512F.VINSERTF64X2.meta,
    AVX512F.VINSERTI32X4.meta,
    AVX512F.VINSERTI64X2.meta,
    AVX512F.VINSERTF32X8.meta,
    AVX512F.VINSERTF64X4.meta,
    AVX512F.VINSERTI32X8.meta,
    AVX512F.VINSERTI64X4.meta,
    // P1: BROADCAST — lane broadcast
    AVX512F.VPBROADCASTMB2Q.meta,
    AVX512F.VPBROADCASTMW2D.meta,
    // P2: DOWN_CONVERT — truncation
    AVX512F.VPMOVDB.meta,
    AVX512F.VPMOVDW.meta,
    AVX512F.VPMOVQB.meta,
    AVX512F.VPMOVQD.meta,
    AVX512F.VPMOVQW.meta,
    AVX512BW.VPMOVWB.meta,
    // P2: DOWN_CONVERT — signed saturation
    AVX512F.VPMOVSDB.meta,
    AVX512F.VPMOVSDW.meta,
    AVX512F.VPMOVSQB.meta,
    AVX512F.VPMOVSQD.meta,
    AVX512F.VPMOVSQW.meta,
    AVX512BW.VPMOVSWB.meta,
    // P2: DOWN_CONVERT — unsigned saturation
    AVX512F.VPMOVUSDB.meta,
    AVX512F.VPMOVUSDW.meta,
    AVX512F.VPMOVUSQB.meta,
    AVX512F.VPMOVUSQD.meta,
    AVX512F.VPMOVUSQW.meta,
    AVX512BW.VPMOVUSWB.meta,
    // P1: COMPLEMENT — bitwise NOT
    AVX512F.VPNOT.meta,
    // P1: UNPACK — interleave low/high
    AVX2.VPUNPCKLBW.meta,
    AVX2.VPUNPCKLWD.meta,
    AVX2.VPUNPCKLDQ.meta,
    AVX2.VPUNPCKLQDQ.meta,
    AVX2.VPUNPCKHBW.meta,
    AVX2.VPUNPCKHWD.meta,
    AVX2.VPUNPCKHDQ.meta,
    AVX2.VPUNPCKHQDQ.meta,
    // P3: AVERAGE — unsigned element average
    AVX2.VPAVGB.meta,
    AVX2.VPAVGW.meta,
    AVX512BW.VPAVGB.meta,
    AVX512BW.VPAVGW.meta,
    // P3: ROTATE — element rotation
    AVX512F.VPROLD.meta,
    AVX512F.VPROLQ.meta,
    AVX512F.VPRORD.meta,
    AVX512F.VPRORQ.meta,
    AVX512F.VPROLVD.meta,
    AVX512F.VPROLVQ.meta,
    AVX512F.VPRORVD.meta,
    AVX512F.VPRORVQ.meta,
    // P3: BITWISE — ternary logic
    AVX512F.VPTERNLOGD.meta,
    AVX512F.VPTERNLOGQ.meta,
    // P3: GALOIS FIELD — GF(2^8) operations
    GFNI.GF2P8MULB.meta,
    GFNI.GF2P8AFFINEQB.meta,
    GFNI.GF2P8AFFINEINVQB.meta,
    // P3: ROUND — float rounding (placeholder)
    // P3: SHA — cryptographic hash operations
    SHA.SHA1MSG1.meta,
    SHA.SHA1MSG2.meta,
    SHA.SHA1NEXTE.meta,
    SHA.SHA1RNDS4.meta,
    SHA.SHA256MSG1.meta,
    SHA.SHA256MSG2.meta,
    SHA.SHA256RNDS2.meta,
    // P3: FULL_PERMUTE — two-source permute
    AVX512F.VPERMI2D.meta,
    AVX512F.VPERMI2Q.meta,
    AVX512F.VPERMI2PS.meta,
    AVX512F.VPERMI2PD.meta,
    AVX512F.VPERMT2D.meta,
    AVX512F.VPERMT2Q.meta,
    AVX512F.VPERMT2PS.meta,
    AVX512F.VPERMT2PD.meta,
    // SHIFT — byte shift (PSLLDQ/PSRLDQ)
    AVX2.PSLLDQ.meta,
    AVX2.PSRLDQ.meta,
    // PACK — word saturation (VPACKSSWB/VPACKUSWB)
    AVX2.VPACKSSWB.meta,
    AVX2.VPACKUSWB.meta,
    // CONVERT — critical conversions (pd2dq, dq2pd, half, bf16)
    AVX512F.CVTPD2DQ.meta,
    AVX512F.CVTTPD2DQ.meta,
    AVX512F.CVTDQ2PD.meta,
    AVX512F.VCVTPH2PS.meta,
    AVX512F.VCVTPS2PH.meta,
    AVX512F.VCVTNEPS2BF16.meta,
    // GATHER — indexed memory load (AVX512F)
    AVX512F.VGATHERDPD.meta,
    AVX512F.VGATHERDPS.meta,
    AVX512F.VGATHERQPD.meta,
    AVX512F.VGATHERQPS.meta,
    AVX512F.VPGATHERDD.meta,
    AVX512F.VPGATHERDQ.meta,
    AVX512F.VPGATHERQD.meta,
    AVX512F.VPGATHERQQ.meta,
    // SCATTER — indexed memory store (AVX512F)
    AVX512F.VSCATTERDPD.meta,
    AVX512F.VSCATTERDPS.meta,
    AVX512F.VSCATTERQPD.meta,
    AVX512F.VSCATTERQPS.meta,
    AVX512F.VPSCATTERDD.meta,
    AVX512F.VPSCATTERDQ.meta,
    AVX512F.VPSCATTERQD.meta,
    AVX512F.VPSCATTERQQ.meta,
};

pub fn tableCount() usize {
    return metas.len;
}

pub fn findByName(name: []const u8) ?types.InstructionMeta {
    for (metas) |meta| if (std.ascii.eqlIgnoreCase(meta.name, name)) return meta;
    return null;
}

pub fn validateAll() types.SafetyError!void {
    for (metas) |meta| try types.validateMeta(meta);
}

pub fn completedCount(features: types.FeatureSet) usize {
    var count: usize = 0;
    for (metas) |meta| {
        if (types.safetyReport(meta, features).ok()) count += 1;
    }
    return count;
}

pub fn progressPermille(features: types.FeatureSet) u16 {
    if (metas.len == 0) return 0;
    return @intCast((completedCount(features) * 1000) / metas.len);
}

pub fn validateRuntimeAbi(runtime_abi: anytype) void {
    runtime_abi.cleo.init();
    defer runtime_abi.cleo.deinit();

    const features = types.FeatureSet.cleoEmulated();
    for (metas) |meta| {
        const plan = meta.plan();
        runtime_abi.cleo.validateWideInstruction(.{
            .name = meta.name,
            .family = meta.family,
            .source_path = meta.source_path,
            .required_feature = @tagName(meta.required_feature),
            .operation = @tagName(meta.operation),
            .max_width_bits = meta.max_width_bits,
            .element_bits = meta.element_bits,
            .block_bits = plan.block_bits,
            .block_count = plan.block_count,
            .uses_neon_blocks = plan.uses_neon_blocks,
            .requires_scalar_fixup = plan.requires_scalar_fixup,
            .supports_masking = plan.supports_masking,
            .supports_broadcast = plan.supports_broadcast,
            .asm_template_present = meta.asm_template.len != 0,
        });
    }
    runtime_abi.cleo.validateRegistry(tableCount(), completedCount(features), progressPermille(features));
}

test "CLEO registry covers current wide ISA tables" {
    try std.testing.expectEqual(@as(usize, 424), tableCount());
    try validateAll();
    const all_features = types.FeatureSet.all();
    try std.testing.expectEqual(tableCount(), completedCount(all_features));
    try std.testing.expectEqual(@as(u16, 1000), progressPermille(all_features));
    const runtime_features = types.FeatureSet.cleoEmulated();
    try std.testing.expect(completedCount(runtime_features) <= tableCount());
    try std.testing.expect(progressPermille(runtime_features) <= 1000);
    try std.testing.expect(findByName("VADDPS") == null);
    try std.testing.expect(findByName("ADDPS") != null);
}
