const std = @import("std");
const types = @import("types.zig");

const BatCommand = types.BatCommand;
const BatError = types.BatError;
const CommandKind = types.CommandKind;
const Redirect = types.Redirect;

/// Translates Windows .bat script content to POSIX shell or Makefile recipes.
pub const BatTranslator = struct {
    allocator: std.mem.Allocator,
    commands: std.ArrayListUnmanaged(BatCommand),

    pub fn init(allocator: std.mem.Allocator) BatTranslator {
        return .{
            .allocator = allocator,
            .commands = .{ .items = &.{}, .capacity = 0 },
        };
    }

    pub fn deinit(self: *BatTranslator) void {
        self.commands.deinit(self.allocator);
    }

    // ---------------------------------------------------------------- //
    //  Parsing (file I/O handled by main.zig)
    // ---------------------------------------------------------------- //

    /// Parse a blob of .bat text into structured commands.
    pub fn parse(self: *BatTranslator, text: []const u8) !void {
        self.commands.clearAndFree(self.allocator);
        var lines = std.mem.splitScalar(u8, text, '\n');
        while (lines.next()) |raw_line| {
            if (parseLine(raw_line)) |cmd| {
                try self.commands.append(self.allocator, cmd);
            }
        }
    }

    // ---------------------------------------------------------------- //
    //  Shell output — builds into caller-provided buffer
    // ---------------------------------------------------------------- //

    /// Generate a POSIX shell script into `out`.
    pub fn toShell(self: *const BatTranslator, shebang: bool, out: *std.ArrayListUnmanaged(u8)) !void {
        if (shebang) {
            try out.appendSlice(self.allocator, "#!/bin/sh\n");
            try out.appendSlice(self.allocator, "# Generated by lib/processor/bat_processor/translator\n\n");
        }
        for (self.commands.items) |cmd| {
            try cmdToShellBuf(cmd, out, self.allocator);
        }
    }

    /// Generate a Makefile recipe into `out`.
    pub fn toMakefile(
        self: *const BatTranslator,
        target: []const u8,
        deps: []const []const u8,
        out: *std.ArrayListUnmanaged(u8),
    ) !void {
        try out.appendSlice(self.allocator, "# Generated by lib/processor/bat_processor/translator\n\n");
        try out.appendSlice(self.allocator, target);
        if (deps.len > 0) {
            try out.appendSlice(self.allocator, ": ");
            for (deps, 0..) |dep, i| {
                if (i > 0) try out.appendSlice(self.allocator, " ");
                try out.appendSlice(self.allocator, dep);
            }
        } else {
            try out.appendSlice(self.allocator, ":");
        }
        try out.appendSlice(self.allocator, "\n\t@echo \"  BATGEN  ");
        try out.appendSlice(self.allocator, target);
        try out.appendSlice(self.allocator, "\"\n");

        for (self.commands.items) |cmd| {
            var line_buf: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
            defer line_buf.deinit(self.allocator);
            try cmdToShellBuf(cmd, &line_buf, self.allocator);
            const shell_line = line_buf.items;

            if (shell_line.len == 0) continue;
            if (shell_line[0] == '#') {
                try out.appendSlice(self.allocator, "\t");
                try out.appendSlice(self.allocator, shell_line);
            } else {
                if (cmd.suppress) try out.appendSlice(self.allocator, "\t@");
                if (!cmd.suppress) try out.appendSlice(self.allocator, "\t");
                // $$ escaping for Make
                for (shell_line) |ch| {
                    if (ch == '$') {
                        try out.appendSlice(self.allocator, "$$");
                    } else {
                        try out.append(self.allocator, ch);
                    }
                }
                try out.append(self.allocator, '\n');
            }
        }
    }
};

// ==================================================================== //
//  Free-standing functions
// ==================================================================== //

/// Parse a single raw line. Returns null for blank lines.
fn parseLine(raw: []const u8) ?BatCommand {
    const line = trimRight(raw, " \t\r");
    const stripped = trimLeft(line, " \t");
    if (stripped.len == 0) return null;

    // -- labels (start with ':' but not '::')
    if (stripped[0] == ':' and !std.mem.startsWith(u8, stripped, "::")) {
        return BatCommand{
            .kind = .label,
            .raw = line,
            .label_name = trimLeft(stripped[1..], " \t"),
        };
    }

    // -- comments (:: or rem)
    if (std.mem.startsWith(u8, stripped, "::") or
        std.mem.startsWith(u8, stripped, "rem ") or
        std.mem.eql(u8, stripped, "rem"))
    {
        const text = if (std.mem.startsWith(u8, stripped, "::"))
            stripped[2..]
        else if (stripped.len > 3)
            stripped[3..]
        else
            "";
        return BatCommand{
            .kind = .comment,
            .raw = line,
            .comment_text = text,
        };
    }

    // -- bare "echo" -> echo status indicator
    if (std.ascii.eqlIgnoreCase(stripped, "echo")) {
        return BatCommand{
            .kind = .command,
            .raw = line,
            .command = "echo",
            .args = "",
        };
    }

    // -- @ prefix
    const suppress = stripped[0] == '@';
    var content = if (suppress) stripped[1..] else stripped;
    content = trimLeft(content, " \t");

    // -- extract trailing redirect
    var redirect: ?Redirect = null;
    if (extractRedirect(content)) |r| {
        redirect = r;
        const redir_offset = findRedirectOffset(content);
        content = trimRight(content[0..redir_offset], " \t");
    }

    // -- split command + args (first space-delimited word)
    const space_idx = std.mem.indexOfScalar(u8, content, ' ') orelse content.len;
    const cmd_word = content[0..space_idx];
    if (cmd_word.len == 0) return null;
    const args = if (space_idx < content.len) content[space_idx + 1 ..] else "";

    return BatCommand{
        .kind = .command,
        .raw = line,
        .suppress = suppress,
        .command = cmd_word,
        .args = args,
        .redirect = redirect,
    };
}

/// Translate one command to shell text, appending to `out`.
fn cmdToShellBuf(cmd: BatCommand, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    switch (cmd.kind) {
        .label => {
            try out.appendSlice(allocator, trimRight(cmd.raw, " \t\r"));
            try out.append(allocator, '\n');
        },
        .comment => {
            const trimmed = trimLeft(cmd.comment_text, " \t");
            try out.appendSlice(allocator, "# ");
            try out.appendSlice(allocator, trimmed);
            try out.append(allocator, '\n');
        },
        .command => {
            try translateCommandBuf(cmd, out, allocator);
        },
    }
}

fn translateCommandBuf(cmd: BatCommand, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    const command = cmd.command;
    const args = cmd.args;
    const r = cmd.redirect;

    // -- @echo off
    if (std.ascii.eqlIgnoreCase(command, "echo") and
        std.ascii.eqlIgnoreCase(std.mem.trim(u8, args, " \t"), "off"))
    {
        try out.appendSlice(allocator, "set +v  # @echo off\n");
        return;
    }

    // -- plain echo (no redirect)
    if (std.ascii.eqlIgnoreCase(command, "echo") and r == null) {
        try out.appendSlice(allocator, "printf '%s\\n' ");
        try appendShQuote(out, allocator, args);
        try out.append(allocator, '\n');
        return;
    }

    // -- echo with redirect
    if (std.ascii.eqlIgnoreCase(command, "echo") and r != null) {
        const trimmed = std.mem.trim(u8, args, " \t");
        if (trimmed.len == 0 or isBlankEchoVariant(trimmed)) {
            try out.appendSlice(allocator, "printf '\\n' ");
            try appendRedir(out, allocator, r.?);
            try out.append(allocator, '\n');
        } else {
            try out.appendSlice(allocator, "printf '%s\\n' ");
            try appendShQuote(out, allocator, args);
            try out.append(allocator, ' ');
            try appendRedir(out, allocator, r.?);
            try out.append(allocator, '\n');
        }
        return;
    }

    // -- echo: echo. echo; etc (command itself is the special form)
    if (std.ascii.startsWithIgnoreCase(command, "echo") and
        !std.ascii.eqlIgnoreCase(command, "echo") and args.len == 0)
    {
        if (r) |rr| {
            try out.appendSlice(allocator, "printf '\\n' ");
            try appendRedir(out, allocator, rr);
            try out.append(allocator, '\n');
        } else {
            try out.appendSlice(allocator, "printf '\\n'\n");
        }
        return;
    }

    // -- del /F /Q file...
    if (std.ascii.eqlIgnoreCase(command, "del")) {
        try out.appendSlice(allocator, "rm -f");
        var arg_iter = std.mem.splitScalar(u8, args, ' ');
        while (arg_iter.next()) |part| {
            if (part.len > 0 and part[0] != '/') {
                try out.append(allocator, ' ');
                try out.appendSlice(allocator, part);
            }
        }
        try out.append(allocator, '\n');
        return;
    }

    // -- type file >> dest
    if (std.ascii.eqlIgnoreCase(command, "type")) {
        try out.appendSlice(allocator, "cat ");
        try out.appendSlice(allocator, args);
        if (r) |rr| {
            try out.append(allocator, ' ');
            try appendRedir(out, allocator, rr);
        }
        try out.append(allocator, '\n');
        return;
    }

    // -- set VAR=value
    if (std.ascii.eqlIgnoreCase(command, "set")) {
        if (std.mem.indexOfScalar(u8, args, '=')) |eq_idx| {
            const varname = args[0..eq_idx];
            const value = args[eq_idx + 1 ..];
            try out.appendSlice(allocator, varname);
            try out.append(allocator, '=');
            try appendShQuote(out, allocator, value);
            try out.appendSlice(allocator, "; export ");
            try out.appendSlice(allocator, varname);
            try out.append(allocator, '\n');
            return;
        }
    }

    // -- cd
    if (std.ascii.eqlIgnoreCase(command, "cd")) {
        try out.appendSlice(allocator, "cd ");
        try out.appendSlice(allocator, args);
        try out.append(allocator, '\n');
        return;
    }

    // -- mkdir / md
    if (std.ascii.eqlIgnoreCase(command, "mkdir") or std.ascii.eqlIgnoreCase(command, "md")) {
        try out.appendSlice(allocator, "mkdir -p");
        var arg_iter = std.mem.splitScalar(u8, args, ' ');
        while (arg_iter.next()) |part| {
            if (part.len > 0 and part[0] != '/') {
                try out.append(allocator, ' ');
                try out.appendSlice(allocator, part);
            }
        }
        try out.append(allocator, '\n');
        return;
    }

    // -- copy -> cp
    if (std.ascii.eqlIgnoreCase(command, "copy")) {
        try appendCpOrMv(out, allocator, "cp", args, cmd);
        return;
    }

    // -- move -> mv
    if (std.ascii.eqlIgnoreCase(command, "move")) {
        try appendCpOrMv(out, allocator, "mv", args, cmd);
        return;
    }

    // -- call <script>
    if (std.ascii.eqlIgnoreCase(command, "call")) {
        try out.appendSlice(allocator, "# (call) ");
        try out.appendSlice(allocator, args);
        try out.append(allocator, '\n');
        return;
    }

    // -- if exist / if not exist / if "%var%"=="value"
    if (std.ascii.eqlIgnoreCase(command, "if")) {
        try translateIfBuf(cmd, out, allocator);
        return;
    }

    // -- exit /b
    if (std.ascii.eqlIgnoreCase(command, "exit") and std.mem.indexOf(u8, args, "/b") != null) {
        try out.appendSlice(allocator, "exit 0\n");
        return;
    }

    // -- goto
    if (std.ascii.eqlIgnoreCase(command, "goto")) {
        try out.appendSlice(allocator, "# (goto) ");
        try out.appendSlice(allocator, args);
        try out.appendSlice(allocator, "  # shell function / case label\n");
        return;
    }

    // -- for loops (basic)
    if (std.ascii.eqlIgnoreCase(command, "for")) {
        try out.appendSlice(allocator, "# (for) ");
        try out.appendSlice(allocator, args);
        try out.append(allocator, '\n');
        return;
    }

    // -- fallthrough: comment-out untranslated
    try out.appendSlice(allocator, "# (untranslated) ");
    try out.appendSlice(allocator, trimRight(cmd.raw, " \t\r"));
    try out.append(allocator, '\n');
}

fn appendCpOrMv(out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator, comptime unix_cmd: []const u8, args: []const u8, cmd: BatCommand) !void {
    var count: usize = 0;
    var arg_iter = std.mem.splitScalar(u8, args, ' ');
    while (arg_iter.next()) |part| {
        if (part.len > 0 and part[0] != '/') count += 1;
    }
    if (count >= 2) {
        try out.appendSlice(allocator, unix_cmd);
        try out.append(allocator, ' ');
        arg_iter.reset();
        var seen: usize = 0;
        while (arg_iter.next()) |part| {
            if (part.len > 0 and part[0] != '/') {
                if (seen > 0) try out.append(allocator, ' ');
                try out.appendSlice(allocator, part);
                seen += 1;
            }
        }
        try out.append(allocator, '\n');
        return;
    }
    try out.appendSlice(allocator, "# (untranslated) ");
    try out.appendSlice(allocator, trimRight(cmd.raw, " \t\r"));
    try out.append(allocator, '\n');
}

fn translateIfBuf(cmd: BatCommand, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    const raw = std.mem.trim(u8, cmd.raw, " \t\r");
    const raw_lower = std.ascii.allocLowerString(std.heap.page_allocator, raw) catch raw;
    defer if (raw_lower.ptr != raw.ptr) std.heap.page_allocator.free(raw_lower);

    // if not exist <file> <action>
    if (std.mem.indexOf(u8, raw_lower, "if not exist ")) |pos| {
        const rest = raw[pos + "if not exist ".len ..];
        if (std.mem.indexOfScalar(u8, rest, ' ')) |space_idx| {
            const file = rest[0..space_idx];
            const action = trimLeft(rest[space_idx + 1 ..], " \t");
            try out.appendSlice(allocator, "if [ ! -e ");
            try out.appendSlice(allocator, file);
            try out.appendSlice(allocator, " ]; then ");
            try out.appendSlice(allocator, action);
            try out.appendSlice(allocator, "; fi  # (if not exist)\n");
            return;
        }
    }

    // if exist <file> <action>
    if (std.mem.indexOf(u8, raw_lower, "if exist ")) |pos| {
        const rest = raw[pos + "if exist ".len ..];
        if (std.mem.indexOfScalar(u8, rest, ' ')) |space_idx| {
            const file = rest[0..space_idx];
            const action = trimLeft(rest[space_idx + 1 ..], " \t");
            try out.appendSlice(allocator, "if [ -e ");
            try out.appendSlice(allocator, file);
            try out.appendSlice(allocator, " ]; then ");
            try out.appendSlice(allocator, action);
            try out.appendSlice(allocator, "; fi  # (if exist)\n");
            return;
        }
    }

    // if "%var%"=="value" <action>
    if (std.mem.indexOf(u8, raw, "==")) |_| {
        var it = std.mem.splitScalar(u8, raw, '"');
        _ = it.next(); // "if "
        const var_name = it.next() orelse "";
        _ = it.next(); // "=="
        const value = it.next() orelse "";
        const after_equals = std.mem.indexOf(u8, raw, "==") orelse 0;
        var remaining = raw[after_equals + 2 ..];
        if (std.mem.indexOfScalar(u8, remaining, '"')) |_| {
            if (std.mem.indexOfScalarPos(u8, remaining, 1, '"')) |after_quote| {
                remaining = remaining[after_quote + 1 ..];
            }
        }
        const action = std.mem.trim(u8, remaining, " \t");
        try out.appendSlice(allocator, "if [ \"${{");
        try out.appendSlice(allocator, var_name);
        try out.appendSlice(allocator, ":-}}\" = \"");
        try out.appendSlice(allocator, value);
        try out.appendSlice(allocator, "\" ]; then ");
        try out.appendSlice(allocator, action);
        try out.appendSlice(allocator, "; fi\n");
        return;
    }

    try out.appendSlice(allocator, "# (if) ");
    try out.appendSlice(allocator, raw);
    try out.append(allocator, '\n');
}

// -------------------------------------------------------------------- //
//  Append-based quoting utilities
// -------------------------------------------------------------------- //

fn appendShQuote(out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator, s: []const u8) !void {
    try out.append(allocator, '\'');
    for (s) |ch| {
        if (ch == '\'') {
            try out.appendSlice(allocator, "'\\''");
        } else {
            try out.append(allocator, ch);
        }
    }
    try out.append(allocator, '\'');
}

fn appendRedir(out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator, r: Redirect) !void {
    try out.appendSlice(allocator, r.op);
    try out.append(allocator, ' ');
    try out.appendSlice(allocator, r.file);
}

// -------------------------------------------------------------------- //
//  String utilities
// -------------------------------------------------------------------- //

fn trimLeft(s: []const u8, comptime chars: []const u8) []const u8 {
    var start: usize = 0;
    while (start < s.len) {
        const ch = s[start];
        var matched = false;
        inline for (chars) |c| {
            if (ch == c) matched = true;
        }
        if (!matched) break;
        start += 1;
    }
    return s[start..];
}

fn trimRight(s: []const u8, comptime chars: []const u8) []const u8 {
    var end = s.len;
    while (end > 0) {
        const ch = s[end - 1];
        var matched = false;
        inline for (chars) |c| {
            if (ch == c) matched = true;
        }
        if (!matched) break;
        end -= 1;
    }
    return s[0..end];
}

// -------------------------------------------------------------------- //
//  Redirect extraction
// -------------------------------------------------------------------- //

fn extractRedirect(content: []const u8) ?Redirect {
    const trimmed = trimRight(content, " \t");
    var i: usize = trimmed.len;
    while (i > 0) {
        i -= 1;
        if (trimmed[i] == '>' or trimmed[i] == '<') {
            var op_start = i;
            if (i > 0 and trimmed[i] == '>' and trimmed[i - 1] == '>') {
                op_start = i - 1;
            } else if (i == 0 or trimmed[i - 1] == ' ' or trimmed[i - 1] == '\t') {
                // Valid redirect position
            } else {
                continue;
            }

            var file_start = i + 1;
            while (file_start < trimmed.len and (trimmed[file_start] == ' ' or trimmed[file_start] == '\t')) {
                file_start += 1;
            }
            if (file_start >= trimmed.len) return null;

            var file_end = file_start;
            while (file_end < trimmed.len and trimmed[file_end] != ' ' and trimmed[file_end] != '\t') {
                file_end += 1;
            }

            const op = trimmed[op_start .. i + 1];
            const file = trimmed[file_start..file_end];

            if (file_end == trimmed.len) {
                return Redirect{ .op = op, .file = file };
            }
            var j = file_end;
            while (j < trimmed.len) : (j += 1) {
                if (trimmed[j] != ' ' and trimmed[j] != '\t') break;
            } else {
                return Redirect{ .op = op, .file = file };
            }
        }
    }
    return null;
}

fn findRedirectOffset(content: []const u8) usize {
    const trimmed = trimRight(content, " \t");
    var i: usize = trimmed.len;
    while (i > 0) {
        i -= 1;
        if (trimmed[i] == '>') {
            var op_start = i;
            if (i > 0 and trimmed[i - 1] == '>') op_start = i - 1;
            var file_start = i + 1;
            while (file_start < trimmed.len and (trimmed[file_start] == ' ' or trimmed[file_start] == '\t')) {
                file_start += 1;
            }
            var file_end = file_start;
            while (file_end < trimmed.len and trimmed[file_end] != ' ' and trimmed[file_end] != '\t') {
                file_end += 1;
            }
            if (file_end == trimmed.len) return op_start;
            var j = file_end;
            while (j < trimmed.len) : (j += 1) {
                if (trimmed[j] != ' ' and trimmed[j] != '\t') break;
            } else {
                return op_start;
            }
        }
    }
    return content.len;
}

fn isBlankEchoVariant(s: []const u8) bool {
    return s.len == 1 and switch (s[0]) {
        ':', '.', ';', ',', '=', '/', '+' => true,
        else => false,
    };
}
