#!/usr/bin/env python3
"""
lib/processor/bat_processor.translator — Windows .bat to POSIX shell/Makefile translator.

Parses common .bat commands and emits equivalent shell or Makefile recipes,
allowing Windows build scripts to run on macOS/Linux under Rosette.

Supported commands:
  @echo off / echo <text> / echo:<text>
  del /F /Q <file>
  type <file> >> <dest>
  :: / rem comments
  :label / goto label
  if exist / if not exist
  set VAR=value
  cd <dir>
  mkdir <dir>
  copy <src> <dst>
  move <src> <dst>
  call <script>
  exit /b
  for %%i in ...
"""

import os
import re
import sys
import shlex
import subprocess
from pathlib import Path
from typing import Optional


class BatParseError(Exception):
    pass


class BatTranslator:
    """Parse .bat content and translate to POSIX shell or Makefile recipes."""

    def __init__(self):
        self.commands: list[dict] = []

    # ------------------------------------------------------------------ #
    #  Parsing
    # ------------------------------------------------------------------ #

# Take a blob of script text and transform it into structured command dicts
    def parse(self, text: str):
        self.commands = [self._parse_line(l) for l in text.splitlines()]
        self.commands = [c for c in self.commands if c is not None]
        return self

    def parse_file(self, path: os.PathLike):
        return self.parse(Path(path).read_text(encoding="utf-8", errors="replace"))

    _RE_REDIR = re.compile(r"(>>?)\s*(\S+)$")
    _RE_SET   = re.compile(r'^set\s+(\w+)=(.*)', re.IGNORECASE)

    def _parse_line(self, raw: str) -> Optional[dict]:
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            return None

        # -- labels
        if stripped.startswith(":") and not stripped.startswith("::"):
            return {"type": "label", "raw": line, "name": stripped[1:].strip()}

        # -- comments
        if stripped.startswith("::") or stripped.startswith("rem ") or stripped == "rem":
            return {"type": "comment", "raw": line, "text": stripped}

        # -- echo with no redirect: just "ECHO is on/off" indicator
        if stripped.lower() == "echo":
            return {"type": "command", "command": "echo", "args": "", "redirect": None, "suppress": False, "raw": line}

        # -- @ prefix
        suppress = stripped.startswith("@")
        content  = stripped[1:] if suppress else stripped

        # -- extract trailing redirect
        redirect = None
        m = self._RE_REDIR.search(content)
        if m:
            redirect = {"op": m.group(1), "file": m.group(2)}
            content_before = content[: m.start()].strip()
        else:
            content_before = content

        # -- split command + args
        parts = content_before.split(maxsplit=1)
        if not parts:
            return None
        command = parts[0].lower()
        args    = parts[1] if len(parts) > 1 else ""

        return {
            "type": "command",
            "raw": line,
            "suppress": suppress,
            "command": command,
            "args": args,
            "redirect": redirect,
        }

    # ------------------------------------------------------------------ #
    #  Translation helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _sh_quote(s: str) -> str:
        """Single-quote a string for POSIX shell (safe for printf)."""
        escaped = s.replace("'", "'\\''")
        return f"'{escaped}'"

    @staticmethod
    def _make_quote(s: str) -> str:
        """Quote for Makefile recipes (double-quote style)."""
        escaped = s.replace('"', '\\"').replace('$', '$$')
        return f'"{escaped}"'

    @staticmethod
    def _redir_str(r: Optional[dict]) -> str:
        if r is None:
            return ""
        return f"{r['op']} {r['file']}"

    # ------------------------------------------------------------------ #
    #  Shell output
    # ------------------------------------------------------------------ #

    def to_shell(self, shebang: bool = True) -> str:
        """Generate a POSIX shell script equivalent of the parsed .bat."""
        out: list[str] = []
        if shebang:
            out.append("#!/bin/sh")
            out.append("# Generated by lib/processor/bat_processor.translator")
            out.append("")

        for cmd in self.commands:
            out.append(self._cmd_to_shell(cmd))
        return "\n".join(out)

    def _cmd_to_shell(self, cmd: dict) -> str:
        t = cmd["type"]

        if t == "label":
            return cmd["raw"].strip()

        if t == "comment":
            text = cmd["text"]
            if text.startswith("::"):
                return "# " + text[2:].strip()
            return "# " + text[3:].strip()

        command = cmd["command"]
        args    = cmd["args"]
        r       = cmd.get("redirect")

        # -- @echo off  -> disable verbose mode
        if command == "echo" and args.strip() == "off":
            return "set +v  # @echo off"

        # -- plain echo (no redirect)
        if command == "echo" and r is None:
            return f"printf '%s\\n' {self._sh_quote(args)}"

        # -- echo with redirect
        if command == "echo" and r is not None:
            redir = self._redir_str(r)
            # blank-line variants: echo:  echo.  echo;  etc.
            if not args or args in {":", ".", ";", ",", "=", "/", "+"}:
                return f"printf '\\n' {redir}"
            return f"printf '%s\\n' {self._sh_quote(args)} {redir}"

        # -- echo: echo. echo; etc (command itself is "echo:" etc, no args)
        if command.startswith("echo") and command != "echo" and not args:
            redir = self._redir_str(r)
            line  = f"printf '\\n' {redir}" if redir else "printf '\\n'"
            return line.rstrip()

        # -- del /F /Q file…
        if command == "del":
            parts = args.split()
            files = [p for p in parts if not p.startswith("/")]
            return "rm -f " + " ".join(files)

        # -- type file >> dest
        if command == "type":
            redir = self._redir_str(r)
            return f"cat {args} {redir}".rstrip()

        # -- set VAR=value
        m = self._RE_SET.match(cmd["raw"].strip())
        if m:
            varname, value = m.group(1), m.group(2)
            q = self._sh_quote(value)
            return f"{varname}={q}; export {varname}"

        # -- cd
        if command == "cd":
            return f"cd {args}"

        # -- mkdir
        if command in ("mkdir", "md"):
            parts = [p for p in shlex.split(args) if not p.startswith("/")]
            return "mkdir -p " + " ".join(parts)

        # -- copy -> cp
        if command == "copy":
            parts = [p for p in shlex.split(args) if not p.startswith("/")]
            if len(parts) >= 2:
                return "cp " + " ".join(parts[:-1]) + " " + parts[-1]
            return f"# (untranslated) {cmd['raw'].strip()}"

        # -- move -> mv
        if command == "move":
            parts = [p for p in shlex.split(args) if not p.startswith("/")]
            if len(parts) >= 2:
                return "mv " + " ".join(parts[:-1]) + " " + parts[-1]
            return f"# (untranslated) {cmd['raw'].strip()}"

        # -- call <script>
        if command == "call":
            return f"# (call) {args}"

        # -- if exist / if not exist
        if command == "if":
            return self._translate_if(cmd)

        # -- exit /b
        if command == "exit" and "/b" in args:
            return "exit 0"

        # -- goto
        if command == "goto":
            return f"# (goto) {args}  # shell function / case label"

        # -- for loops (basic)
        if command == "for":
            return f"# (for) {args}"

        # -- fallthrough: comment-out untranslated
        return f"# (untranslated) {cmd['raw'].strip()}"

    # ------------------------------------------------------------------ #
    #  Makefile output
    # ------------------------------------------------------------------ #

    def to_makefile(self, target: str = "all", deps: Optional[list[str]] = None) -> str:
        """
        Generate a Makefile recipe from parsed .bat commands.

        When the .bat builds a specific output file (detected via del + type
        patterns), call ``to_makefile()`` and pass the target and its
        dependencies manually for best results.
        """
        out: list[str] = [
            "# Generated by lib/processor/bat_processor.translator",
            "",
        ]
        if not deps:
            deps = []
        out.append(f"{target}: {' '.join(deps)}")
        out.append(f'\t@echo "  BATGEN  {target}"')
        for cmd in self.commands:
            shell_line = self._cmd_to_shell(cmd)
            if not shell_line:
                continue
            if shell_line.startswith("#"):
                out.append(f"\t{shell_line}")
            else:
                at = "@" if cmd.get("suppress") else ""
                escaped = shell_line.replace("$", "$$")
                out.append(f"\t{at}{escaped}")
        return "\n".join(out)

    # ------------------------------------------------------------------ #
    #  Direct execution (pipe to sh)
    # ------------------------------------------------------------------ #

    def execute(self, dry_run: bool = False, workdir: Optional[str] = None) -> int:
        """Translate and execute the parsed .bat under ``/bin/sh``."""
        script = self.to_shell(shebang=False)
        if dry_run:
            print(script)
            return 0
        kwargs: dict = {}
        if workdir is not None:
            kwargs["cwd"] = workdir
        proc = subprocess.run(
            ["/bin/sh"],
            input=script,
            capture_output=False,
            text=True,
            **kwargs,
        )
        return proc.returncode

    # ------------------------------------------------------------------ #
    #  if / else translation
    # ------------------------------------------------------------------ #

    def _translate_if(self, cmd: dict) -> str:
        raw = cmd["raw"].strip()
        # if not exist
        m = re.match(r'if\s+not\s+exist\s+(\S+)\s+(.*)', raw, re.IGNORECASE)
        if m:
            return f"if [ ! -e {m.group(1)} ]; then {m.group(2)}; fi  # (if not exist)"
        # if exist
        m = re.match(r'if\s+exist\s+(\S+)\s+(.*)', raw, re.IGNORECASE)
        if m:
            return f"if [ -e {m.group(1)} ]; then {m.group(2)}; fi  # (if exist)"
        # if "%var%"=="value"
        m = re.match(r'if\s+"[%]?(\w+)[%]?"\s*==\s*"(\w+)"\s+(.*)', raw, re.IGNORECASE)
        if m:
            var = m.group(1)
        return f'if [ "${{{var}:-}}" = "{m.group(2)}" ]; then {m.group(3)}; fi'
        return f"# (if) {raw}"


# ====================================================================== #
#  CLI
# ====================================================================== #

def main(argv: Optional[list[str]] = None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    import argparse
    ap = argparse.ArgumentParser(
        prog="python -m lib.processor.bat_processor.translator",
        description="Translate Windows .bat scripts to POSIX shell or Makefile.",
    )
    ap.add_argument("file", help="Path to the .bat file")
    ap.add_argument(
        "--shell", action="store_true", default=True,
        help="Output a POSIX shell script (default)",
    )
    ap.add_argument(
        "--makefile", action="store_true",
        help="Output a Makefile recipe",
    )
    ap.add_argument("-o", "--output", help="Write output to file instead of stdout")
    ap.add_argument(
        "--run", action="store_true",
        help="Execute the translated script directly via /bin/sh",
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Print the shell script that would be executed (implies --shell)",
    )
    ap.add_argument("--target", default="generated_target",
                     help="Makefile target name (default: generated_target)")
    ap.add_argument("--deps", nargs="*", default=[],
                     help="Makefile dependencies")

    args = ap.parse_args(argv)

    bat_path = Path(args.file)
    if not bat_path.exists():
        print(f"error: file not found: {bat_path}", file=sys.stderr)
        return 1

    translator = BatTranslator()
    translator.parse_file(bat_path)

    # --run / --dry-run always use shell mode
    if args.dry_run:
        script = translator.to_shell(shebang=False)
        print(script)
        return 0

    if args.run:
        print(f"# executing: {bat_path}")
        return translator.execute(workdir=str(bat_path.parent))

    if args.makefile:
        result = translator.to_makefile(target=args.target, deps=args.deps)
    else:
        result = translator.to_shell(shebang=True)

    if args.output:
        Path(args.output).write_text(result)
        print(f"wrote {args.output}")
    else:
        print(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
