//! Family: types — core types, Op enum, register/flag re-exports, ISA ABI contract.
//! Extracted from the universal x86-64 decoder (formerly src/x64-ASM/decoder.zig).

const std = @import("std");
const cpu_state = @import("cpu_state");
const flags = @import("flags");
const bit_test = @import("bit_test");
const isa_registry = @import("isa_registry");
const runtime_abi = @import("runtime_abi_handshake");

pub const highway = @import("isa_highway");
pub const isa_decode = @import("isa_decode");
pub const capabilities = @import("capabilities");

pub const OperandSize = flags.OperandSize;
pub const Condition = flags.Condition;
pub const Size = flags.OperandSize;
pub const Cond = flags.Condition;
pub const RegId = cpu_state.RegId;
pub const Regs = cpu_state.Regs;
pub const Segment = cpu_state.Segment;
pub const SegmentState = cpu_state.SegmentState;

/// Decode mode is owned by the ISA layer (`ISA/decode/mode.zig`); this is a
/// re-export so all consumers route through the ISA central hub.
pub const ExecutionMode = isa_decode.ExecutionMode;

pub const MemoryReferenceKind = enum {
    instruction_fetch,
    stack,
    explicit_data,
    string_source,
    string_destination,
};

pub const RFL_CF = flags.RFL_CF;
pub const RFL_PF = flags.RFL_PF;
pub const RFL_AF = flags.RFL_AF;
pub const RFL_ZF = flags.RFL_ZF;
pub const RFL_SF = flags.RFL_SF;
pub const RFL_OF = flags.RFL_OF;
pub const statusByteForLahf = flags.statusByteForLahf;
pub const applySahf = flags.applySahf;
pub const BitTestOperation = bit_test.Operation;
pub const bitTestRegister = bit_test.applyRegister;
pub const bitTestAndResetRegister = bit_test.resetRegister;
pub const bitTestMemoryOperand = bit_test.memoryOperand;
pub const bitTestMemoryOperandImmediate = bit_test.memoryOperandImmediate;

/// Prefix state shared by every legacy x86-64 instruction family. Keeping
/// this in the decoder prevents each opcode handler from growing its own
/// subtly different prefix loop.
pub const RegisterOperand = struct {
    id: RegId,
    high8: bool = false,
};

pub const MemoryOperand = struct {
    displacement: u64 = 0,
    has_index: bool = false,
    index_reg: RegId = .al_ax_eax_rax,
    scale: u2 = 0,
    has_base: bool = false,
    base_reg: RegId = .al_ax_eax_rax,
    rip_relative: bool = false,
    segment: Segment = .ds,
};

pub const RmOperand = union(enum) {
    register: RegisterOperand,
    memory: MemoryOperand,
};

pub const DecodedModRm = struct {
    reg: RegisterOperand,
    rm: RmOperand,
    group: u3,
};

pub const applySub = flags.applySub;
pub const applySbb = flags.applySbb;
pub const applyAdd = flags.applyAdd;
pub const applyIncDec = flags.applyIncDec;
pub const applyLogic = flags.applyLogic;
pub const evalCond = flags.evalCond;
pub const regVal = cpu_state.regVal;
pub const setReg = cpu_state.setReg;

pub const BitScanKind = enum { bsf, bsr, tzcnt, lzcnt };

pub const BitScanResult = struct {
    value: u64,
    write_destination: bool,
    zero_flag: bool,
    carry_flag: ?bool,
};

pub const PopulationCountResult = struct {
    value: u64,
    rflags: u32,
};

/// Implements scalar POPCNT independently of a particular loader. Intel
/// defines OF, SF, AF, CF and PF as cleared, with ZF set only for a zero source.
pub const Op = enum(u16) {
    invalid,
    nop,
    cmc,
    clc,
    stc,
    fild_mem16,
    fild_mem32,
    fild_mem64,
    fld_mem32,
    fld_mem64,
    fld_mem80,
    fstp_mem80,
    fstp_mem32,
    fstp_mem64,
    fld_st,
    fstp_st,
    fxch_st,
    ffree_st,
    fninit,
    fnstsw_ax,
    fnstcw_mem16,
    fldcw_mem16,
    x87_binary,
    fucomip_st,
    // mov
    mov_mem8_reg8,
    mov_mem16_reg16,
    mov_mem32_reg32,
    mov_mem64_reg64,
    mov_reg8_mem8,
    mov_reg16_mem16,
    mov_reg32_mem32,
    mov_reg64_mem64,
    mov_reg_imm,
    mov_mem8_imm8,
    mov_mem16_imm16,
    mov_mem32_imm32,
    mov_mem64_imm32,
    mov_reg8_reg8,
    mov_reg16_reg16,
    mov_reg32_reg32,
    mov_reg64_reg64,
    add_accum_imm,
    or_accum_imm,
    adc_accum_imm,
    sbb_accum_imm,
    and_accum_imm,
    sub_accum_imm,
    xor_accum_imm,
    cmp_accum_imm,
    // add (reg, r/m) d=1
    add_reg8_mem8,
    add_reg16_mem16,
    add_reg32_mem32,
    add_reg64_mem64,
    // add (r/m, reg) d=0
    add_mem8_reg8,
    add_mem16_reg16,
    add_mem32_reg32,
    add_mem64_reg64,
    // add reg, reg
    add_reg8_reg8,
    add_reg16_reg16,
    add_reg32_reg32,
    add_reg64_reg64,
    add_reg8_imm8,
    add_reg16_imm8,
    add_reg32_imm8,
    add_reg64_imm8,
    adc_reg8_imm8,
    adc_reg16_imm8,
    adc_reg32_imm8,
    adc_reg64_imm8,
    sbb_reg8_imm8,
    add_reg16_imm32,
    add_reg32_imm32,
    add_reg64_imm32,
    add_mem8_imm8,
    add_mem16_imm8,
    add_mem32_imm8,
    add_mem64_imm8,
    adc_reg8_mem8,
    sbb_reg8_mem8,
    // sub (reg, r/m) d=1
    sub_reg8_mem8,
    sub_reg16_mem16,
    sub_reg32_mem32,
    sub_reg64_mem64,
    // sub (r/m, reg) d=0
    sub_mem8_reg8,
    sub_mem16_reg16,
    sub_mem32_reg32,
    sub_mem64_reg64,
    // sub (reg, reg) mod=3
    sub_reg8_reg8,
    sub_reg16_reg16,
    sub_reg32_reg32,
    sub_reg64_reg64,
    // sub r/m, imm8 (80 /5)
    sub_mem8_imm8,
    sub_reg8_imm8,
    sub_reg16_imm8,
    sub_reg32_imm8,
    sub_reg64_imm8,
    sub_reg16_imm32,
    sub_reg32_imm32,
    sub_reg64_imm32,
    sbb_reg8_reg8,
    sbb_reg16_reg16,
    sbb_reg32_reg32,
    sbb_reg64_reg64,
    // logical and/xor
    and_reg8_reg8,
    and_reg16_reg16,
    and_reg32_reg32,
    and_reg64_reg64,
    and_reg8_mem8,
    and_reg16_mem16,
    and_reg32_mem32,
    and_reg64_mem64,
    and_mem8_reg8,
    and_mem16_reg16,
    and_mem32_reg32,
    and_mem64_reg64,
    and_reg8_imm8,
    and_reg16_imm8,
    and_reg32_imm8,
    and_reg64_imm8,
    and_reg16_imm32,
    and_reg32_imm32,
    and_reg64_imm32,
    or_reg8_reg8,
    or_reg16_reg16,
    or_reg32_reg32,
    or_reg64_reg64,
    or_reg8_mem8,
    or_reg16_mem16,
    or_reg32_mem32,
    or_reg64_mem64,
    or_mem8_reg8,
    or_mem16_reg16,
    or_mem32_reg32,
    or_mem64_reg64,
    or_reg8_imm8,
    or_reg16_imm8,
    or_reg32_imm8,
    or_reg64_imm8,
    or_mem8_imm8,
    or_mem16_imm8,
    or_mem32_imm8,
    or_mem64_imm8,
    or_mem16_imm32,
    or_mem32_imm32,
    or_mem64_imm32,
    xor_reg8_reg8,
    xor_reg16_reg16,
    xor_reg32_reg32,
    xor_reg64_reg64,
    xor_reg8_mem8,
    xor_reg16_mem16,
    xor_reg32_mem32,
    xor_reg64_mem64,
    xor_mem8_reg8,
    xor_mem16_reg16,
    xor_mem32_reg32,
    xor_mem64_reg64,
    xor_reg8_imm8,
    xor_reg16_imm8,
    xor_reg32_imm8,
    xor_reg64_imm8,
    // shifts
    rol_reg_cl,
    rol_mem_cl,
    ror_reg_cl,
    ror_mem_cl,
    shl_reg_cl,
    shl_mem_cl,
    shr_reg_cl,
    shr_mem_cl,
    sar_reg_cl,
    sar_mem_cl,
    rol_reg_imm,
    rol_mem_imm,
    ror_reg_imm,
    ror_mem_imm,
    shl_reg_imm,
    shl_mem_imm,
    shr_reg_imm,
    shr_mem_imm,
    sar_reg_imm,
    sar_mem_imm,
    // bit scans and zero counts
    bsf_reg_reg,
    bsf_reg_mem,
    bsr_reg_reg,
    bsr_reg_mem,
    tzcnt_reg_reg,
    tzcnt_reg_mem,
    lzcnt_reg_reg,
    lzcnt_reg_mem,
    popcnt_reg_reg,
    popcnt_reg_mem,
    bswap_reg,
    crc32_reg_reg,
    crc32_reg_mem,
    // test
    test_reg8_reg8,
    test_reg16_reg16,
    test_reg32_reg32,
    test_reg64_reg64,
    test_mem8_reg8,
    test_mem16_reg16,
    test_mem32_reg32,
    test_mem64_reg64,
    test_reg8_imm8,
    test_reg16_imm16,
    test_reg32_imm32,
    test_reg64_imm32,
    test_mem8_imm8,
    test_mem16_imm16,
    test_mem32_imm32,
    test_mem64_imm32,
    neg_reg8,
    neg_reg16,
    neg_reg32,
    neg_reg64,
    neg_mem8,
    neg_mem16,
    neg_mem32,
    neg_mem64,
    not_reg8,
    not_reg16,
    not_reg32,
    not_reg64,
    not_mem8,
    not_mem16,
    not_mem32,
    not_mem64,
    // cmp r/m, r
    cmp_mem8_reg8,
    cmp_mem16_reg16,
    cmp_mem32_reg32,
    cmp_mem64_reg64,
    cmp_reg8_reg8,
    cmp_reg16_reg16,
    cmp_reg32_reg32,
    cmp_reg64_reg64,
    // cmp reg, r/m (3A/3B, d=1)
    cmp_reg8_mem8,
    cmp_reg16_mem16,
    cmp_reg32_mem32,
    cmp_reg64_mem64,
    // cmp r/m, imm8 (83 /7)
    cmp_mem8_imm8,
    cmp_mem16_imm8,
    cmp_mem32_imm8,
    cmp_mem64_imm8,
    cmp_reg8_imm8,
    cmp_reg16_imm8,
    cmp_reg32_imm8,
    cmp_reg64_imm8,
    // inc/dec
    inc_mem8,
    inc_mem16,
    inc_mem32,
    inc_mem64,
    inc_reg8,
    inc_reg16,
    inc_reg32,
    inc_reg64,
    dec_mem8,
    dec_mem16,
    dec_mem32,
    dec_mem64,
    dec_reg8,
    dec_reg16,
    dec_reg32,
    dec_reg64,
    // mul/imul/div/idiv (memory)
    mul_mem8,
    mul_mem16,
    mul_mem32,
    mul_mem64,
    imul_mem8,
    imul_mem16,
    imul_mem32,
    imul_mem64,
    div_mem8,
    div_mem16,
    div_mem32,
    div_mem64,
    idiv_mem8,
    idiv_mem16,
    idiv_mem32,
    idiv_mem64,
    // mul/imul/div/idiv (register)
    mul_reg8,
    mul_reg16,
    mul_reg32,
    mul_reg64,
    imul_reg8,
    imul_reg16,
    imul_reg32,
    imul_reg64,
    div_reg8,
    div_reg16,
    div_reg32,
    div_reg64,
    idiv_reg8,
    idiv_reg16,
    idiv_reg32,
    idiv_reg64,
    // imul r, r/m (0F AF)
    imul_reg64_mem64,
    imul_reg64_reg64,
    imul_reg32_mem32,
    imul_reg32_reg32,
    // imul r, r/m, imm8 (6B)
    imul_reg64_mem64_imm8,
    imul_reg64_reg64_imm8,
    imul_reg32_mem32_imm8,
    imul_reg32_reg32_imm8,
    // stack / calls
    call_rel32,
    ret,
    push_reg,
    push_mem64,
    push_imm,
    pop_reg,
    pop_mem64,
    lods,
    // sign extend
    cbw,
    cwde,
    cdqe,
    cwd,
    cdq,
    cqo,
    // zero/sign extend loads
    movzx_reg32_mem8,
    movzx_reg32_mem16,
    movsx_reg32_mem8,
    movsx_reg32_mem16,
    movsxd_reg64_reg32,
    movsxd_reg64_mem32,
    lea_reg_mem,
    cmovcc_reg_reg,
    cmovcc_reg_mem,
    setcc_reg8,
    setcc_mem8,
    cmpxchg_mem8_reg8,
    cmpxchg_mem16_reg16,
    cmpxchg_mem32_reg32,
    cmpxchg_mem64_reg64,
    cmpxchg_reg8_reg8,
    cmpxchg_reg16_reg16,
    cmpxchg_reg32_reg32,
    cmpxchg_reg64_reg64,
    cmpxchg8b_mem,
    cmpxchg16b_mem,
    xchg_mem32_reg32,
    xchg_mem64_reg64,
    xchg_reg32_reg32,
    xchg_reg64_reg64,
    xadd_mem8_reg8,
    xadd_mem32_reg32,
    xadd_mem64_reg64,
    xorps_xmm_xmm,
    movups_xmm_xmm,
    movups_xmm_mem,
    movups_mem_xmm,
    movaps_xmm_xmm,
    movaps_xmm_mem,
    movaps_mem_xmm,
    vmovd_xmm_reg32,
    vmovd_xmm_mem32,
    vmovd_reg32_xmm,
    vmovd_mem32_xmm,
    vmovq_xmm_reg64,
    vmovq_xmm_mem64,
    vmovq_reg64_xmm,
    vmovq_mem64_xmm,
    vpinsrb_xmm_xmm_reg32,
    vpinsrb_xmm_xmm_mem8,
    vpinsrd,
    vpinsrq,
    vpinsrw,
    vinsertps,
    vpextrb,
    vpextrw,
    vpextrd,
    vpextrq,
    vextractf128,
    vpshufb,
    vphaddw,
    vphaddd,
    vphaddsw,
    vphsubw,
    vphsubd,
    vphsubsw,
    vpshufd,
    vshufps,
    vpmuludq,
    vpblendw,
    vpunpckhbw,
    vpunpckhwd,
    vpunpckhdq,
    vpunpcklbw,
    vpunpcklwd,
    vpunpcklqdq,
    vpunpckhqdq,
    vpslld,
    vpsllq,
    vpsllw,
    vpslldq,
    vpsrld,
    vpsrlq,
    vpsrlw,
    vpsrldq,
    vpsubb,
    vpsubd,
    vpsubq,
    vpsubw,
    vpaddb,
    vpaddd,
    vpaddq,
    vpaddw,
    vpmullw,
    vpmulld_38,
    vpcmpeqb,
    vpcmpeqw,
    vpcmpeqd,
    vpcmpeqq,
    vpcmpgtb,
    vpcmpgtw,
    vpcmpgtd,
    vpcmpgtq,
    vptest,
    pmovmskb,
    vpmovmskb,
    vpmovmskb_ymm,
    vmovmskps,
    vmovmskpd,
    vmovdqu_xmm_xmm,
    vmovdqu_xmm_mem,
    vmovdqu_mem_xmm,
    vmovdqa_xmm_xmm,
    vmovdqa_xmm_mem,
    vmovdqa_mem_xmm,
    vmovups_xmm_xmm,
    vmovups_xmm_mem,
    vmovups_mem_xmm,
    vmovaps_xmm_xmm,
    vmovaps_xmm_mem,
    vmovaps_mem_xmm,
    vmovupd_xmm_xmm,
    vmovupd_xmm_mem,
    vmovupd_mem_xmm,
    vmovapd_xmm_xmm,
    vmovapd_xmm_mem,
    vmovapd_mem_xmm,
    vmovss_xmm_mem,
    vmovss_mem_xmm,
    vmovsd_xmm_mem,
    vmovsd_mem_xmm,
    vmovlps_xmm_xmm_mem64,
    vmovlps_mem64_xmm,
    vmovlpd_xmm_xmm_mem64,
    vmovlpd_mem64_xmm,
    vmovhps_xmm_xmm_mem64,
    vmovhps_mem64_xmm,
    vmovhpd_xmm_xmm_mem64,
    vmovhpd_mem64_xmm,
    vmovhlps,
    vmovlhps,
    vmovshdup,
    vmovsldup,
    vmovddup,
    vmovdqu_ymm_ymm,
    vmovdqu_ymm_mem,
    vmovdqu_mem_ymm,
    vmovdqa_ymm_ymm,
    vmovdqa_ymm_mem,
    vmovdqa_mem_ymm,
    vmovups_ymm_ymm,
    vmovups_ymm_mem,
    vmovups_mem_ymm,
    vmovaps_ymm_ymm,
    vmovaps_ymm_mem,
    vmovaps_mem_ymm,
    vmovupd_ymm_ymm,
    vmovupd_ymm_mem,
    vmovupd_mem_ymm,
    vmovapd_ymm_ymm,
    vmovapd_ymm_mem,
    vmovapd_mem_ymm,
    vzeroupper,
    vcvtsi2ss_xmm_reg,
    vcvtsi2ss_xmm_mem,
    vcvtsi2sd_xmm_reg,
    vcvtsi2sd_xmm_mem,
    vcvtss2sd,
    vcvtsd2ss,
    vsqrtps,
    vsqrtpd,
    vsqrtss,
    vsqrtsd,
    vaddss,
    vaddsd,
    vaddps,
    vaddpd,
    vmulss,
    vmulsd,
    vmulps,
    vmulpd,
    vsubss,
    vsubsd,
    vsubps,
    vsubpd,
    vdivss,
    vdivsd,
    vdivps,
    vdivpd,
    vucomiss,
    vucomisd,
    vroundss,
    vroundsd,
    vroundps,
    vroundpd,
    vcvttss2si,
    vcvttsd2si,
    vcvtss2si,
    vcvtsd2si,
    vandps,
    vandpd,
    vandnps,
    vandnpd,
    vorps,
    vorpd,
    vxorps,
    vxorpd,
    vpor,
    vpand,
    vpandn,
    vpxor,
    vpunpckldq,
    vunpcklps,
    vunpckhps,
    vunpcklpd,
    vunpckhpd,
    vpermilpd,
    // AVX arithmetic (MIN, MAX, HADD, HSUB, RCP, RSQRT)
    vminps,
    vminpd,
    vminss,
    vminsd,
    vmaxps,
    vmaxpd,
    vmaxss,
    vmaxsd,
    vhaddps,
    vhaddpd,
    vhsubps,
    vhsubpd,
    vrcpps,
    vrcpss,
    vrsqrtps,
    vrsqrtss,
    // AVX2 FMA (VEX.0F38 map: 132/213/231 format)
    vfmadd132ps,
    vfmadd132pd,
    vfmadd213ps,
    vfmadd213pd,
    vfmadd231ps,
    vfmadd231pd,
    vfmsub132ps,
    vfmsub132pd,
    vfmsub213ps,
    vfmsub213pd,
    vfmsub231ps,
    vfmsub231pd,
    // VEX.0F38 FMA ADDSUB/VFMSUBADD
    vfmaddsub132ps,
    vfmaddsub132pd,
    vfmaddsub213ps,
    vfmaddsub213pd,
    vfmaddsub231ps,
    vfmaddsub231pd,
    vfmsubadd132ps,
    vfmsubadd132pd,
    vfmsubadd213ps,
    vfmsubadd213pd,
    vfmsubadd231ps,
    vfmsubadd231pd,
    // SSSE3/AVX2 integer ops (VEX.0F38 map)
    vpsignb,
    vpsignw,
    vpsignd,
    vpsrlvw,
    vpsravw,
    vpsllvw,
    vpabsb,
    vpabsw,
    vpabsd,
    vpmovsxbw,
    vpmovsxbd,
    vpmovsxbq,
    vpmovsxwd,
    vpmovsxwq,
    vpmovsxdq,
    vpmovzxbw,
    vpmovzxbd,
    vpmovzxbq,
    vpmovzxwd,
    vpmovzxwq,
    vpmovzxdq,
    vpmuldq,
    vpacksswb,
    vpackuswb,
    vpackusdw,
    vpermd,
    vpminsb,
    vpminsd,
    vpminuw,
    vpminud,
    vpmaxsb,
    vpmaxsd,
    vpmaxuw,
    vpmaxud,
    vphminposuw,
    vpsrlvd,
    vpsravd,
    vpsllvd,
    vpblendvb,
    vpalignr,
    vpermps,
    // AVX SIMD compare (VCMP)
    vcmpps,
    vcmppd,
    vcmpss,
    vcmpsd,
    // AVX512/AVX COMPUTE group (SCALE, RANGE, FIXUP)
    vscalefps,
    vscalefpd,
    vrangeps,
    vrangepd,
    vfixupimmps,
    vfixupimmpd,
    // AVX512 COMPRESS/EXPAND
    vcompressps,
    vcompresspd,
    vexpandps,
    vexpandpd,
    // AVX BROADCAST
    vbroadcastss,
    vbroadcastsd,
    vbroadcastf128,
    vbroadcasti128,
    // AVX512 PERMUTE
    vpermi2d,
    vpermi2q,
    vpermi2ps,
    vpermi2pd,
    vpermt2d,
    vpermt2q,
    vpermt2ps,
    vpermt2pd,
    // AVX512 GATHER
    vgatherdps,
    vgatherdpd,
    vgatherqps,
    vgatherqpd,
    vpgatherdd,
    vpgatherdq,
    // AVX512 SCATTER
    vscatterdps,
    vscatterdpd,
    vscatterqps,
    vscatterqpd,
    vpscatterdd,
    vpscatterdq,
    // AVX512 TERNARY LOGIC
    vpternlogd,
    vpternlogq,
    // AVX512 CONVERT
    vcvtps2ph,
    vcvtph2ps,
    vcvtne2ps2bf16,
    vcvttps2dq,
    vcvtps2dq,
    vcvtdq2ps,
    vcvtps2pd,
    vcvtpd2ps,
    // AVX512 SHUFFLE
    vshuff32x4,
    vshuff64x2,
    vshufi32x4,
    vshufi64x2,
    // AVX512 ALIGN
    valignd,
    valignq,
    // AVX512 MASK
    vpmovm2d,
    vpmovd2m,
    // AVX512 MULTISHIFT / CONFLICT
    vpmultishiftqb,
    vpconflictd,
    vpconflictq,
    // bit test family
    bt_reg_reg,
    bt_mem_reg,
    bts_reg_reg,
    bts_mem_reg,
    btr_reg_reg,
    btr_mem_reg,
    btc_reg_reg,
    btc_mem_reg,
    bt_reg_imm,
    bt_mem_imm,
    bts_reg_imm,
    bts_mem_imm,
    btr_reg_imm,
    btr_mem_imm,
    btc_reg_imm,
    btc_mem_imm,
    // conditional / unconditional jumps
    jmp_rel8,
    jcc_rel8,
    jcc_rel32,
    jmp_mem64,
    jmp_reg64,
    // syscall
    syscall,
    ud2,
    cpuid,
    xgetbv,
    call_mem64,
    call_reg64,
    hlt,
    // Legacy status-byte transfer. Kept at the end so existing Op numeric
    // values remain stable for trace and cache consumers.
    lahf,
    sahf,
    // Three-byte endian-aware moves. Appended to preserve all existing Op
    // numeric values used by decode caches and trace consumers.
    movbe_reg_mem,
    movbe_mem_reg,
    // ADC ModRM forms. Appended to preserve the numeric values of all earlier
    // operations used by trace and decode-cache consumers.
    adc_reg8_reg8,
    adc_reg16_reg16,
    adc_reg32_reg32,
    adc_reg64_reg64,
    adc_reg16_mem16,
    adc_reg32_mem32,
    adc_reg64_mem64,
    adc_mem8_reg8,
    adc_mem16_reg16,
    adc_mem32_reg32,
    adc_mem64_reg64,
    // SSE/AVX control-state transfers share one architectural MXCSR state.
    ldmxcsr_mem32,
    stmxcsr_mem32,
    // AVX variable-blend (VEX.0F3A 4A/4B/4C: VBLENDVPS/VBLENDVPD/VPBLENDVB).
    // Appended to preserve the numeric values of all earlier operations used
    // by trace and decode-cache consumers.
    vblendvps,
    vblendvpd,
};

fn canonicalMnemonic(op: Op, buffer: *[32]u8) ?[]const u8 {
    if (op == .invalid) return null;
    // Synthetic dispatcher ops do not name a single instruction: x87_binary
    // covers the whole D8-DF arithmetic family (execution switches on
    // `x87.imm`), so there is no one ISA ABI contract for it.
    if (op == .x87_binary) return null;

    const tag = @tagName(op);
    const stem = tag[0 .. std.mem.indexOfScalar(u8, tag, '_') orelse tag.len];
    const canonical = if (std.mem.eql(u8, stem, "cmovcc"))
        "cmove"
    else if (std.mem.eql(u8, stem, "setcc"))
        "sete"
    else if (std.mem.eql(u8, stem, "jcc"))
        "je"
    else if (std.mem.eql(u8, stem, "ud2"))
        "UD2"
    else
        stem;

    std.debug.assert(canonical.len <= buffer.len);
    return std.ascii.upperString(buffer[0..canonical.len], canonical);
}

test "every executable x64 decoder operation has a validated ISA ABI contract" {
    runtime_abi.isa.init();
    defer runtime_abi.isa.deinit();

    const violations_before = runtime_abi.common.violationCount();
    const validations_before = runtime_abi.common.validationCount();

    for (std.enums.values(Op)) |op| {
        var mnemonic_buffer: [32]u8 = undefined;
        const mnemonic = canonicalMnemonic(op, &mnemonic_buffer) orelse continue;
        const table = isa_registry.x86.findByName(mnemonic) orelse {
            std.debug.print("decoder operation {s} has no ISA ABI contract for {s}\n", .{ @tagName(op), mnemonic });
            return error.MissingDecoderIsaContract;
        };
        table.validate();
        isa_registry.neon.validateTable(table);
    }

    try std.testing.expect(runtime_abi.common.validationCount() > validations_before);
    try std.testing.expectEqual(violations_before, runtime_abi.common.violationCount());
}

pub const DecodedInsn = struct {
    op: Op = .invalid,
    size: OperandSize = .bits32,
    dst_size: OperandSize = .bits32,
    dst_reg: RegId = .al_ax_eax_rax,
    src_reg: RegId = .al_ax_eax_rax,
    dst_high8: bool = false,
    src_high8: bool = false,
    addr: u64 = 0,
    imm: u64 = 0,
    len: u8 = 0,
    sib_has_index: bool = false,
    sib_index_reg: RegId = .al_ax_eax_rax,
    sib_scale: u2 = 0,
    sib_has_base: bool = false,
    sib_base_reg: RegId = .al_ax_eax_rax,
    rip_relative: bool = false,
    segment: Segment = .ds,
    has_0x67: bool = false,
    is_reg_form: bool = false,
    cond: Condition = .e,
    xmm_dst: u8 = 0,
    xmm_src: u8 = 0,
    xmm_src2: u8 = 0,
    // Fourth XMM operand (register index). Used by AVX variable-blend
    // instructions (VBLENDVPS/VBLENDVPD/VPBLENDVB) whose mask register is
    // encoded in imm8[7:4].
    xmm_mask: u8 = 0,
    vector_256: bool = false,
    uses_imm: bool = false,
    lock: bool = false,
    // EVEX-specific fields
    opmask: u3 = 0,
    zero_mask: bool = false,
    evex_broadcast: bool = false,
    vector_512: bool = false,
};
