#!/usr/bin/env python3
"""
lib/processor/ps1_processor.translator — Windows PowerShell (.ps1) to POSIX shell/Makefile translator.

Parses common PowerShell syntax and commands, emitting equivalent POSIX shell
or Makefile recipes, allowing Windows build scripts to run on macOS under Rosette.
"""

import os
import re
import sys
import shlex
import subprocess
from pathlib import Path
from typing import Optional


class Ps1ParseError(Exception):
    pass


class Ps1Translator:
    """Parse PowerShell .ps1 content and translate to POSIX shell or Makefile recipes."""

    def __init__(self):
        self.commands: list[dict] = []

    def parse(self, text: str):
        text = self._convert_block_comments(text)
        self.commands = [self._parse_line(l) for l in text.splitlines()]
        self.commands = [c for c in self.commands if c is not None]
        return self

    def parse_file(self, path: os.PathLike):
        return self.parse(Path(path).read_text(encoding="utf-8", errors="replace"))

    def _convert_block_comments(self, text: str) -> str:
        """Converts block comments <# ... #> to standard single-line # comments."""
        def repl(m):
            lines = m.group(1).splitlines()
            return "\n".join(f"# {l.strip()}" for l in lines)
        return re.sub(r"<#(.*?)#>", repl, text, flags=re.DOTALL)

    _RE_VAR = re.compile(r'^\s*\$(\w+)\s*=\s*(.*)')
    _RE_IF_NOT = re.compile(r'^\s*if\s*\(\s*-not\s*\(\s*Test-Path\s+(.*?)\s*\)\s*\)\s*\{(.*)', re.IGNORECASE)
    _RE_IF = re.compile(r'^\s*if\s*\(\s*Test-Path\s+(.*?)\s*\)\s*\{(.*)', re.IGNORECASE)

    def _parse_line(self, raw: str) -> Optional[dict]:
        line = raw.rstrip()
        stripped = line.strip()

        if not stripped:
            return None

        if stripped.startswith("#"):
            return {"type": "comment", "raw": line, "text": stripped[1:].strip()}

        if stripped.startswith("[CmdletBinding(") or stripped.startswith("param(") or stripped.startswith("#Requires"):
            return {"type": "comment", "raw": line, "text": f"ignored: {stripped}"}

        if "StrictMode" in stripped or "ErrorActionPreference" in stripped:
            return {"type": "comment", "raw": line, "text": f"setup: {stripped}"}

        m_var = self._RE_VAR.match(stripped)
        if m_var:
            return {
                "type": "variable",
                "raw": line,
                "name": m_var.group(1),
                "value": m_var.group(2).strip()
            }

        m_if_not = self._RE_IF_NOT.match(stripped)
        if m_if_not:
            return {
                "type": "if_not_path",
                "raw": line,
                "path": m_if_not.group(1).strip(),
                "body": m_if_not.group(2).strip()
            }

        m_if = self._RE_IF.match(stripped)
        if m_if:
            return {
                "type": "if_path",
                "raw": line,
                "path": m_if.group(1).strip(),
                "body": m_if.group(2).strip()
            }

        if stripped == "}":
            return {"type": "block_end", "raw": line}

        parts = stripped.split(maxsplit=1)
        command = parts[0]
        args = parts[1] if len(parts) > 1 else ""

        return {
            "type": "command",
            "raw": line,
            "command": command,
            "args": args,
        }

    @staticmethod
    def _sh_quote(s: str) -> str:
        """Quotes a string for POSIX shell."""
        if (s.startswith('"') and s.endswith('"')) or (s.startswith("'") and s.endswith("'")):
            s = s[1:-1]
        s = s.replace("$PSScriptRoot", "$(dirname \"$0\")")
        s = s.replace("$scriptDir", "$(dirname \"$0\")")
        s = re.sub(r'\$(\w+)', r'$\1', s)
        return s

    def to_shell(self, shebang: bool = True) -> str:
        """Generate a POSIX shell script equivalent of the parsed .ps1."""
        out: list[str] = []
        if shebang:
            out.append("#!/bin/sh")
            out.append("# Generated by lib/processor/ps1_processor.translator")
            out.append("set -e  # stop on errors")
            out.append("")

        for cmd in self.commands:
            translated = self._cmd_to_shell(cmd)
            if translated:
                out.append(translated)
        return "\n".join(out)

    def _cmd_to_shell(self, cmd: dict) -> str:
        t = cmd["type"]

        if t == "comment":
            return "# " + cmd["text"]

        if t == "block_end":
            return "fi"

        if t == "variable":
            name = cmd["name"]
            val = self._sh_quote(cmd["value"])
            if "Join-Path" in val:
                m_jp = re.search(r'Join-Path\s+(\S+)\s+(\S+)', val)
                if m_jp:
                    base = self._sh_quote(m_jp.group(1))
                    sub = self._sh_quote(m_jp.group(2))
                    return f'{name}="{base}/{sub}"'
            return f'{name}="{val}"'

        if t == "if_not_path":
            path = self._sh_quote(cmd["path"])
            body = self._cmd_to_shell(self._parse_line(cmd["body"])) if cmd["body"] else ""
            if body:
                return f'if [ ! -e "{path}" ]; then\n  {body}\nfi'
            return f'if [ ! -e "{path}" ]; then'

        if t == "if_path":
            path = self._sh_quote(cmd["path"])
            body = self._cmd_to_shell(self._parse_line(cmd["body"])) if cmd["body"] else ""
            if body:
                return f'if [ -e "{path}" ]; then\n  {body}\nfi'
            return f'if [ -e "{path}" ]; then'

        command = cmd["command"]
        args = cmd["args"]

        if command in ("Write-Host", "Write-Output", "Write-Warning", "Write-Error"):
            clean_args = self._sh_quote(args)
            clean_args = re.sub(r'-ForegroundColor\s+\S+', '', clean_args)
            return f'printf \'%s\\n\' "{clean_args.strip()}"'

        if command == "New-Item" and "-ItemType Directory" in args:
            m_path = re.search(r'-Path\s+(\S+)', args)
            path = self._sh_quote(m_path.group(1)) if m_path else ""
            if path:
                return f'mkdir -p "{path}"'
            return "# (untranslated New-Item)"

        if command == "mkdir":
            return f'mkdir -p "{self._sh_quote(args)}"'

        if command == "Move-Item":
            m_path = re.search(r'-Path\s+(\S+)', args)
            m_dest = re.search(r'-Destination\s+(\S+)', args)
            src = self._sh_quote(m_path.group(1)) if m_path else ""
            dst = self._sh_quote(m_dest.group(1)) if m_dest else ""
            if src and dst:
                return f'mv -f "{src}" "{dst}"'
            return "# (untranslated Move-Item)"

        if command == "Remove-Item":
            m_path = re.search(r'-Path\s+(\S+)', args)
            path = self._sh_quote(m_path.group(1)) if m_path else self._sh_quote(args)
            return f'rm -rf "{path}"'

        if command.startswith("&") or command.startswith(".\\"):
            cmd_name = command[1:] if command.startswith("&") else command
            return f'{self._sh_quote(cmd_name)} {self._sh_quote(args)}'

        return f'# (untranslated) {cmd["raw"].strip()}'

    def to_makefile(self, target: str = "all", deps: Optional[list[str]] = None) -> str:
        """Generate a Makefile recipe from parsed .ps1 commands."""
        out: list[str] = [
            "# Generated by lib/processor/ps1_processor.translator",
            "",
        ]
        if not deps:
            deps = []
        out.append(f"{target}: {' '.join(deps)}")
        out.append(f'\t@echo "  PS1GEN  {target}"')
        for cmd in self.commands:
            shell_line = self._cmd_to_shell(cmd)
            if not shell_line:
                continue
            if shell_line.startswith("#"):
                out.append(f"\t{shell_line}")
            else:
                escaped = shell_line.replace("$", "$$")
                out.append(f"\t@{escaped}")
        return "\n".join(out)

    def execute(self, dry_run: bool = False, workdir: Optional[str] = None) -> int:
        """Translate and execute the parsed .ps1 under /bin/sh."""
        script = self.to_shell(shebang=False)
        if dry_run:
            print(script)
            return 0
        kwargs: dict = {}
        if workdir is not None:
            kwargs["cwd"] = workdir
        proc = subprocess.run(
            ["/bin/sh"],
            input=script,
            capture_output=False,
            text=True,
            **kwargs,
        )
        return proc.returncode

def main(argv: Optional[list[str]] = None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    import argparse
    ap = argparse.ArgumentParser(
        prog="python -m lib.processor.ps1_processor.translator",
        description="Translate Windows PowerShell scripts to POSIX shell or Makefile.",
    )
    ap.add_argument("file", help="Path to the .ps1 file")
    ap.add_argument(
        "--shell", action="store_true", default=True,
        help="Output a POSIX shell script (default)",
    )
    ap.add_argument(
        "--makefile", action="store_true",
        help="Output a Makefile recipe",
    )
    ap.add_argument("-o", "--output", help="Write output to file instead of stdout")
    ap.add_argument(
        "--run", action="store_true",
        help="Execute the translated script directly via /bin/sh",
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Print the shell script that would be executed (implies --shell)",
    )
    ap.add_argument("--target", default="generated_target",
                     help="Makefile target name (default: generated_target)")
    ap.add_argument("--deps", nargs="*", default=[],
                     help="Makefile dependencies")

    args = ap.parse_args(argv)

    ps1_path = Path(args.file)
    if not ps1_path.exists():
        print(f"error: file not found: {ps1_path}", file=sys.stderr)
        return 1

    translator = Ps1Translator()
    translator.parse_file(ps1_path)

    if args.dry_run:
        script = translator.to_shell(shebang=False)
        print(script)
        return 0

    if args.run:
        print(f"# executing: {ps1_path}")
        return translator.execute(workdir=str(ps1_path.parent))

    if args.makefile:
        result = translator.to_makefile(target=args.target, deps=args.deps)
    else:
        result = translator.to_shell(shebang=True)

    if args.output:
        Path(args.output).write_text(result)
        print(f"wrote {args.output}")
    else:
        print(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
