const std = @import("std");
const types = @import("types.zig");

const Ps1Command = types.Ps1Command;
const CommandType = types.CommandType;

/// Translates Windows PowerShell (.ps1) content to POSIX shell or
/// Makefile recipes.
///
/// Translates Windows PowerShell (.ps1) content. All slice fields
/// on `Ps1Command` point into the source text, except `text` for
/// "ignored: ..."/"setup: ..." comments which are translator-owned and
/// tracked in `allocated` for deinit.
pub const Ps1Translator = struct {
    allocator: std.mem.Allocator,
    commands: std.ArrayListUnmanaged(Ps1Command),
    /// Translator-owned strings (prefixed comment text) freed on deinit.
    allocated: std.ArrayListUnmanaged([]const u8),

    pub fn init(allocator: std.mem.Allocator) Ps1Translator {
        return .{
            .allocator = allocator,
            .commands = .{ .items = &.{}, .capacity = 0 },
            .allocated = .{ .items = &.{}, .capacity = 0 },
        };
    }

    pub fn deinit(self: *Ps1Translator) void {
        for (self.allocated.items) |owned| self.allocator.free(owned);
        self.allocated.deinit(self.allocator);
        self.commands.deinit(self.allocator);
    }

    // ---------------------------------------------------------------- //
    //  Parsing (file I/O handled by main.zig)
    // ---------------------------------------------------------------- //

    /// Parse a blob of PowerShell text into structured commands.
    pub fn parse(self: *Ps1Translator, text: []const u8) !void {
        self.commands.clearAndFree(self.allocator);
        for (self.allocated.items) |owned| self.allocator.free(owned);
        self.allocated.clearRetainingCapacity();

        const converted = try convertBlockComments(self.allocator, text);
        var lines = std.mem.splitScalar(u8, converted, '\n');
        while (lines.next()) |raw_line| {
            if (try parseLine(self.allocator, raw_line)) |cmd| {
                try self.commands.append(self.allocator, cmd);
                if (cmd.kind == .comment and isOwnedComment(cmd)) {
                    try self.allocated.append(self.allocator, cmd.text);
                }
            }
        }
    }

    // ---------------------------------------------------------------- //
    //  Shell output — builds into caller-provided buffer
    // ---------------------------------------------------------------- //

    /// Generate a POSIX shell script into `out`.
    pub fn toShell(self: *const Ps1Translator, shebang: bool, out: *std.ArrayListUnmanaged(u8)) !void {
        if (shebang) {
            try out.appendSlice(self.allocator, "#!/bin/sh\n");
            try out.appendSlice(self.allocator, "# Generated by lib/processor/ps1_processor.translator\n");
            try out.appendSlice(self.allocator, "set -e  # stop on errors\n\n");
        }
        for (self.commands.items) |cmd| {
            try cmdToShellBuf(cmd, out, self.allocator);
        }
    }

    /// Generate a Makefile recipe into `out`.
    pub fn toMakefile(
        self: *const Ps1Translator,
        target: []const u8,
        deps: []const []const u8,
        out: *std.ArrayListUnmanaged(u8),
    ) !void {
        try out.appendSlice(self.allocator, "# Generated by lib/processor/ps1_processor.translator\n\n");
        try out.appendSlice(self.allocator, target);
        if (deps.len > 0) {
            try out.appendSlice(self.allocator, ": ");
            for (deps, 0..) |dep, i| {
                if (i > 0) try out.appendSlice(self.allocator, " ");
                try out.appendSlice(self.allocator, dep);
            }
        } else {
            try out.appendSlice(self.allocator, ":");
        }
        try out.appendSlice(self.allocator, "\n\t@echo \"  PS1GEN  ");
        try out.appendSlice(self.allocator, target);
        try out.appendSlice(self.allocator, "\"\n");

        for (self.commands.items) |cmd| {
            var line_buf: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
            defer line_buf.deinit(self.allocator);
            try cmdToShellBuf(cmd, &line_buf, self.allocator);
            const shell_line = line_buf.items;

            if (shell_line.len == 0) continue;
            if (shell_line[0] == '#') {
                try out.appendSlice(self.allocator, "\t");
                try out.appendSlice(self.allocator, shell_line);
            } else {
                try out.appendSlice(self.allocator, "\t@");
                for (shell_line) |ch| {
                    if (ch == '$') {
                        try out.appendSlice(self.allocator, "$$");
                    } else {
                        try out.append(self.allocator, ch);
                    }
                }
            }
            try out.append(self.allocator, '\n');
        }
    }
};

// ==================================================================== //
//  Block comment conversion
// ==================================================================== //

/// Convert `<# ... #>` block comments to `#` line comments, matching the
/// Python `re.sub(r"<#(.*?)#>", ...)` with DOTALL.
fn convertBlockComments(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    var out = std.ArrayListUnmanaged(u8){ .items = &.{}, .capacity = 0 };
    errdefer out.deinit(allocator);
    var i: usize = 0;
    while (i < text.len) {
        if (text[i] == '<' and i + 1 < text.len and text[i + 1] == '#') {
            const open_end = i + 2;
            if (std.mem.indexOf(u8, text[open_end..], "#>")) |rel| {
                const close_start = open_end + rel;
                const inner = text[open_end..close_start];
                var lines = std.mem.splitScalar(u8, inner, '\n');
                while (lines.next()) |line| {
                    try out.appendSlice(allocator, "# ");
                    try out.appendSlice(allocator, std.mem.trim(u8, line, " \t"));
                    try out.append(allocator, '\n');
                }
                i = close_start + 2;
                continue;
            }
        }
        try out.append(allocator, text[i]);
        i += 1;
    }
    return out.items;
}

// ==================================================================== //
//  Line parsing
// ==================================================================== //

/// Parse a single raw line into a `Ps1Command`.  Returns null for blank
/// lines.  `owned` tracks the translator allocation used for prefixed
/// comment text ("ignored: ..." / "setup: ...").
fn parseLine(allocator: std.mem.Allocator, raw: []const u8) !?Ps1Command {
    const line = trimRight(raw, " \t\r");
    const stripped = trimLeft(line, " \t");
    if (stripped.len == 0) return null;

    if (stripped[0] == '#') {
        return Ps1Command{
            .kind = .comment,
            .raw = line,
            .text = trimLeft(stripped[1..], " \t"),
        };
    }

    if (startsWith(stripped, "[CmdletBinding(") or
        startsWith(stripped, "param(") or
        startsWith(stripped, "#Requires"))
    {
        return Ps1Command{
            .kind = .comment,
            .raw = line,
            .text = try allocOwned(allocator, "ignored: ", stripped),
        };
    }

    if (indexOf(stripped, "StrictMode") != null or indexOf(stripped, "ErrorActionPreference") != null) {
        return Ps1Command{
            .kind = .comment,
            .raw = line,
            .text = try allocOwned(allocator, "setup: ", stripped),
        };
    }

    if (matchVariable(stripped)) |var_match| {
        return Ps1Command{
            .kind = .variable,
            .raw = line,
            .name = var_match.name,
            .value = var_match.value,
        };
    }

    if (matchIfNotPath(stripped)) |if_match| {
        return Ps1Command{
            .kind = .if_not_path,
            .raw = line,
            .path = if_match.path,
            .body = if_match.body,
        };
    }

    if (matchIfPath(stripped)) |if_match| {
        return Ps1Command{
            .kind = .if_path,
            .raw = line,
            .path = if_match.path,
            .body = if_match.body,
        };
    }

    if (std.mem.eql(u8, stripped, "}")) {
        return Ps1Command{ .kind = .block_end, .raw = line };
    }

    const space_idx = indexOfScalar(stripped, ' ') orelse stripped.len;
    const command = stripped[0..space_idx];
    const args = if (space_idx < stripped.len) stripped[space_idx + 1 ..] else "";

    return Ps1Command{
        .kind = .command,
        .raw = line,
        .command = command,
        .args = args,
    };
}

/// Matches `^\s*\$(\w+)\s*=\s*(.*)`.
fn matchVariable(stripped: []const u8) ?struct { name: []const u8, value: []const u8 } {
    var s = trimLeft(stripped, " \t");
    if (s.len == 0 or s[0] != '$') return null;
    s = s[1..];
    var name_end: usize = 0;
    while (name_end < s.len and isWordChar(s[name_end])) : (name_end += 1) {}
    if (name_end == 0) return null;
    const name = s[0..name_end];
    var rest = trimLeft(s[name_end..], " \t");
    if (rest.len == 0 or rest[0] != '=') return null;
    rest = trimLeft(rest[1..], " \t");
    return .{ .name = name, .value = rest };
}

/// Matches `if (-not (Test-Path <path>)) { <body>` (case-insensitive).
fn matchIfNotPath(stripped: []const u8) ?struct { path: []const u8, body: []const u8 } {
    var s = trimLeft(stripped, " \t");
    if (!startsWithIgnoreCase(s, "if")) return null;
    s = trimLeft(s[2..], " \t");
    if (s.len == 0 or s[0] != '(') return null;
    s = trimLeft(s[1..], " \t");
    if (!startsWithIgnoreCase(s, "-not")) return null;
    s = trimLeft(s[4..], " \t");
    if (s.len == 0 or s[0] != '(') return null;
    s = trimLeft(s[1..], " \t");
    if (!startsWithIgnoreCase(s, "Test-Path")) return null;
    s = s["Test-Path".len..];
    const path_start = trimLeft(s, " \t");
    if (path_start.len == s.len) return null; // no whitespace after Test-Path
    if (findConditionalClose(path_start)) |close| {
        return .{
            .path = trimRight(path_start[0..close.end], " \t"),
            .body = path_start[close.body_start..],
        };
    }
    return null;
}

/// Matches `if (Test-Path <path>) { <body>` (case-insensitive).
fn matchIfPath(stripped: []const u8) ?struct { path: []const u8, body: []const u8 } {
    var s = trimLeft(stripped, " \t");
    if (!startsWithIgnoreCase(s, "if")) return null;
    s = trimLeft(s[2..], " \t");
    if (s.len == 0 or s[0] != '(') return null;
    s = trimLeft(s[1..], " \t");
    if (!startsWithIgnoreCase(s, "Test-Path")) return null;
    s = s["Test-Path".len..];
    const path_start = trimLeft(s, " \t");
    if (path_start.len == s.len) return null; // no whitespace after Test-Path
    if (findCloseParenBrace(path_start)) |close| {
        return .{
            .path = trimRight(path_start[0..close.end], " \t"),
            .body = path_start[close.body_start..],
        };
    }
    return null;
}

const CloseMatch = struct {
    /// End of the captured path (before trailing whitespace / close).
    end: usize,
    /// Position just after the opening `{`.
    body_start: usize,
};

/// Find the earliest `\s*\)\s*\)\s*\{` in `s`, mirroring the non-greedy
/// `(.*?)\s*\)\s*\)\s*\{` of the Python `_RE_IF_NOT`.
fn findConditionalClose(s: []const u8) ?CloseMatch {
    var i: usize = 0;
    while (i < s.len) : (i += 1) {
        var j = i;
        while (j < s.len and (s[j] == ' ' or s[j] == '\t')) j += 1;
        if (j < s.len and s[j] == ')') {
            var k = j + 1;
            while (k < s.len and (s[k] == ' ' or s[k] == '\t')) k += 1;
            if (k < s.len and s[k] == ')') {
                var m = k + 1;
                while (m < s.len and (s[m] == ' ' or s[m] == '\t')) m += 1;
                if (m < s.len and s[m] == '{') {
                    return .{ .end = i, .body_start = m + 1 };
                }
            }
        }
    }
    return null;
}

/// Find the earliest `\s*\)\s*\{` in `s`, mirroring the non-greedy
/// `(.*?)\s*\)\s*\{` of the Python `_RE_IF`.
fn findCloseParenBrace(s: []const u8) ?CloseMatch {
    var i: usize = 0;
    while (i < s.len) : (i += 1) {
        var j = i;
        while (j < s.len and (s[j] == ' ' or s[j] == '\t')) j += 1;
        if (j < s.len and s[j] == ')') {
            var k = j + 1;
            while (k < s.len and (s[k] == ' ' or s[k] == '\t')) k += 1;
            if (k < s.len and s[k] == '{') {
                return .{ .end = i, .body_start = k + 1 };
            }
        }
    }
    return null;
}

// ==================================================================== //
//  Command → shell translation
// ==================================================================== //

const TranslateError = error{OutOfMemory};

fn cmdToShellBuf(cmd: Ps1Command, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) TranslateError!void {
    switch (cmd.kind) {
        .comment => {
            try out.appendSlice(allocator, "# ");
            try out.appendSlice(allocator, cmd.text);
            try out.append(allocator, '\n');
        },
        .block_end => {
            try out.appendSlice(allocator, "fi\n");
        },
        .variable => try translateVariable(cmd, out, allocator),
        .if_not_path => try translateIfPath(cmd, out, allocator, true),
        .if_path => try translateIfPath(cmd, out, allocator, false),
        .command => try translateCommand(cmd, out, allocator),
    }
}

/// `$name = value` — with Join-Path collapsing to `base/sub`.
fn translateVariable(cmd: Ps1Command, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
    defer quoted.deinit(allocator);
    try shQuote(cmd.value, &quoted, allocator);

    if (indexOf(quoted.items, "Join-Path") != null) {
        if (matchJoinPath(quoted.items)) |jp| {
            try out.appendSlice(allocator, cmd.name);
            try out.appendSlice(allocator, "=\"");
            try shQuote(jp.base, out, allocator);
            try out.append(allocator, '/');
            try shQuote(jp.sub, out, allocator);
            try out.appendSlice(allocator, "\"\n");
            return;
        }
    }

    try out.appendSlice(allocator, cmd.name);
    try out.appendSlice(allocator, "=\"");
    try out.appendSlice(allocator, quoted.items);
    try out.appendSlice(allocator, "\"\n");
}

/// Matches `Join-Path <base> <sub>` where both tokens are `\S+`.
fn matchJoinPath(s: []const u8) ?struct { base: []const u8, sub: []const u8 } {
    const pos = indexOf(s, "Join-Path") orelse return null;
    var rest = trimLeft(s[pos + "Join-Path".len ..], " \t");
    const base_end = indexOfScalar(rest, ' ') orelse rest.len;
    if (base_end == 0) return null;
    const base = rest[0..base_end];
    rest = trimLeft(rest[base_end..], " \t");
    const sub_end = indexOfScalar(rest, ' ') orelse rest.len;
    if (sub_end == 0) return null;
    return .{ .base = base, .sub = rest[0..sub_end] };
}

/// `if [ -e "path" ]; then ... fi` (or `! -e` for the -not variant).
/// The inline body is a single line, re-parsed and translated.
fn translateIfPath(cmd: Ps1Command, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator, comptime negated: bool) TranslateError!void {
    var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
    defer quoted.deinit(allocator);
    try shQuote(cmd.path, &quoted, allocator);

    var body_buf: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
    defer body_buf.deinit(allocator);
    if (cmd.body.len != 0) {
        if (try parseLine(allocator, cmd.body)) |body_cmd| {
            try cmdToShellBuf(body_cmd, &body_buf, allocator);
        }
    }

    const negate = if (negated) "! " else "";
    if (body_buf.items.len != 0) {
        try out.appendSlice(allocator, "if [ ");
        try out.appendSlice(allocator, negate);
        try out.appendSlice(allocator, "-e \"");
        try out.appendSlice(allocator, quoted.items);
        try out.appendSlice(allocator, "\" ]; then\n  ");
        try out.appendSlice(allocator, body_buf.items);
        try out.appendSlice(allocator, "fi\n");
    } else {
        try out.appendSlice(allocator, "if [ ");
        try out.appendSlice(allocator, negate);
        try out.appendSlice(allocator, "-e \"");
        try out.appendSlice(allocator, quoted.items);
        try out.appendSlice(allocator, "\" ]; then\n");
    }
}

fn translateCommand(cmd: Ps1Command, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    const command = cmd.command;
    const args = cmd.args;

    // Write-Host / Write-Output / Write-Warning / Write-Error
    if (std.ascii.eqlIgnoreCase(command, "Write-Host") or
        std.ascii.eqlIgnoreCase(command, "Write-Output") or
        std.ascii.eqlIgnoreCase(command, "Write-Warning") or
        std.ascii.eqlIgnoreCase(command, "Write-Error"))
    {
        var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer quoted.deinit(allocator);
        try shQuote(args, &quoted, allocator);
        var clean: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer clean.deinit(allocator);
        try stripForegroundColor(quoted.items, &clean, allocator);
        try out.appendSlice(allocator, "printf '%s\\n' \"");
        try out.appendSlice(allocator, std.mem.trim(u8, clean.items, " \t"));
        try out.appendSlice(allocator, "\"\n");
        return;
    }

    // New-Item -ItemType Directory
    if (std.ascii.eqlIgnoreCase(command, "New-Item") and indexOf(args, "-ItemType Directory") != null) {
        var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer quoted.deinit(allocator);
        if (matchFlagPath(args, "-Path")) |path_token| {
            try shQuote(path_token, &quoted, allocator);
            try out.appendSlice(allocator, "mkdir -p \"");
            try out.appendSlice(allocator, quoted.items);
            try out.appendSlice(allocator, "\"\n");
            return;
        }
        try out.appendSlice(allocator, "# (untranslated New-Item)\n");
        return;
    }

    // mkdir
    if (std.ascii.eqlIgnoreCase(command, "mkdir")) {
        var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer quoted.deinit(allocator);
        try shQuote(args, &quoted, allocator);
        try out.appendSlice(allocator, "mkdir -p \"");
        try out.appendSlice(allocator, quoted.items);
        try out.appendSlice(allocator, "\"\n");
        return;
    }

    // Move-Item
    if (std.ascii.eqlIgnoreCase(command, "Move-Item")) {
        const src = matchFlagPath(args, "-Path") orelse "";
        const dst = matchFlagPath(args, "-Destination") orelse "";
        if (src.len != 0 and dst.len != 0) {
            var src_q: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
            var dst_q: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
            defer src_q.deinit(allocator);
            defer dst_q.deinit(allocator);
            try shQuote(src, &src_q, allocator);
            try shQuote(dst, &dst_q, allocator);
            try out.appendSlice(allocator, "mv -f \"");
            try out.appendSlice(allocator, src_q.items);
            try out.appendSlice(allocator, "\" \"");
            try out.appendSlice(allocator, dst_q.items);
            try out.appendSlice(allocator, "\"\n");
            return;
        }
        try out.appendSlice(allocator, "# (untranslated Move-Item)\n");
        return;
    }

    // Remove-Item
    if (std.ascii.eqlIgnoreCase(command, "Remove-Item")) {
        var quoted: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer quoted.deinit(allocator);
        const path_token = matchFlagPath(args, "-Path") orelse args;
        try shQuote(path_token, &quoted, allocator);
        try out.appendSlice(allocator, "rm -rf \"");
        try out.appendSlice(allocator, quoted.items);
        try out.appendSlice(allocator, "\"\n");
        return;
    }

    // & <script> / .\ <script> invocation
    if (command[0] == '&' or startsWith(command, ".\\")) {
        const cmd_name = if (command[0] == '&') trimLeft(command[1..], " \t") else command;
        var name_q: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        var args_q: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
        defer name_q.deinit(allocator);
        defer args_q.deinit(allocator);
        try shQuote(cmd_name, &name_q, allocator);
        try shQuote(args, &args_q, allocator);
        try out.appendSlice(allocator, name_q.items);
        try out.append(allocator, ' ');
        try out.appendSlice(allocator, args_q.items);
        try out.append(allocator, '\n');
        return;
    }

    // Untranslated fallthrough
    try out.appendSlice(allocator, "# (untranslated) ");
    try out.appendSlice(allocator, trimRight(cmd.raw, " \t\r"));
    try out.append(allocator, '\n');
}

// ==================================================================== //
//  Quoting / small transforms
// ==================================================================== //

/// POSIX-shell quote for a value, applying the Python `_sh_quote` rules:
/// strip outer quotes, then replace `$PSScriptRoot` / `$scriptDir` with
/// `$(dirname "$0")`.
fn shQuote(s: []const u8, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    var src = s;
    if (src.len >= 2 and
        ((src[0] == '"' and src[src.len - 1] == '"') or
            (src[0] == '\'' and src[src.len - 1] == '\'')))
    {
        src = src[1 .. src.len - 1];
    }
    var i: usize = 0;
    while (i < src.len) {
        if (std.mem.startsWith(u8, src[i..], "$PSScriptRoot")) {
            try out.appendSlice(allocator, "$(dirname \"$0\")");
            i += "$PSScriptRoot".len;
        } else if (std.mem.startsWith(u8, src[i..], "$scriptDir")) {
            try out.appendSlice(allocator, "$(dirname \"$0\")");
            i += "$scriptDir".len;
        } else {
            try out.append(allocator, src[i]);
            i += 1;
        }
    }
}

/// Remove a `-ForegroundColor <token>` clause from `s`.
fn stripForegroundColor(s: []const u8, out: *std.ArrayListUnmanaged(u8), allocator: std.mem.Allocator) !void {
    var i: usize = 0;
    while (i < s.len) {
        if (startsWithIgnoreCase(s[i..], "-ForegroundColor")) {
            var j = i + "-ForegroundColor".len;
            while (j < s.len and (s[j] == ' ' or s[j] == '\t')) j += 1;
            while (j < s.len and s[j] != ' ' and s[j] != '\t') j += 1;
            i = j;
            continue;
        }
        try out.append(allocator, s[i]);
        i += 1;
    }
}

/// Match a `-Flag <token>` pair in `s`, returning the token after the flag.
fn matchFlagPath(s: []const u8, comptime flag: []const u8) ?[]const u8 {
    var i: usize = 0;
    while (i < s.len) {
        const remaining = s[i..];
        if (startsWithIgnoreCase(remaining, flag)) {
            var j = i + flag.len;
            while (j < s.len and (s[j] == ' ' or s[j] == '\t')) j += 1;
            if (j >= s.len) return null;
            const token_start = j;
            while (j < s.len and s[j] != ' ' and s[j] != '\t') j += 1;
            return s[token_start..j];
        }
        i += 1;
    }
    return null;
}

// ==================================================================== //
//  Owned-string helper
// ==================================================================== //

fn isOwnedComment(cmd: Ps1Command) bool {
    return std.mem.startsWith(u8, cmd.text, "ignored: ") or std.mem.startsWith(u8, cmd.text, "setup: ");
}

fn allocOwned(allocator: std.mem.Allocator, prefix: []const u8, suffix: []const u8) ![]u8 {
    const out = try allocator.alloc(u8, prefix.len + suffix.len);
    @memcpy(out[0..prefix.len], prefix);
    @memcpy(out[prefix.len..], suffix);
    return out;
}

// ==================================================================== //
//  String utilities
// ==================================================================== //

fn isWordChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '_';
}

fn trimLeft(s: []const u8, comptime chars: []const u8) []const u8 {
    var start: usize = 0;
    while (start < s.len) {
        const ch = s[start];
        var matched = false;
        inline for (chars) |c| {
            if (ch == c) matched = true;
        }
        if (!matched) break;
        start += 1;
    }
    return s[start..];
}

fn trimRight(s: []const u8, comptime chars: []const u8) []const u8 {
    var end = s.len;
    while (end > 0) {
        const ch = s[end - 1];
        var matched = false;
        inline for (chars) |c| {
            if (ch == c) matched = true;
        }
        if (!matched) break;
        end -= 1;
    }
    return s[0..end];
}

fn startsWith(s: []const u8, comptime prefix: []const u8) bool {
    return std.mem.startsWith(u8, s, prefix);
}

fn startsWithIgnoreCase(s: []const u8, comptime prefix: []const u8) bool {
    if (s.len < prefix.len) return false;
    return std.ascii.eqlIgnoreCase(s[0..prefix.len], prefix);
}

fn indexOf(haystack: []const u8, needle: []const u8) ?usize {
    return std.mem.indexOf(u8, haystack, needle);
}

fn indexOfScalar(haystack: []const u8, needle: u8) ?usize {
    return std.mem.indexOfScalar(u8, haystack, needle);
}

// ==================================================================== //
//  Tests
// ==================================================================== //

const testing = std.testing;

fn translateToShell(arena: std.mem.Allocator, src: []const u8) ![]const u8 {
    var translator = Ps1Translator.init(arena);
    try translator.parse(src);

    var out: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
    try translator.toShell(true, &out);
    return out.items;
}

test "variable assignment" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "$foo = \"bar\"\n");
    try testing.expectEqualStrings("#!/bin/sh\n# Generated by lib/processor/ps1_processor.translator\nset -e  # stop on errors\n\nfoo=\"bar\"\n", result);
}

test "block comment conversion" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "<# a comment\n  spanning lines #>\nWrite-Host \"hi\"\n");
    try testing.expect(std.mem.indexOf(u8, result, "# a comment\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "# spanning lines\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "printf '%s\\n' \"hi\"") != null);
}

test "if not path with body" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "if (-not (Test-Path \"C:\\foo\")) { mkdir foo }\n");
    // Faithful to Python: `(.*)` captures the rest of the line, so the closing
    // `}` becomes part of the body command args.
    try testing.expect(std.mem.indexOf(u8, result, "if [ ! -e \"C:\\foo\" ]; then\n  mkdir -p \"foo }\"\nfi\n") != null);
}

test "if path with body" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "if (Test-Path \"build\") { Write-Host \"exists\" }\n");
    // Faithful to Python: the trailing ` }` is part of the body; the inner
    // Write-Host args keep their quotes because the line is not outer-quoted.
    try testing.expect(std.mem.indexOf(u8, result, "if [ -e \"build\" ]; then\n  printf '%s\\n' \"\"exists\" }\"\nfi\n") != null);
}

test "if not path without body" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "if (-not (Test-Path \"C:\\foo\")) {\n");
    try testing.expect(std.mem.indexOf(u8, result, "if [ ! -e \"C:\\foo\" ]; then\n") != null);
}

test "join-path variable" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "$root = Join-Path $PSScriptRoot \"sub\"\n");
    // Faithful to Python: the replacement happens before Join-Path tokenization,
    // so `\S+\s+\S+` splits inside "$(dirname "$0")" producing the compact form.
    try testing.expect(std.mem.indexOf(u8, result, "root=\"$(dirname/\"$0\")\"\n") != null);
}

test "new-item directory" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "New-Item -ItemType Directory -Path \"build/out\"\n");
    try testing.expect(std.mem.indexOf(u8, result, "mkdir -p \"build/out\"\n") != null);
}

test "move-item" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "Move-Item -Path \"a\" -Destination \"b\"\n");
    try testing.expect(std.mem.indexOf(u8, result, "mv -f \"a\" \"b\"\n") != null);
}

test "remove-item" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "Remove-Item -Path \"tmp\"\n");
    try testing.expect(std.mem.indexOf(u8, result, "rm -rf \"tmp\"\n") != null);
}

test "write-host strips foreground color" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "Write-Host \"done\" -ForegroundColor Green\n");
    // Faithful to Python: args are sh_quoted first (retaining the inner quotes
    // because the line does not start and end with the same quote char), then the
    // -ForegroundColor clause is stripped.
    try testing.expect(std.mem.indexOf(u8, result, "printf '%s\\n' \"\"done\"\"\n") != null);
}

test "untranslated fallthrough" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "Invoke-WebRequest http://example.com\n");
    try testing.expect(std.mem.indexOf(u8, result, "# (untranslated) Invoke-WebRequest http://example.com\n") != null);
}

test "block end becomes fi" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "if (Test-Path \"x\") {\n}\n");
    try testing.expect(std.mem.indexOf(u8, result, "fi\n") != null);
}

test "ignored preamble is commented" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "[CmdletBinding()]\nparam()\n");
    try testing.expect(std.mem.indexOf(u8, result, "# ignored: [CmdletBinding()]\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "# ignored: param()\n") != null);
}

test "setup lines are commented" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "$ErrorActionPreference = \"Stop\"\n");
    try testing.expect(std.mem.indexOf(u8, result, "# setup: $ErrorActionPreference = \"Stop\"\n") != null);
}

test "makefile generation" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var translator = Ps1Translator.init(arena);
    try translator.parse("mkdir foo\nWrite-Host \"hi\"\n");

    var out: std.ArrayListUnmanaged(u8) = .{ .items = &.{}, .capacity = 0 };
    try translator.toMakefile("all", &.{}, &out);
    const result = out.items;

    try testing.expect(std.mem.indexOf(u8, result, "all:\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "\t@echo \"  PS1GEN  all\"\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "\t@mkdir -p \"foo\"\n") != null);
    try testing.expect(std.mem.indexOf(u8, result, "\t@printf '%s\\n' \"hi\"\n") != null);
}

test "empty script produces header only" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const result = try translateToShell(arena, "\n  \n# just a comment\n");
    try testing.expect(std.mem.indexOf(u8, result, "# just a comment\n") != null);
}
