#!/usr/bin/env bash
# Rosette-owned GTK/X11 header policy for Xenia's Xcode path.
#
# The old Xenia scripts selected a Homebrew prefix and rewrote headers in a
# shared /tmp directory. This adapter takes the provider chosen by Rosette,
# emits include settings, and can stage a fresh header tree at an explicit
# destination. Existing output is never overwritten.

set -euo pipefail

_rosette_xenia_gtk_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/xenia/scripts/rosette-xenia-environment.sh
source "${_rosette_xenia_gtk_dir}/rosette-xenia-environment.sh"

rosette_xenia_gtk_components=(
    gtk-3.0
    glib-2.0
    pango-1.0
    cairo
    atk-1.0
    gdk-pixbuf-2.0
    harfbuzz
    X11
    xcb
    fontconfig
)

rosette_xenia_gtk_require_provider() {
    [[ "${ROSETTE_XENIA_CONFIGURED:-0}" == "1" ]] || {
        echo "ERROR: configure the Rosette Xenia environment first" >&2
        return 1
    }
    [[ -n "${ROSETTE_XENIA_PROVIDER_ROOT:-}" ]] || {
        echo "ERROR: selected provider has no include root; GTK cannot be located safely" >&2
        return 1
    }
    if [[ "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}" == "x86_64" ]]; then
        case "${ROSETTE_XENIA_PROVIDER_ROOT}" in
            /opt/homebrew|/opt/homebrew/*)
                echo "ERROR: refusing ARM64 GTK headers for an x86-64 source" >&2
                return 1
                ;;
        esac
    fi
    if [[ "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}" == "arm64" ]]; then
        case "${ROSETTE_XENIA_PROVIDER_ROOT}" in
            /usr/local/x86brew|/usr/local/x86brew/*)
                echo "ERROR: refusing x86brew GTK headers for an ARM64 source" >&2
                return 1
                ;;
        esac
    fi
}

rosette_xenia_gtk_print_flags() {
    rosette_xenia_gtk_require_provider
    local include_root="${ROSETTE_XENIA_PROVIDER_ROOT}/include"
    local component
    local found=0
    for component in "${rosette_xenia_gtk_components[@]}"; do
        if [[ -d "${include_root}/${component}" ]]; then
            printf '%s\n' "-I${include_root}/${component}"
            found=1
        fi
    done
    [[ "${found}" == 1 ]] || {
        echo "ERROR: selected provider has no GTK/X11 header tree: ${include_root}" >&2
        return 1
    }
    if [[ -d "${ROSETTE_XENIA_PROVIDER_ROOT}/lib/glib-2.0/include" ]]; then
        printf '%s\n' "-I${ROSETTE_XENIA_PROVIDER_ROOT}/lib/glib-2.0/include"
    fi
}

rosette_xenia_gtk_emit_xcconfig() {
    local output="${1:?output path is required}"
    rosette_xenia_gtk_require_provider
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite an existing Xcode configuration: ${output}" >&2
        return 1
    }
    local include_root="${2:-${ROSETTE_XENIA_PROVIDER_ROOT}/include}"
    local glib_include="${3:-${ROSETTE_XENIA_PROVIDER_ROOT}/lib/glib-2.0/include}"
    local search_paths=""
    local component
    for component in "${rosette_xenia_gtk_components[@]}"; do
        if [[ -d "${include_root}/${component}" ]]; then
            search_paths="${search_paths} \"${include_root}/${component}\""
        fi
    done
    if [[ -d "${glib_include}" ]]; then
        search_paths="${search_paths} \"${glib_include}\""
    fi
    cat > "${output}" <<EOF
// Generated by Rosette's Xenia script package.
HEADER_SEARCH_PATHS = \$(inherited)${search_paths}
USER_HEADER_SEARCH_PATHS = \$(inherited)${search_paths}
GCC_PREPROCESSOR_DEFINITIONS = \$(inherited) USE_ROSETTE_GTK_PROVIDER=1
EOF
    printf 'rosette Xenia GTK: emitted %s\n' "${output}"
}

rosette_xenia_gtk_stage_headers() {
    local output="${1:?output directory is required}"
    rosette_xenia_gtk_require_provider
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite existing GTK staging output: ${output}" >&2
        return 1
    }
    local staging="${output}.staging.$$"
    [[ ! -e "${staging}" ]] || {
        echo "ERROR: staging path already exists: ${staging}" >&2
        return 1
    }
    mkdir -p "${staging}"

    local include_root="${ROSETTE_XENIA_PROVIDER_ROOT}/include"
    local component source header relative destination
    local copied=0
    for component in "${rosette_xenia_gtk_components[@]}"; do
        source="${include_root}/${component}"
        [[ -d "${source}" ]] || continue
        while IFS= read -r header; do
            relative="${header#"${source}"/}"
            destination="${staging}/${component}/${relative}"
            mkdir -p "$(dirname "${destination}")"
            sed -E \
                -e 's@#[[:space:]]*include[[:space:]]*<((gtk|gdk|glib|gio|gobject|gmodule|pango|atk|gdk-pixbuf|hb|cairo|pangocairo|X11|xcb|fontconfig)[^>]*)>@#include "\1"@g' \
                "${header}" > "${destination}"
            copied=$((copied + 1))
        done < <(find "${source}" -type f -name '*.h' -print)
    done

    local glibconfig="${ROSETTE_XENIA_PROVIDER_ROOT}/lib/glib-2.0/include/glibconfig.h"
    if [[ -f "${glibconfig}" ]]; then
        mkdir -p "${staging}/glib-2.0/include"
        sed -E \
            -e 's@#[[:space:]]*include[[:space:]]*<((glib|gio|gobject|gmodule|glib-object)[^>]*)>@#include "\1"@g' \
            "${glibconfig}" > "${staging}/glib-2.0/include/glibconfig.h"
    fi

    [[ "${copied}" -gt 0 ]] || {
        echo "ERROR: selected provider has no headers that can be staged: ${include_root}" >&2
        return 1
    }
    rosette_xenia_gtk_emit_xcconfig "${staging}/gtk.xcconfig" "${staging}" "${staging}/glib-2.0/include"
    printf 'rosette Xenia GTK: staged %d headers at %s\n' "${copied}" "${staging}"
    mv "${staging}" "${output}"
    export ROSETTE_XENIA_GTK_INCLUDE_ROOT="${output}"
    printf 'rosette Xenia GTK: output=%s\n' "${output}"
}

rosette_xenia_gtk_help() {
    cat <<'EOF'
Rosette Xenia GTK adapter

  rosette-xenia-gtk.sh --source-architecture x86_64 --print
  rosette-xenia-gtk.sh --source-architecture x86_64 --xcconfig path
  rosette-xenia-gtk.sh --source-architecture x86_64 --stage path

The stage path must not already exist. Header staging is generated output and
is separate from the Xenia checkout; project files are not rewritten.
EOF
}

source_image=""
source_architecture=""
print=0
xcconfig=""
stage=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-image)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-image requires a path" >&2; exit 2; }
            source_image="$2"
            shift 2
            ;;
        --source-architecture)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-architecture requires a value" >&2; exit 2; }
            source_architecture="$2"
            shift 2
            ;;
        --print) print=1; shift ;;
        --xcconfig)
            [[ $# -ge 2 ]] || { echo "ERROR: --xcconfig requires a path" >&2; exit 2; }
            xcconfig="$2"
            shift 2
            ;;
        --stage)
            [[ $# -ge 2 ]] || { echo "ERROR: --stage requires a directory" >&2; exit 2; }
            stage="$2"
            shift 2
            ;;
        --help|-h) rosette_xenia_gtk_help; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; rosette_xenia_gtk_help >&2; exit 2 ;;
    esac
done

[[ -n "${source_image}" ]] && export ROSETTE_XENIA_SOURCE_IMAGE="${source_image}"
[[ -n "${source_architecture}" ]] && export ROSETTE_XENIA_SOURCE_ARCHITECTURE="${source_architecture}"
if [[ -n "${source_image}" ]]; then
    rosette_xenia_configure_environment "${source_image}"
else
    rosette_xenia_configure_environment
fi
rosette_xenia_verify_environment
[[ "${print}" == 1 ]] && rosette_xenia_gtk_print_flags
[[ -n "${xcconfig}" ]] && rosette_xenia_gtk_emit_xcconfig "${xcconfig}"
[[ -n "${stage}" ]] && rosette_xenia_gtk_stage_headers "${stage}"
