#!/usr/bin/env bash
# Rosette-owned DXIL/SPIR-V dependency contract.
#
# Xenia's historical setup script copied headers, generated compatibility
# headers, and wrote parser stubs directly into its checkout. Rosette keeps the
# source locations and compiler configuration explicit instead. This adapter
# only audits the inputs and emits a CMake include fragment; it never rewrites
# third-party sources or fabricates a successful shader translation.

set -euo pipefail

_rosette_xenia_dxil_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/xenia/scripts/rosette-xenia-environment.sh
source "${_rosette_xenia_dxil_dir}/rosette-xenia-environment.sh"

rosette_xenia_dxil_require_sources() {
    local root="${1:?Xenia root is required}"
    local required_path
    local missing=0
    for required_path in \
        "${root}/third_party/DirectXShaderCompiler/include/llvm" \
        "${root}/third_party/DirectXShaderCompiler/include/llvm-c" \
        "${root}/third_party/DirectXShaderCompiler/include/dxc" \
        "${root}/third_party/dxil-spirv" \
        "${root}/third_party/dxil-spirv/subprojects/dxbc-spirv/ir" \
        "${root}/third_party/dxil-spirv/third_party/spirv-headers/include/spirv" \
        "${root}/third_party/SPIRV-Tools/include/spirv-tools"; do
        if [[ ! -d "${required_path}" ]]; then
            echo "ERROR: DXIL source dependency is missing: ${required_path}" >&2
            missing=1
        fi
    done
    [[ "${missing}" == 0 ]] || return 1
}

rosette_xenia_dxil_print() {
    local root="${1:?Xenia root is required}"
    rosette_xenia_dxil_require_sources "${root}"
    printf 'Rosette Xenia DXIL dependency contract\n'
    printf '  source architecture: %s\n' "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}"
    printf '  provider: %s\n' "${ROSETTE_XENIA_PROVIDER_ROOT:-system-native}"
    printf '  DXC include: %s\n' "${root}/third_party/DirectXShaderCompiler/include"
    printf '  dxil-spirv root: %s\n' "${root}/third_party/dxil-spirv"
    printf '  SPIRV-Tools include: %s\n' "${root}/third_party/SPIRV-Tools/include"
    printf '  parser stubs: forbidden (translation failure remains observable)\n'
}

rosette_xenia_dxil_emit_cmake() {
    local root="${1:?Xenia root is required}"
    local output="${2:?output path is required}"
    rosette_xenia_dxil_require_sources "${root}"
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite an existing DXIL fragment: ${output}" >&2
        return 1
    }
    cat > "${output}" <<EOF
# Generated by Rosette's Xenia script package.
set(ROSETTE_XENIA_DXC_INCLUDE "${root}/third_party/DirectXShaderCompiler/include")
set(ROSETTE_XENIA_DXIL_SPIRV_ROOT "${root}/third_party/dxil-spirv")
set(ROSETTE_XENIA_SPIRV_TOOLS_INCLUDE "${root}/third_party/SPIRV-Tools/include")
set(ROSETTE_XENIA_DXIL_SOURCE_ARCHITECTURE "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}")
include_directories(
    "\${ROSETTE_XENIA_DXC_INCLUDE}"
    "\${ROSETTE_XENIA_DXIL_SPIRV_ROOT}"
    "\${ROSETTE_XENIA_SPIRV_TOOLS_INCLUDE}"
)
EOF
    printf 'rosette Xenia DXIL: emitted %s\n' "${output}"
}

rosette_xenia_dxil_help() {
    cat <<'EOF'
Rosette Xenia DXIL adapter

  rosette-xenia-dxil.sh --source-architecture x86_64 --xenia-root path --print
  rosette-xenia-dxil.sh --source-architecture x86_64 --xenia-root path \
      --emit-cmake path

This adapter validates existing third-party inputs and emits include paths. It
does not copy, patch, delete, or stub third-party files in the Xenia checkout.
EOF
}

source_image=""
source_architecture=""
xenia_root="${ROSETTE_XENIA_ROOT:-}"
print=0
emit_cmake=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-image)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-image requires a path" >&2; exit 2; }
            source_image="$2"
            shift 2
            ;;
        --source-architecture)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-architecture requires a value" >&2; exit 2; }
            source_architecture="$2"
            shift 2
            ;;
        --xenia-root)
            [[ $# -ge 2 ]] || { echo "ERROR: --xenia-root requires a path" >&2; exit 2; }
            xenia_root="$2"
            shift 2
            ;;
        --print) print=1; shift ;;
        --emit-cmake)
            [[ $# -ge 2 ]] || { echo "ERROR: --emit-cmake requires a path" >&2; exit 2; }
            emit_cmake="$2"
            shift 2
            ;;
        --help|-h) rosette_xenia_dxil_help; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; rosette_xenia_dxil_help >&2; exit 2 ;;
    esac
done

[[ -n "${xenia_root}" ]] || {
    echo "ERROR: --xenia-root or ROSETTE_XENIA_ROOT is required" >&2
    exit 2
}
[[ -n "${source_image}" ]] && export ROSETTE_XENIA_SOURCE_IMAGE="${source_image}"
[[ -n "${source_architecture}" ]] && export ROSETTE_XENIA_SOURCE_ARCHITECTURE="${source_architecture}"
if [[ -n "${source_image}" ]]; then
    rosette_xenia_configure_environment "${source_image}"
else
    rosette_xenia_configure_environment
fi
rosette_xenia_verify_environment
[[ "${print}" == 1 ]] && rosette_xenia_dxil_print "${xenia_root}"
[[ -n "${emit_cmake}" ]] && rosette_xenia_dxil_emit_cmake "${xenia_root}" "${emit_cmake}"

