#!/usr/bin/env bash
# Rosette-owned Vulkan/MoltenVK preflight for the Xenia script surface.
#
# Build-provider selection and the Vulkan runtime are separate contracts. This
# adapter validates that the loader/ICD matches the source architecture and
# reports the exact path; it does not launch Frida or Xenia.

set -euo pipefail

_rosette_xenia_vulkan_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/xenia/scripts/rosette-xenia-environment.sh
source "${_rosette_xenia_vulkan_dir}/rosette-xenia-environment.sh"

rosette_xenia_vulkan_sdk_root() {
    if [[ -n "${ROSETTE_VULKAN_SDK:-}" ]]; then
        printf '%s\n' "${ROSETTE_VULKAN_SDK}"
    elif [[ -n "${VULKAN_SDK:-}" ]]; then
        printf '%s\n' "${VULKAN_SDK}"
    elif [[ -n "${ROSETTE_XENIA_PROVIDER_ROOT:-}" ]]; then
        printf '%s\n' "${ROSETTE_XENIA_PROVIDER_ROOT}"
    else
        printf '%s\n' ""
    fi
}

rosette_xenia_vulkan_find_library() {
    local sdk="$(rosette_xenia_vulkan_sdk_root)"
    local candidate
    for candidate in \
        "${sdk}/lib/libMoltenVK.dylib" \
        "${sdk}/lib/libvulkan.1.dylib" \
        "${sdk}/lib/libvulkan.dylib" \
        "${sdk}/macOS/lib/libMoltenVK.dylib" \
        "${sdk}/macOS/lib/libvulkan.1.dylib" \
        "${sdk}/macOS/lib/libvulkan.dylib"; do
        [[ -f "${candidate}" ]] && { printf '%s\n' "${candidate}"; return 0; }
    done
    return 1
}

rosette_xenia_vulkan_check_architecture() {
    local library="${1:?library path is required}"
    local description
    description="$(file -b -- "${library}" 2>/dev/null || true)"
    case "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}" in
        x86_64)
            case "${description}" in
                *x86_64*|*universal*|*Universal*) ;;
                *) echo "ERROR: Vulkan library is not x86-64/universal for an x86 source: ${library} (${description})" >&2; return 1 ;;
            esac
            ;;
        arm64)
            case "${description}" in
                *arm64*|*universal*|*Universal*) ;;
                *) echo "ERROR: Vulkan library is not ARM64/universal for an ARM64 source: ${library} (${description})" >&2; return 1 ;;
            esac
            ;;
        *) echo "ERROR: no concrete source architecture for Vulkan validation" >&2; return 1 ;;
    esac
}

rosette_xenia_vulkan_find_icd() {
    local sdk="$(rosette_xenia_vulkan_sdk_root)"
    local candidate
    if [[ -n "${VK_ICD_FILENAMES:-}" ]]; then
        printf '%s\n' "${VK_ICD_FILENAMES}"
        return 0
    fi
    for candidate in \
        "${sdk}/share/vulkan/icd.d/MoltenVK_icd.json" \
        "${sdk}/macOS/share/vulkan/icd.d/MoltenVK_icd.json" \
        "${sdk}/etc/vulkan/icd.d/MoltenVK_icd.json" \
        "${sdk}/macOS/etc/vulkan/icd.d/MoltenVK_icd.json"; do
        [[ -f "${candidate}" ]] && { printf '%s\n' "${candidate}"; return 0; }
    done
    return 1
}

rosette_xenia_vulkan_require() {
    [[ "${ROSETTE_XENIA_CONFIGURED:-0}" == "1" ]] || {
        echo "ERROR: configure the Rosette Xenia environment first" >&2
        return 1
    }
    local library
    library="$(rosette_xenia_vulkan_find_library)" || {
        echo "ERROR: no Vulkan/MoltenVK library found under the selected SDK/provider" >&2
        return 1
    }
    rosette_xenia_vulkan_check_architecture "${library}"
    local icd
    icd="$(rosette_xenia_vulkan_find_icd)" || {
        echo "ERROR: no MoltenVK ICD manifest found for the selected SDK/provider" >&2
        return 1
    }
    [[ -f "${icd}" ]] || {
        echo "ERROR: VK_ICD_FILENAMES points at a missing file: ${icd}" >&2
        return 1
    }
    export ROSETTE_XENIA_VULKAN_LIBRARY="${library}"
    export ROSETTE_XENIA_VULKAN_ICD="${icd}"
}

rosette_xenia_vulkan_print() {
    rosette_xenia_vulkan_require
    printf 'Rosette Xenia Vulkan contract\n'
    printf '  source architecture: %s\n' "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}"
    printf '  loader/library: %s\n' "${ROSETTE_XENIA_VULKAN_LIBRARY}"
    printf '  ICD: %s\n' "${ROSETTE_XENIA_VULKAN_ICD}"
    printf '  validation layers: %s\n' "${VK_LAYER_PATH:-not configured}"
    printf '  runtime policy: loader architecture must cover the selected source\n'
}

rosette_xenia_vulkan_emit_environment() {
    local output="${1:?output path is required}"
    rosette_xenia_vulkan_require
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite an existing Vulkan environment file: ${output}" >&2
        return 1
    }
    cat > "${output}" <<EOF
# Generated by Rosette's Xenia script package.
export VULKAN_SDK="$(rosette_xenia_vulkan_sdk_root)"
export VK_ICD_FILENAMES="${ROSETTE_XENIA_VULKAN_ICD}"
export DYLD_LIBRARY_PATH="$(dirname "${ROSETTE_XENIA_VULKAN_LIBRARY}")\${DYLD_LIBRARY_PATH:+:\${DYLD_LIBRARY_PATH}}"
EOF
    printf 'rosette Xenia Vulkan: emitted %s\n' "${output}"
}

rosette_xenia_vulkan_help() {
    cat <<'EOF'
Rosette Xenia Vulkan adapter

  rosette-xenia-vulkan.sh --source-architecture x86_64 --preflight
  rosette-xenia-vulkan.sh --source-architecture x86_64 --print
  rosette-xenia-vulkan.sh --source-architecture x86_64 --emit-env path

VULKAN_SDK or ROSETTE_VULKAN_SDK may name the SDK. If neither is set, the
selected Rosette provider is checked. The library must cover the selected
source architecture; ARM-only Vulkan cannot silently serve x86 source.
EOF
}

source_image=""
source_architecture=""
print=0
preflight=0
emit_environment=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-image)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-image requires a path" >&2; exit 2; }
            source_image="$2"
            shift 2
            ;;
        --source-architecture)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-architecture requires a value" >&2; exit 2; }
            source_architecture="$2"
            shift 2
            ;;
        --print) print=1; shift ;;
        --preflight) preflight=1; shift ;;
        --emit-env)
            [[ $# -ge 2 ]] || { echo "ERROR: --emit-env requires a path" >&2; exit 2; }
            emit_environment="$2"
            shift 2
            ;;
        --help|-h) rosette_xenia_vulkan_help; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; rosette_xenia_vulkan_help >&2; exit 2 ;;
    esac
done

[[ -n "${source_image}" ]] && export ROSETTE_XENIA_SOURCE_IMAGE="${source_image}"
[[ -n "${source_architecture}" ]] && export ROSETTE_XENIA_SOURCE_ARCHITECTURE="${source_architecture}"
if [[ -n "${source_image}" ]]; then
    rosette_xenia_configure_environment "${source_image}"
else
    rosette_xenia_configure_environment
fi
rosette_xenia_verify_environment
if [[ "${print}" == 1 || "${preflight}" == 1 || -n "${emit_environment}" ]]; then
    rosette_xenia_vulkan_require
fi
[[ "${print}" == 1 ]] && rosette_xenia_vulkan_print
[[ -n "${emit_environment}" ]] && rosette_xenia_vulkan_emit_environment "${emit_environment}"
