#!/usr/bin/env bash
# Rosette-owned linker configuration for Xenia's macOS target.
#
# The historical script mixed provider discovery, generated CMake text, and
# build execution. This adapter only resolves the selected provider and emits
# a reusable CMake fragment. The caller decides when to configure or build.

set -euo pipefail

_rosette_xenia_linker_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=tools/xenia/scripts/rosette-xenia-environment.sh
source "${_rosette_xenia_linker_dir}/rosette-xenia-environment.sh"

rosette_xenia_linker_sdl2_flags() {
    local pkg_config="${PKG_CONFIG:-pkg-config}"
    command -v "${pkg_config}" >/dev/null 2>&1 || {
        echo "ERROR: selected provider has no pkg-config executable" >&2
        return 1
    }
    "${pkg_config}" --exists sdl2 || {
        echo "ERROR: selected provider does not expose SDL2 through pkg-config" >&2
        return 1
    }
    local cflags libs
    cflags="$("${pkg_config}" --cflags sdl2)"
    libs="$("${pkg_config}" --libs sdl2)"
    case "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}:${cflags} ${libs}" in
        x86_64:*\/opt\/homebrew*|arm64:*\/usr\/local\/x86brew*)
            echo "ERROR: SDL2 flags belong to a provider incompatible with the source" >&2
            return 1
            ;;
    esac
    printf '%s\n' "${cflags}" "${libs}"
}

rosette_xenia_linker_print() {
    local flags
    flags="$(rosette_xenia_linker_sdl2_flags)"
    printf 'Rosette Xenia linker contract\n'
    printf '  source architecture: %s\n' "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}"
    printf '  provider: %s\n' "${ROSETTE_XENIA_PROVIDER_ROOT:-system-native}"
    printf '  SDL2 flags:\n%s\n' "${flags}"
    printf '  frameworks: Foundation AppKit CoreFoundation CoreServices Cocoa\n'
}

rosette_xenia_linker_emit_cmake() {
    local output="${1:?output path is required}"
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite an existing linker fragment: ${output}" >&2
        return 1
    }
    local pkg_config="${PKG_CONFIG:-pkg-config}"
    local cflags libs
    cflags="$("${pkg_config}" --cflags sdl2)"
    libs="$("${pkg_config}" --libs sdl2)"
    case "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}:${cflags} ${libs}" in
        x86_64:*\/opt\/homebrew*|arm64:*\/usr\/local\/x86brew*)
            echo "ERROR: refusing cross-architecture SDL2 linker flags" >&2
            return 1
            ;;
    esac
    cat > "${output}" <<EOF
# Generated by Rosette's Xenia script package.
set(ROSETTE_XENIA_SDL2_CFLAGS "${cflags}")
set(ROSETTE_XENIA_SDL2_LIBS "${libs}")
set(ROSETTE_XENIA_MACOS_FRAMEWORKS Foundation AppKit CoreFoundation CoreServices Cocoa)
set(ROSETTE_XENIA_DEPLOYMENT_TARGET "11.0")

function(rosette_xenia_apply_linker_contract target)
    target_compile_options(\${target} PRIVATE \${ROSETTE_XENIA_SDL2_CFLAGS})
    target_link_libraries(\${target} PRIVATE \${ROSETTE_XENIA_SDL2_LIBS})
    foreach(framework IN LISTS ROSETTE_XENIA_MACOS_FRAMEWORKS)
        target_link_libraries(\${target} PRIVATE "-framework" \${framework})
    endforeach()
    set_target_properties(\${target} PROPERTIES
        OSX_DEPLOYMENT_TARGET "\${ROSETTE_XENIA_DEPLOYMENT_TARGET}")
endfunction()
EOF
    printf 'rosette Xenia linker: emitted %s\n' "${output}"
}

rosette_xenia_linker_help() {
    cat <<'EOF'
Rosette Xenia linker adapter

  rosette-xenia-linker.sh --source-architecture x86_64 --print
  rosette-xenia-linker.sh --source-architecture x86_64 --emit-cmake path

The generated fragment is provider-specific and must be included by the
consumer's CMake configure step. This command does not configure or build.
EOF
}

source_image=""
source_architecture=""
print=0
emit_cmake=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-image)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-image requires a path" >&2; exit 2; }
            source_image="$2"
            shift 2
            ;;
        --source-architecture)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-architecture requires a value" >&2; exit 2; }
            source_architecture="$2"
            shift 2
            ;;
        --print) print=1; shift ;;
        --emit-cmake)
            [[ $# -ge 2 ]] || { echo "ERROR: --emit-cmake requires a path" >&2; exit 2; }
            emit_cmake="$2"
            shift 2
            ;;
        --help|-h) rosette_xenia_linker_help; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; rosette_xenia_linker_help >&2; exit 2 ;;
    esac
done

[[ -n "${source_image}" ]] && export ROSETTE_XENIA_SOURCE_IMAGE="${source_image}"
[[ -n "${source_architecture}" ]] && export ROSETTE_XENIA_SOURCE_ARCHITECTURE="${source_architecture}"
if [[ -n "${source_image}" ]]; then
    rosette_xenia_configure_environment "${source_image}"
else
    rosette_xenia_configure_environment
fi
rosette_xenia_verify_environment
[[ "${print}" == 1 ]] && rosette_xenia_linker_print
[[ -n "${emit_cmake}" ]] && rosette_xenia_linker_emit_cmake "${emit_cmake}"

