#!/usr/bin/env bash
# Rosette-owned source-aware toolchain configuration for Xenia.
#
# This is the replacement for the old build/setup wrappers' provider logic. It
# emits configuration and performs preflight checks; it intentionally does not
# invoke CMake, make, xb, or the Xenia executable.

set -euo pipefail

_rosette_xenia_toolchain_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_rosette_xenia_toolchain_root="$(cd "${_rosette_xenia_toolchain_dir}/../../.." && pwd)"
# shellcheck source=tools/xenia/scripts/rosette-xenia-environment.sh
source "${_rosette_xenia_toolchain_dir}/rosette-xenia-environment.sh"

rosette_xenia_toolchain_require_tools() {
    local tool
    for tool in clang clang++ cmake nasm pkg-config; do
        if ! command -v "${tool}" >/dev/null 2>&1; then
            echo "ERROR: Rosette Xenia toolchain is missing: ${tool}" >&2
            return 1
        fi
    done
}

rosette_xenia_toolchain_require_packages() {
    local package
    local missing=0
    for package in sdl2 gtk+-3.0 fontconfig; do
        if ! "${PKG_CONFIG:-pkg-config}" --exists "${package}"; then
            echo "ERROR: selected provider does not expose pkg-config package: ${package}" >&2
            missing=1
        fi
    done
    [[ "${missing}" == 0 ]] || return 1
}

rosette_xenia_toolchain_print() {
    printf 'Xenia source architecture: %s\n' "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}"
    printf 'Xenia library architecture: %s\n' "${ROSETTE_XENIA_LIBRARY_ARCHITECTURE}"
    printf 'Xenia provider: %s\n' "${ROSETTE_XENIA_PROVIDER_ROOT:-system-native}"
    printf 'Provider class: %s\n' "$(rosette_xenia_provider_kind)"
    printf 'C compiler: %s\n' "${CC}"
    printf 'C++ compiler: %s\n' "${CXX}"
    printf 'CMake architecture: %s\n' "${CMAKE_OSX_ARCHITECTURES}"
    printf 'CMake prefix path: %s\n' "${CMAKE_PREFIX_PATH:-}"
    printf 'Pkg-config path: %s\n' "${PKG_CONFIG_PATH:-}"
    printf 'C flags: %s\n' "${CPPFLAGS:-}"
    printf 'Linker flags: %s\n' "${LDFLAGS:-}"
}

rosette_xenia_toolchain_emit_cmake() {
    local output="${1:?output path is required}"
    [[ ! -e "${output}" ]] || {
        echo "ERROR: refusing to overwrite an existing CMake fragment: ${output}" >&2
        return 1
    }
    local prefix="${ROSETTE_XENIA_PROVIDER_ROOT:-}"
    local pkg_config_path="${PKG_CONFIG_PATH:-}"
    local cmake_prefix_path="${CMAKE_PREFIX_PATH:-}"
    cat > "${output}" <<EOF
# Generated by Rosette's Xenia script package.
# This file contains selected paths only; it does not install dependencies.
set(CMAKE_OSX_ARCHITECTURES "${CMAKE_OSX_ARCHITECTURES}" CACHE STRING "Rosette-selected source architecture")
set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "Rosette Xenia deployment target")
set(ROSETTE_XENIA_SOURCE_ARCHITECTURE "${ROSETTE_XENIA_SOURCE_ARCHITECTURE}")
set(ROSETTE_XENIA_LIBRARY_ARCHITECTURE "${ROSETTE_XENIA_LIBRARY_ARCHITECTURE}")
set(ROSETTE_XENIA_PROVIDER_ROOT "${prefix}")
set(CMAKE_PREFIX_PATH "${cmake_prefix_path}")
set(ENV{PKG_CONFIG_PATH} "${pkg_config_path}")
set(ENV{CC} "${CC}")
set(ENV{CXX} "${CXX}")
set(ENV{CPPFLAGS} "${CPPFLAGS:-}")
set(ENV{LDFLAGS} "${LDFLAGS:-}")
EOF
    printf 'rosette Xenia toolchain: emitted %s\n' "${output}"
}

rosette_xenia_toolchain_help() {
    cat <<'EOF'
Rosette Xenia toolchain adapter

  rosette-xenia-toolchain.sh --source-image title.exe --print
  rosette-xenia-toolchain.sh --source-architecture x86_64 --preflight
  rosette-xenia-toolchain.sh --source-architecture x86_64 --emit-cmake path

The adapter selects the library provider from source architecture and refuses
known cross-architecture paths. It never provisions packages or builds Xenia.
EOF
}

source_image=""
source_architecture=""
preflight=0
print=0
emit_cmake=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source-image)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-image requires a path" >&2; exit 2; }
            source_image="$2"
            shift 2
            ;;
        --source-architecture)
            [[ $# -ge 2 ]] || { echo "ERROR: --source-architecture requires a value" >&2; exit 2; }
            source_architecture="$2"
            shift 2
            ;;
        --preflight) preflight=1; shift ;;
        --print) print=1; shift ;;
        --emit-cmake)
            [[ $# -ge 2 ]] || { echo "ERROR: --emit-cmake requires a path" >&2; exit 2; }
            emit_cmake="$2"
            shift 2
            ;;
        --help|-h) rosette_xenia_toolchain_help; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; rosette_xenia_toolchain_help >&2; exit 2 ;;
    esac
done

[[ -n "${source_image}" ]] && export ROSETTE_XENIA_SOURCE_IMAGE="${source_image}"
[[ -n "${source_architecture}" ]] && export ROSETTE_XENIA_SOURCE_ARCHITECTURE="${source_architecture}"
if [[ -n "${source_image}" ]]; then
    rosette_xenia_configure_environment "${source_image}"
else
    rosette_xenia_configure_environment
fi
rosette_xenia_verify_environment
[[ "${preflight}" == 1 ]] && rosette_xenia_toolchain_require_tools && rosette_xenia_toolchain_require_packages
[[ "${print}" == 1 ]] && rosette_xenia_toolchain_print
[[ -n "${emit_cmake}" ]] && rosette_xenia_toolchain_emit_cmake "${emit_cmake}"

