//! Counting the kernel calls the guest title actually makes.
//!
//! Rosette can see every Win32 call Xenia makes, every Vulkan call it
//! forwards, every page it maps. It has never been able to see the one thing
//! that decides whether a picture exists: **what the translated PowerPC is
//! asking the emulated kernel for.**
//!
//! That gap is why the 2026-09-12 run could report fifteen ordered stages,
//! name `title_queried_video_mode` as the wall, and then say nothing further.
//! The stage's whole evidence was one entry count reading zero. A zero is not
//! a diagnosis - it is the absence of one - and the reader was left with "the
//! title has not asked about the display" and no way to find out what it had
//! asked about instead.
//!
//! Xenia satisfies each kernel import with a C++ function generated by
//! `DECLARE_XBOXKRNL_EXPORT`, named `<Export>_entry`, and the MinGW image
//! keeps all 692 of them in its COFF symbol table. Arming every one turns the
//! question into a list.
//!
//! ## Why a table and not a filter
//!
//! `process.zig` arms its twenty-two milestones behind a 64-bit Bloom filter,
//! which is exactly right for twenty-two addresses and useless for 692: the
//! filter saturates, every call passes it, and the cost moves from one bit
//! test to a linear scan of the armed set. That is the hot-path scan this
//! project has already paid for once.
//!
//! So: open addressing, a power-of-two slot count, and a load factor around a
//! third. A call that is not a shim - which is almost all of them - reads one
//! slot, compares one address to zero, and returns. A call that is a shim
//! finds it in one probe nearly always. Both are O(1) and neither degrades as
//! the run goes on.
//!
//! ## What an entry proves
//!
//! That the title asked. Nothing else. It does not prove Xenia's answer was
//! right, that the call returned, or that the title liked what it got. Those
//! are different questions and this module deliberately answers none of them.
//!
//! ## What a zero proves
//!
//! Less than it looks. A shim reads zero when the title never called it, and
//! also when the image does not contain the symbol - so `armed` is tracked
//! separately from `hits`, and a report that cannot tell the two apart is
//! required to say so.

const std = @import("std");
const shim_map = @import("xenia_kernel_shim_map");
const export_map = @import("xenia_kernel_export_map");

/// Slots in the open-addressed table.
///
/// The 2026-09-12 image has 694 trampolines and 692 `_entry` forwarders, and
/// both kinds are armed, so this is a load factor of 0.34: a
/// miss finds an empty slot on the first probe roughly two times in three,
/// and the longest probe chain stays short enough that the worst case is
/// still a handful of cache lines. Sized as a constant rather than from the
/// image because the table has to exist before anything is counted, and an
/// image with more shims than slots is reported as an overflow rather than
/// silently dropping the ones that did not fit.
pub const slot_count: usize = 4096;

comptime {
    // Open addressing needs a power of two for the mask, and needs to be
    // strictly larger than the set it holds or insertion loops forever.
    std.debug.assert(slot_count != 0 and slot_count & (slot_count - 1) == 0);
}

const slot_mask: u64 = slot_count - 1;

/// The most slots `arm` will ever fill.
///
/// Not a capacity limit for its own sake. Open addressing degrades by probe
/// length, and a table allowed to fill completely turns `note` - which is on
/// the interpreter's call path - from one probe into a scan of two thousand
/// slots that gets slower the longer the run goes on. That is precisely the
/// hot-path scan this project has already paid for once. Three quarters keeps
/// the worst case short; a build with more shims than this reports an
/// overflow, which is a fact about the image and reads like one.
const slot_high_water: u32 = slot_count * 3 / 4;

/// One armed export shim.
pub const Slot = struct {
    /// The resolved entry address, or zero for an empty slot.
    address: u64 = 0,
    /// The console export name, borrowed from the PE image's string table.
    /// The image outlives the state in every caller, which is the only reason
    /// this can be a slice rather than a copy.
    export_name: []const u8 = &.{},
    hits: u64 = 0,
    first_step: u64 = 0,
    last_step: u64 = 0,
    module: shim_map.Module = .xboxkrnl,
    /// Whether this is the registered trampoline or the `_entry` forwarder
    /// it calls. Both are armed; only the trampoline's count is the title's
    /// act, because the forwarder can be inlined into it.
    kind: shim_map.EntryKind = .trampoline,
    subsystem: shim_map.Subsystem = .other,
    /// The boot phase this export places the title in, when it is a marker.
    phase: ?shim_map.BootPhase = null,
};

/// The armed set and what it has seen.
pub const Census = struct {
    /// Heap-allocated, because a hundred kilobytes by value inside `ElfState`
    /// would be a hundred kilobytes of stack in the runner that builds it.
    slots: []Slot = &.{},

    /// The address range the armed shims occupy. Every call the interpreter
    /// makes is tested against this before it is hashed, and a call outside
    /// the range - into the heap, into Xenia's JIT cache at 0xA0000000, into
    /// a thunk page - is rejected by two comparisons.
    low: u64 = std.math.maxInt(u64),
    high: u64 = 0,

    armed: u32 = 0,
    /// Of those, the ones that are registered trampolines. The denominator
    /// for every "did the title call this" question, because an export with
    /// no armed trampoline cannot be observed however many `_entry` symbols
    /// the image happens to carry.
    armed_trampolines: u32 = 0,
    /// Shims the image named that did not fit. Reported, never hidden: a
    /// census missing an unknown number of names is not a census.
    overflowed: u32 = 0,
    /// Symbols offered to `arm` that were not shims. Expected to be large -
    /// the caller offers every symbol in the image - and useful only as proof
    /// that the recogniser ran at all.
    rejected: u64 = 0,

    /// Distinct exports whose *trampoline* was entered at least once.
    distinct_entered: u32 = 0,
    /// Every trampoline entry, summed. This is the number of kernel calls the
    /// title made: one guest import call reaches exactly one trampoline.
    total_calls: u64 = 0,
    /// Entries into `_entry` forwarders, counted apart so one guest call is
    /// never counted twice.
    ///
    /// A forwarder is called by its trampoline, so in a build that kept them
    /// out of line this tracks `total_calls`. Where it is far lower, the
    /// compiler inlined the forwarders - which is the fact that would have
    /// made an `_entry`-only census read zero for a title calling constantly.
    forwarder_calls: u64 = 0,
    /// The furthest boot phase any entered export places the title in.
    furthest_phase: shim_map.BootPhase = .no_kernel_contact,
    /// The slot of the most recent shim entry, plus one. Zero means none.
    last_slot: u32 = 0,
    last_step: u64 = 0,
    /// Entries reached by a tail jump rather than a call.
    ///
    /// Which instruction a translator uses to reach its handler is a property
    /// of the translator, not of the title, and the two are indistinguishable
    /// in the count. Separating them means a census reading zero can say
    /// whether it was looking at the wrong instruction - which is the one
    /// failure mode that would make every number here silently wrong.
    tail_jump_entries: u64 = 0,

    pub fn deinit(self: *Census, allocator: std.mem.Allocator) void {
        if (self.slots.len != 0) allocator.free(self.slots);
        self.slots = &.{};
    }

    /// Allocate the table. Idempotent, so a caller can arm without a separate
    /// set-up step and a state that never arms anything never allocates.
    fn ensure(self: *Census, allocator: std.mem.Allocator) bool {
        if (self.slots.len != 0) return true;
        const slots = allocator.alloc(Slot, slot_count) catch return false;
        for (slots) |*slot| slot.* = .{};
        self.slots = slots;
        return true;
    }

    /// Fibonacci hashing: one multiply and a shift, which spreads the low
    /// bits of an address that a mask alone would throw away. Entry points
    /// are 16-byte aligned in this image, so masking the raw address would
    /// leave four bits of every index constant.
    fn indexOf(address: u64) usize {
        const mixed = address *% 0x9E3779B97F4A7C15;
        return @intCast((mixed >> 32) & slot_mask);
    }

    /// Arm `mangled` at `address`, if it is a kernel export shim.
    ///
    /// Returns true when a slot was taken. A symbol that is not a shim is
    /// counted in `rejected` and is not an error: the caller offers the whole
    /// symbol table because filtering it here is the only place that knows
    /// the rule.
    pub fn arm(
        self: *Census,
        allocator: std.mem.Allocator,
        mangled: []const u8,
        address: u64,
    ) bool {
        const shim = shim_map.parseExportEntryPoint(mangled) orelse {
            self.rejected +|= 1;
            return false;
        };
        if (address == 0) {
            self.rejected +|= 1;
            return false;
        }
        if (!self.ensure(allocator)) {
            self.overflowed +|= 1;
            return false;
        }
        if (self.armed >= slot_high_water) {
            // Refused rather than squeezed in: one more entry costs every
            // future lookup, and a census that is 99% complete and slow is
            // worse than one that says it is incomplete.
            self.overflowed +|= 1;
            return false;
        }
        var index = indexOf(address);
        var probes: usize = 0;
        while (probes < slot_count) : (probes += 1) {
            const slot = &self.slots[index];
            if (slot.address == address) return true; // already armed
            if (slot.address == 0) {
                slot.* = .{
                    .address = address,
                    .export_name = shim.export_name,
                    .module = shim.module,
                    .kind = shim.kind,
                    .subsystem = shim.subsystem,
                    .phase = shim_map.phaseOf(shim.export_name),
                };
                self.armed += 1;
                if (shim.kind == .trampoline) self.armed_trampolines += 1;
                if (address < self.low) self.low = address;
                if (address > self.high) self.high = address;
                return true;
            }
            index = (index + 1) & @as(usize, slot_mask);
        }
        self.overflowed +|= 1;
        return false;
    }

    /// Record a call into `address`, if it is an armed shim.
    ///
    /// On the interpreter's call path. Returns the slot index plus one when
    /// it was a shim, so the caller can attribute it to a thread without a
    /// second lookup, and zero otherwise.
    pub fn note(self: *Census, address: u64, step: u64) u32 {
        if (self.slots.len == 0) return 0;
        if (address < self.low or address > self.high) return 0;
        var index = indexOf(address);
        var probes: usize = 0;
        while (probes < slot_count) : (probes += 1) {
            const slot = &self.slots[index];
            if (slot.address == 0) return 0;
            if (slot.address == address) {
                const first = slot.hits == 0;
                slot.hits +|= 1;
                slot.last_step = step;
                if (slot.kind == .shim) {
                    // The forwarder is reached from its own trampoline, never
                    // from the guest. Counting it in the totals would report
                    // two kernel calls for one.
                    self.forwarder_calls +|= 1;
                    return @intCast(index + 1);
                }
                if (first) {
                    slot.first_step = step;
                    self.distinct_entered += 1;
                    if (slot.phase) |phase| {
                        if (@intFromEnum(phase) > @intFromEnum(self.furthest_phase)) {
                            self.furthest_phase = phase;
                        }
                    }
                }
                self.total_calls +|= 1;
                self.last_slot = @intCast(index + 1);
                self.last_step = step;
                return @intCast(index + 1);
            }
            index = (index + 1) & @as(usize, slot_mask);
        }
        return 0;
    }

    /// The armed slot for an export name, or null when the image did not name
    /// it. Linear: called a handful of times at report time and never on the
    /// interpreter's path.
    pub fn findExport(self: *const Census, export_name: []const u8) ?*const Slot {
        return self.findExportOfKind(export_name, .trampoline) orelse
            self.findExportOfKind(export_name, .shim);
    }

    /// One export's slot of a given kind, or null.
    ///
    /// `findExport` prefers the trampoline because that is the witness whose
    /// count is the title's act; the forwarder is a fallback for an image
    /// with one and not the other, and a caller comparing the two asks for
    /// each by name.
    pub fn findExportOfKind(
        self: *const Census,
        export_name: []const u8,
        kind: shim_map.EntryKind,
    ) ?*const Slot {
        for (self.slots) |*slot| {
            if (slot.address == 0 or slot.kind != kind) continue;
            if (std.mem.eql(u8, slot.export_name, export_name)) return slot;
        }
        return null;
    }

    /// Entries into one export, or zero when it was never armed.
    ///
    /// Callers must not read a zero from this as "the title did not call it"
    /// without also checking `isArmed` - an unarmed export reads zero for a
    /// reason that has nothing to do with the title.
    pub fn hitsFor(self: *const Census, export_name: []const u8) u64 {
        const slot = self.findExport(export_name) orelse return 0;
        return slot.hits;
    }

    pub fn isArmed(self: *const Census, export_name: []const u8) bool {
        return self.findExport(export_name) != null;
    }

    /// Total entries across every export whose name this milestone's witness
    /// table names. Zero when the milestone has no shim witness.
    pub fn witnessHitsFor(self: *const Census, milestone: []const u8) u64 {
        if (milestone.len == 0) return 0;
        var total: u64 = 0;
        for (shim_map.witnesses) |witness| {
            if (!std.mem.eql(u8, witness.milestone, milestone)) continue;
            total +|= self.hitsFor(witness.export_name);
        }
        return total;
    }

    /// Whether at least one of a milestone's shim witnesses is armed, so a
    /// report can separate "the title did not call it" from "this image does
    /// not let us see whether it did".
    pub fn witnessArmedFor(self: *const Census, milestone: []const u8) bool {
        if (milestone.len == 0) return false;
        for (shim_map.witnesses) |witness| {
            if (!std.mem.eql(u8, witness.milestone, milestone)) continue;
            if (self.isArmed(witness.export_name)) return true;
        }
        return false;
    }

    /// Calls and distinct exports per subsystem.
    pub fn subsystemTotals(self: *const Census) [shim_map.subsystem_count]Totals {
        var totals = [_]Totals{.{}} ** shim_map.subsystem_count;
        for (self.slots) |slot| {
            // Trampolines only: one row per export, and the forwarder is the
            // same export seen from the other side.
            if (slot.address == 0 or slot.kind != .trampoline) continue;
            const index = @intFromEnum(slot.subsystem);
            totals[index].armed += 1;
            if (slot.hits == 0) continue;
            totals[index].distinct += 1;
            totals[index].calls +|= slot.hits;
        }
        return totals;
    }

    pub const Totals = struct {
        armed: u32 = 0,
        distinct: u32 = 0,
        calls: u64 = 0,
    };

    /// How many of a phase's markers the title has actually called, out of
    /// how many this image can see. Two different denominators matter: a
    /// marker the image never armed cannot be called, and reporting it as
    /// uncalled would blame the title for Xenia's build.
    pub fn phaseProgress(self: *const Census, phase: shim_map.BootPhase) PhaseProgress {
        var progress = PhaseProgress{};
        for (shim_map.phase_markers) |marker| {
            if (marker.phase != phase) continue;
            progress.declared += 1;
            const slot = self.findExport(marker.export_name) orelse continue;
            progress.armed += 1;
            if (slot.hits != 0) progress.called += 1;
        }
        return progress;
    }

    pub const PhaseProgress = struct {
        declared: u32 = 0,
        armed: u32 = 0,
        called: u32 = 0,
    };

    /// The slot of the nth-most-recently first-entered export, for a report
    /// that prints the tail of the boot narrative.
    ///
    /// Selection rather than a sort, because the table is not the caller's to
    /// reorder and a run has at most a few hundred entered slots.
    pub fn nthLatestFirstEntry(self: *const Census, n: usize) ?*const Slot {
        var remaining = n;
        var boundary: u64 = std.math.maxInt(u64);
        while (true) {
            var best: ?*const Slot = null;
            for (self.slots) |*slot| {
                if (slot.address == 0 or slot.hits == 0 or slot.kind != .trampoline) continue;
                if (slot.first_step >= boundary) continue;
                if (best == null or slot.first_step > best.?.first_step) best = slot;
            }
            const found = best orelse return null;
            if (remaining == 0) return found;
            remaining -= 1;
            boundary = found.first_step;
        }
    }

    /// The export entered most often, which is usually a spin.
    pub fn busiest(self: *const Census) ?*const Slot {
        var best: ?*const Slot = null;
        for (self.slots) |*slot| {
            if (slot.address == 0 or slot.hits == 0 or slot.kind != .trampoline) continue;
            if (best == null or slot.hits > best.?.hits) best = slot;
        }
        return best;
    }

    /// Fill `out` with the busiest retained `_entry` bodies, in descending
    /// hit order.  Forwarder entries are deliberately kept separate from
    /// `busiest`: they are an implementation-layout cost, not another count
    /// of what the title asked the kernel to do.  Selection is bounded by the
    /// fixed census table and happens only while producing the exit report.
    pub fn topForwarders(self: *const Census, out: []?*const Slot) usize {
        for (out) |*entry| entry.* = null;
        var filled: usize = 0;
        for (self.slots) |*slot| {
            if (slot.address == 0 or slot.hits == 0 or slot.kind != .shim) continue;
            var position: usize = 0;
            while (position < filled) : (position += 1) {
                const current = out[position].?;
                if (slot.hits > current.hits or
                    (slot.hits == current.hits and slot.address < current.address)) break;
            }
            if (position >= out.len) continue;
            if (filled < out.len) filled += 1;
            var move = filled;
            while (move > position + 1) : (move -= 1) {
                out[move - 1] = out[move - 2];
            }
            out[position] = slot;
        }
        return filled;
    }

    pub fn slotAt(self: *const Census, index_plus_one: u32) ?*const Slot {
        if (index_plus_one == 0) return null;
        const index: usize = @as(usize, index_plus_one) - 1;
        if (index >= self.slots.len) return null;
        if (self.slots[index].address == 0) return null;
        return &self.slots[index];
    }
};

/// What the console publishes that this Xenia build does not implement.
///
/// A purely static join between `kernel-export-map`'s console tables and the
/// shims this image armed. It says nothing about the run - but it is the
/// answer to "what is missing", and until now the answer did not exist in any
/// form. The console publishes 73 `Vd*` exports and the 2026-09-12 build
/// implements 23 of them; a title that calls one of the other 50 reaches
/// Xenia's unimplemented-export path, and no counter anywhere said so.
pub const CoverageRow = struct {
    module: shim_map.Module,
    subsystem: shim_map.Subsystem,
    published: u32 = 0,
    implemented: u32 = 0,
};

/// Console exports, Xenia shims, and the gap, for one module and subsystem.
pub fn coverageFor(
    census: *const Census,
    module: shim_map.Module,
    subsystem: shim_map.Subsystem,
) CoverageRow {
    var row = CoverageRow{ .module = module, .subsystem = subsystem };
    const table = switch (module) {
        .xboxkrnl => export_map.xboxkrnl_exports[0..],
        .xam => export_map.xam_exports[0..],
        .xbdm => export_map.xbdm_exports[0..],
    };
    for (table) |entry| {
        if (shim_map.subsystemOf(module, entry.name) != subsystem) continue;
        row.published += 1;
        // Implemented means a registered trampoline exists for it. An
        // `_entry` forwarder alone is not something the guest can reach.
        if (census.findExportOfKind(entry.name, .trampoline) != null) row.implemented += 1;
    }
    return row;
}

/// The whole of one module, without walking it once per subsystem.
///
/// `coverageFor` reads the console table for every subsystem it is asked
/// about; asking it twenty times to build a total would read the same 2913
/// rows twenty times over for a number a single pass produces.
pub fn coverageForModule(census: *const Census, module: shim_map.Module) CoverageRow {
    var row = CoverageRow{ .module = module, .subsystem = .other };
    const table = switch (module) {
        .xboxkrnl => export_map.xboxkrnl_exports[0..],
        .xam => export_map.xam_exports[0..],
        .xbdm => export_map.xbdm_exports[0..],
    };
    for (table) |entry| {
        row.published += 1;
        if (census.findExportOfKind(entry.name, .trampoline) != null) row.implemented += 1;
    }
    return row;
}

/// Console exports in a subsystem that this build does not implement, written
/// into `out` and returned as the prefix that was filled.
///
/// Bounded by the caller's buffer rather than allocating: a report prints a
/// handful of names and a full list of 2221 would bury the finding.
pub fn missingExports(
    census: *const Census,
    module: shim_map.Module,
    subsystem: shim_map.Subsystem,
    out: [][]const u8,
) [][]const u8 {
    if (out.len == 0) return out[0..0];
    const table = switch (module) {
        .xboxkrnl => export_map.xboxkrnl_exports[0..],
        .xam => export_map.xam_exports[0..],
        .xbdm => export_map.xbdm_exports[0..],
    };
    var filled: usize = 0;
    for (table) |entry| {
        if (filled == out.len) break;
        if (shim_map.subsystemOf(module, entry.name) != subsystem) continue;
        if (census.findExportOfKind(entry.name, .trampoline) != null) continue;
        out[filled] = entry.name;
        filled += 1;
    }
    return out[0..filled];
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

// The registered trampolines, spelled exactly as Xenia's macro instantiates
// them. Arming an `_entry` forwarder instead would be arming the function the
// trampoline calls, which is the mistake this module exists to avoid.
const TRAMPOLINE_VIDEO_MODE = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt458EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl22VdQueryVideoMode_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
const TRAMPOLINE_REAL_VIDEO_MODE = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt459EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl26VdQueryRealVideoMode_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
const TRAMPOLINE_SWAP = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt444EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl12VdSwap_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
const TRAMPOLINE_READ_FILE = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt219EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl16NtReadFile_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
const TRAMPOLINE_MODULE_HANDLE = "_ZZN2xe6kernel4shim21ExportRegistrerHelperILNS1_14KernelModuleIdE0ELt405EvJEE14RegisterExportIXadL_ZNS0_8xboxkrnl24XexGetModuleHandle_entryEvEELj1EEEPNS_3cpu6ExportEPKcEN1X10TrampolineEPNSC_3ppc12PPCContext_sE";
const ENTRY_VIDEO_MODE = "_ZN2xe6kernel8xboxkrnl22VdQueryVideoMode_entryEv";
const ENTRY_SWAP = "_ZN2xe6kernel8xboxkrnl12VdSwap_entryEv";

fn armVideoMode(census: *Census, allocator: std.mem.Allocator, address: u64) void {
    _ = census.arm(allocator, TRAMPOLINE_VIDEO_MODE, address);
}

test "a trampoline is armed once and counted from the call path" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    // Arming twice must not take two slots; the caller offers the whole
    // symbol table and a duplicate in it would inflate the census.
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    try testing.expectEqual(@as(u32, 1), census.armed);
    try testing.expectEqual(@as(u32, 1), census.armed_trampolines);
    try testing.expect(census.isArmed("VdQueryVideoMode"));

    try testing.expectEqual(@as(u32, 0), census.note(0x1409cb008, 10));
    try testing.expectEqual(@as(u64, 0), census.total_calls);

    const slot = census.note(0x1409cb000, 4242);
    try testing.expect(slot != 0);
    try testing.expectEqual(@as(u64, 1), census.total_calls);
    try testing.expectEqual(@as(u32, 1), census.distinct_entered);
    try testing.expectEqual(@as(u64, 1), census.hitsFor("VdQueryVideoMode"));
    try testing.expectEqual(@as(u64, 4242), census.findExport("VdQueryVideoMode").?.first_step);

    _ = census.note(0x1409cb000, 9000);
    try testing.expectEqual(@as(u64, 2), census.hitsFor("VdQueryVideoMode"));
    try testing.expectEqual(@as(u32, 1), census.distinct_entered);
    try testing.expectEqual(@as(u64, 4242), census.findExport("VdQueryVideoMode").?.first_step);
    try testing.expectEqual(@as(u64, 9000), census.findExport("VdQueryVideoMode").?.last_step);
    try testing.expectEqualStrings("VdQueryVideoMode", census.slotAt(census.last_slot).?.export_name);
}

test "one guest call is never counted twice when both symbols are armed" {
    // The trampoline calls the forwarder, so a build that kept the forwarder
    // out of line produces two entries for one kernel call. Only the
    // trampoline's is the title's act.
    var census = Census{};
    defer census.deinit(testing.allocator);
    _ = census.arm(testing.allocator, TRAMPOLINE_VIDEO_MODE, 0x1409cb000);
    _ = census.arm(testing.allocator, ENTRY_VIDEO_MODE, 0x1409caf00);
    try testing.expectEqual(@as(u32, 2), census.armed);
    try testing.expectEqual(@as(u32, 1), census.armed_trampolines);

    _ = census.note(0x1409cb000, 100); // guest -> trampoline
    _ = census.note(0x1409caf00, 101); // trampoline -> forwarder

    try testing.expectEqual(@as(u64, 1), census.total_calls);
    try testing.expectEqual(@as(u64, 1), census.forwarder_calls);
    try testing.expectEqual(@as(u32, 1), census.distinct_entered);
    // The public count is the trampoline's, and the forwarder is reachable
    // only by asking for it.
    try testing.expectEqual(@as(u64, 1), census.hitsFor("VdQueryVideoMode"));
    try testing.expectEqual(
        shim_map.EntryKind.trampoline,
        census.findExport("VdQueryVideoMode").?.kind,
    );
    try testing.expectEqual(
        @as(u64, 1),
        census.findExportOfKind("VdQueryVideoMode", .shim).?.hits,
    );
}

test "top forwarders expose implementation cost separately from title calls" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    _ = census.arm(testing.allocator, TRAMPOLINE_VIDEO_MODE, 0x1409cb000);
    _ = census.arm(testing.allocator, ENTRY_VIDEO_MODE, 0x1409caf00);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.arm(testing.allocator, ENTRY_SWAP, 0x1409cae00);

    _ = census.note(0x1409caf00, 10);
    _ = census.note(0x1409caf00, 11);
    _ = census.note(0x1409caf00, 12);
    _ = census.note(0x1409cae00, 13);

    var top: [2]?*const Slot = .{ null, null };
    try testing.expectEqual(@as(usize, 2), census.topForwarders(&top));
    try testing.expectEqualStrings("VdQueryVideoMode", top[0].?.export_name);
    try testing.expectEqual(@as(u64, 3), top[0].?.hits);
    try testing.expectEqualStrings("VdSwap", top[1].?.export_name);
    try testing.expectEqual(@as(u64, 1), top[1].?.hits);
    try testing.expectEqual(@as(u64, 0), census.total_calls);
}

test "an inlined forwarder leaves the trampoline count intact" {
    // The 2026-09-12 image has 694 trampolines and 692 forwarders, so two
    // exports already look like this. A census that read the forwarder would
    // report them as never called whatever the title did.
    var census = Census{};
    defer census.deinit(testing.allocator);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.note(0x1409cc000, 7);
    try testing.expectEqual(@as(u64, 1), census.hitsFor("VdSwap"));
    try testing.expectEqual(@as(u64, 0), census.forwarder_calls);
    try testing.expectEqual(@as(?*const Slot, null), census.findExportOfKind("VdSwap", .shim));
}

test "a symbol that is neither entry point never takes a slot" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    // The implementation, which the milestone table arms. Counting it here
    // would report Xenia's own internal call as a call the title made.
    try testing.expect(!census.arm(
        testing.allocator,
        "_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb",
        0x1409caf00,
    ));
    try testing.expect(!census.arm(testing.allocator, "_ZN2xe3gpu16CommandProcessor10InitializeEv", 0x1401c7e30));
    try testing.expectEqual(@as(u32, 0), census.armed);
    try testing.expectEqual(@as(u64, 2), census.rejected);
    // Nothing allocated, so a run whose image has no exports pays nothing.
    try testing.expectEqual(@as(usize, 0), census.slots.len);
    try testing.expectEqual(@as(u32, 0), census.note(0x1409caf00, 1));
}

test "an unarmed export reads zero, and the report can tell that from a title that did not call" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    try testing.expectEqual(@as(u64, 0), census.hitsFor("VdSwap"));
    try testing.expect(!census.isArmed("VdSwap"));
    try testing.expect(census.isArmed("VdQueryVideoMode"));
    try testing.expectEqual(@as(u64, 0), census.hitsFor("VdQueryVideoMode"));
}

test "the wall's stage reads its shim witness, not only its implementation" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    const video_mode = "_ZN2xe6kernel8xboxkrnl16VdQueryVideoModeEPNS0_12X_VIDEO_MODEEb";
    try testing.expect(!census.witnessArmedFor(video_mode));

    armVideoMode(&census, testing.allocator, 0x1409cb000);
    try testing.expect(census.witnessArmedFor(video_mode));
    try testing.expectEqual(@as(u64, 0), census.witnessHitsFor(video_mode));

    _ = census.note(0x1409cb000, 100);
    _ = census.note(0x1409cb000, 200);
    try testing.expectEqual(@as(u64, 2), census.witnessHitsFor(video_mode));

    // Both of the milestone's witnesses are summed: a title that calls
    // VdQueryRealVideoMode has asked about the display just as surely.
    _ = census.arm(testing.allocator, TRAMPOLINE_REAL_VIDEO_MODE, 0x1409cb100);
    _ = census.note(0x1409cb100, 300);
    try testing.expectEqual(@as(u64, 3), census.witnessHitsFor(video_mode));
    try testing.expectEqual(@as(u64, 0), census.witnessHitsFor(""));
}

test "the boot phase is the furthest one any call reached, never the latest" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    try testing.expectEqual(shim_map.BootPhase.no_kernel_contact, census.furthest_phase);

    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.arm(testing.allocator, TRAMPOLINE_MODULE_HANDLE, 0x1409cd000);
    _ = census.note(0x1409cc000, 10);
    try testing.expectEqual(shim_map.BootPhase.rendering, census.furthest_phase);
    // A later call in an earlier phase must not move the answer backwards:
    // a title in its render loop still allocates and still loads files.
    _ = census.note(0x1409cd000, 20);
    try testing.expectEqual(shim_map.BootPhase.rendering, census.furthest_phase);

    const progress = census.phaseProgress(.rendering);
    try testing.expectEqual(@as(u32, 1), progress.armed);
    try testing.expectEqual(@as(u32, 1), progress.called);
    // Declared counts every marker the map names, armed only the ones this
    // image has. The gap is Xenia's build, not the title's progress.
    try testing.expect(progress.declared >= progress.armed);
}

test "subsystem totals separate armed from called" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.arm(testing.allocator, TRAMPOLINE_READ_FILE, 0x1409ce000);
    // A forwarder must not add a second row for an export already counted.
    _ = census.arm(testing.allocator, ENTRY_SWAP, 0x1409cc900);
    _ = census.note(0x1409cb000, 1);
    _ = census.note(0x1409cb000, 2);

    const totals = census.subsystemTotals();
    const video = totals[@intFromEnum(shim_map.Subsystem.video)];
    try testing.expectEqual(@as(u32, 2), video.armed);
    try testing.expectEqual(@as(u32, 1), video.distinct);
    try testing.expectEqual(@as(u64, 2), video.calls);

    const native = totals[@intFromEnum(shim_map.Subsystem.native)];
    try testing.expectEqual(@as(u32, 1), native.armed);
    try testing.expectEqual(@as(u32, 0), native.distinct);
    try testing.expectEqual(@as(u64, 0), native.calls);

    try testing.expectEqualStrings("VdQueryVideoMode", census.busiest().?.export_name);
}

test "the boot narrative is ordered by first entry, newest first" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.arm(testing.allocator, TRAMPOLINE_READ_FILE, 0x1409ce000);
    _ = census.note(0x1409ce000, 100);
    _ = census.note(0x1409cb000, 200);
    _ = census.note(0x1409cc000, 300);
    // A later call into an earlier export must not reorder the narrative;
    // first entry is what places a title in its own boot, not last.
    _ = census.note(0x1409ce000, 400);

    try testing.expectEqualStrings("VdSwap", census.nthLatestFirstEntry(0).?.export_name);
    try testing.expectEqualStrings("VdQueryVideoMode", census.nthLatestFirstEntry(1).?.export_name);
    try testing.expectEqualStrings("NtReadFile", census.nthLatestFirstEntry(2).?.export_name);
    try testing.expectEqual(@as(?*const Slot, null), census.nthLatestFirstEntry(3));
}

test "the static gap between what the console publishes and what this build serves" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);

    const row = coverageFor(&census, .xboxkrnl, .video);
    // The console's own table, which is fixed and large; this build's
    // trampolines, which are few. The gap is the point of the row.
    try testing.expect(row.published > 60);
    try testing.expectEqual(@as(u32, 2), row.implemented);

    var buffer: [4][]const u8 = undefined;
    const missing = missingExports(&census, .xboxkrnl, .video, &buffer);
    try testing.expectEqual(@as(usize, 4), missing.len);
    for (missing) |name| {
        try testing.expect(std.mem.startsWith(u8, name, "Vd"));
        try testing.expect(!census.isArmed(name));
    }
    // A zero-length buffer must not write anywhere.
    var none: [0][]const u8 = undefined;
    try testing.expectEqual(@as(usize, 0), missingExports(&census, .xboxkrnl, .video, &none).len);
}

test "an empty census answers every question without allocating" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    try testing.expectEqual(@as(u32, 0), census.note(0x140000000, 1));
    try testing.expectEqual(@as(?*const Slot, null), census.busiest());
    try testing.expectEqual(@as(?*const Slot, null), census.nthLatestFirstEntry(0));
    try testing.expectEqual(@as(?*const Slot, null), census.slotAt(0));
    try testing.expectEqual(@as(?*const Slot, null), census.slotAt(9999));
    try testing.expect(!census.isArmed("VdSwap"));
    const totals = census.subsystemTotals();
    for (totals) |total| try testing.expectEqual(@as(u32, 0), total.armed);
}

test "the table survives more distinct addresses than the image has entry points" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    // Both kinds for every export in the 2026-09-12 image, and then some.
    var index: u64 = 0;
    while (index < 1400) : (index += 1) {
        _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x140000000 + index * 16);
    }
    try testing.expectEqual(@as(u32, 1400), census.armed);
    try testing.expectEqual(@as(u32, 0), census.overflowed);
    // And every one is findable, which a probe chain that wrapped wrongly
    // would break silently.
    index = 0;
    while (index < 1400) : (index += 1) {
        try testing.expect(census.note(0x140000000 + index * 16, index + 1) != 0);
    }
    try testing.expectEqual(@as(u32, 1400), census.distinct_entered);
}

test "a module's whole coverage is the sum of its subsystems" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    armVideoMode(&census, testing.allocator, 0x1409cb000);
    _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x1409cc000);
    _ = census.arm(testing.allocator, TRAMPOLINE_READ_FILE, 0x1409ce000);

    const whole = coverageForModule(&census, .xboxkrnl);
    var summed = CoverageRow{ .module = .xboxkrnl, .subsystem = .other };
    inline for (@typeInfo(shim_map.Subsystem).@"enum".fields) |field| {
        const row = coverageFor(&census, .xboxkrnl, @enumFromInt(field.value));
        summed.published += row.published;
        summed.implemented += row.implemented;
    }
    // A classification that dropped a name, or counted one twice, shows up
    // here and nowhere else.
    try testing.expectEqual(whole.published, summed.published);
    try testing.expectEqual(whole.implemented, summed.implemented);
    try testing.expectEqual(@as(u32, 3), whole.implemented);
    try testing.expect(whole.published > 900);
}

test "the table refuses to fill, because a full one turns the call path into a scan" {
    var census = Census{};
    defer census.deinit(testing.allocator);
    var index: u64 = 0;
    while (index < slot_count + 64) : (index += 1) {
        _ = census.arm(testing.allocator, TRAMPOLINE_SWAP, 0x140000000 + index * 16);
    }
    try testing.expectEqual(slot_high_water, census.armed);
    try testing.expect(census.overflowed != 0);
    // Every armed address is still found in a short chain, and a miss still
    // terminates on an empty slot rather than walking the whole table.
    try testing.expect(census.note(0x140000000, 1) != 0);
    try testing.expectEqual(@as(u32, 0), census.note(0x140000008, 2));
}
