const std = @import("std");
const cpu_state = @import("cpu_state.zig");
const flags = @import("flags.zig");
pub const capabilities = @import("capabilities.zig");

pub const OperandSize = flags.OperandSize;
pub const Condition = flags.Condition;
pub const RegId = cpu_state.RegId;
pub const Regs = cpu_state.Regs;

pub const RFL_CF = flags.RFL_CF;
pub const RFL_ZF = flags.RFL_ZF;
pub const RFL_SF = flags.RFL_SF;
pub const RFL_OF = flags.RFL_OF;

pub const applySub = flags.applySub;
pub const applyAdd = flags.applyAdd;
pub const applyIncDec = flags.applyIncDec;
pub const applyLogic = flags.applyLogic;
pub const evalCond = flags.evalCond;
pub const regVal = cpu_state.regVal;
pub const setReg = cpu_state.setReg;

pub const Op = enum(u16) {
    invalid,
    nop,
    // mov
    mov_mem8_reg8,
    mov_mem16_reg16,
    mov_mem32_reg32,
    mov_mem64_reg64,
    mov_reg8_mem8,
    mov_reg16_mem16,
    mov_reg32_mem32,
    mov_reg64_mem64,
    mov_reg_imm,
    mov_mem8_imm8,
    mov_mem16_imm16,
    mov_mem32_imm32,
    mov_mem64_imm32,
    mov_reg8_reg8,
    mov_reg16_reg16,
    mov_reg32_reg32,
    mov_reg64_reg64,
    add_accum_imm,
    or_accum_imm,
    adc_accum_imm,
    sbb_accum_imm,
    and_accum_imm,
    sub_accum_imm,
    xor_accum_imm,
    cmp_accum_imm,
    // add (reg, r/m) d=1
    add_reg8_mem8,
    add_reg16_mem16,
    add_reg32_mem32,
    add_reg64_mem64,
    // add (r/m, reg) d=0
    add_mem8_reg8,
    add_mem16_reg16,
    add_mem32_reg32,
    add_mem64_reg64,
    // add reg, reg
    add_reg8_reg8,
    add_reg16_reg16,
    add_reg32_reg32,
    add_reg64_reg64,
    add_reg8_imm8,
    add_reg16_imm8,
    add_reg32_imm8,
    add_reg64_imm8,
    adc_reg8_imm8,
    adc_reg16_imm8,
    adc_reg32_imm8,
    adc_reg64_imm8,
    sbb_reg8_imm8,
    add_reg16_imm32,
    add_reg32_imm32,
    add_reg64_imm32,
    add_mem8_imm8,
    add_mem16_imm8,
    add_mem32_imm8,
    add_mem64_imm8,
    adc_reg8_mem8,
    sbb_reg8_mem8,
    // sub (reg, r/m) d=1
    sub_reg8_mem8,
    sub_reg16_mem16,
    sub_reg32_mem32,
    sub_reg64_mem64,
    // sub (r/m, reg) d=0
    sub_mem8_reg8,
    sub_mem16_reg16,
    sub_mem32_reg32,
    sub_mem64_reg64,
    // sub (reg, reg) mod=3
    sub_reg8_reg8,
    sub_reg16_reg16,
    sub_reg32_reg32,
    sub_reg64_reg64,
    // sub r/m, imm8 (80 /5)
    sub_mem8_imm8,
    sub_reg8_imm8,
    sub_reg16_imm8,
    sub_reg32_imm8,
    sub_reg64_imm8,
    sub_reg16_imm32,
    sub_reg32_imm32,
    sub_reg64_imm32,
    sbb_reg8_reg8,
    sbb_reg16_reg16,
    sbb_reg32_reg32,
    sbb_reg64_reg64,
    // logical and/xor
    and_reg8_reg8,
    and_reg16_reg16,
    and_reg32_reg32,
    and_reg64_reg64,
    and_reg8_mem8,
    and_reg16_mem16,
    and_reg32_mem32,
    and_reg64_mem64,
    and_mem8_reg8,
    and_mem16_reg16,
    and_mem32_reg32,
    and_mem64_reg64,
    and_reg8_imm8,
    and_reg16_imm8,
    and_reg32_imm8,
    and_reg64_imm8,
    and_reg16_imm32,
    and_reg32_imm32,
    and_reg64_imm32,
    or_reg8_reg8,
    or_reg16_reg16,
    or_reg32_reg32,
    or_reg64_reg64,
    or_reg8_mem8,
    or_reg16_mem16,
    or_reg32_mem32,
    or_reg64_mem64,
    or_mem8_reg8,
    or_mem16_reg16,
    or_mem32_reg32,
    or_mem64_reg64,
    or_reg8_imm8,
    or_mem8_imm8,
    or_mem16_imm8,
    or_mem32_imm8,
    or_mem64_imm8,
    or_mem16_imm32,
    or_mem32_imm32,
    or_mem64_imm32,
    xor_reg8_reg8,
    xor_reg16_reg16,
    xor_reg32_reg32,
    xor_reg64_reg64,
    xor_reg8_mem8,
    xor_reg16_mem16,
    xor_reg32_mem32,
    xor_reg64_mem64,
    xor_mem8_reg8,
    xor_mem16_reg16,
    xor_mem32_reg32,
    xor_mem64_reg64,
    xor_reg8_imm8,
    xor_reg16_imm8,
    xor_reg32_imm8,
    xor_reg64_imm8,
    // shifts
    shl_reg_cl,
    shl_mem_cl,
    shr_reg_cl,
    shr_mem_cl,
    sar_reg_cl,
    sar_mem_cl,
    shl_reg_imm,
    shl_mem_imm,
    shr_reg_imm,
    shr_mem_imm,
    sar_reg_imm,
    sar_mem_imm,
    // test
    test_reg8_reg8,
    test_reg16_reg16,
    test_reg32_reg32,
    test_reg64_reg64,
    test_mem8_reg8,
    test_mem16_reg16,
    test_mem32_reg32,
    test_mem64_reg64,
    test_reg8_imm8,
    test_reg16_imm16,
    test_reg32_imm32,
    test_reg64_imm32,
    test_mem8_imm8,
    test_mem16_imm16,
    test_mem32_imm32,
    test_mem64_imm32,
    neg_reg8,
    neg_reg16,
    neg_reg32,
    neg_reg64,
    // cmp r/m, r
    cmp_mem8_reg8,
    cmp_mem16_reg16,
    cmp_mem32_reg32,
    cmp_mem64_reg64,
    cmp_reg8_reg8,
    cmp_reg16_reg16,
    cmp_reg32_reg32,
    cmp_reg64_reg64,
    // cmp reg, r/m (3A/3B, d=1)
    cmp_reg8_mem8,
    cmp_reg16_mem16,
    cmp_reg32_mem32,
    cmp_reg64_mem64,
    // cmp r/m, imm8 (83 /7)
    cmp_mem8_imm8,
    cmp_mem16_imm8,
    cmp_mem32_imm8,
    cmp_mem64_imm8,
    cmp_reg8_imm8,
    cmp_reg16_imm8,
    cmp_reg32_imm8,
    cmp_reg64_imm8,
    // inc/dec
    inc_mem8,
    inc_mem16,
    inc_mem32,
    inc_mem64,
    inc_reg8,
    inc_reg16,
    inc_reg32,
    inc_reg64,
    dec_mem8,
    dec_mem16,
    dec_mem32,
    dec_mem64,
    dec_reg8,
    dec_reg16,
    dec_reg32,
    dec_reg64,
    // mul/imul/div/idiv (memory)
    mul_mem8,
    mul_mem16,
    mul_mem32,
    mul_mem64,
    imul_mem8,
    imul_mem16,
    imul_mem32,
    imul_mem64,
    div_mem8,
    div_mem16,
    div_mem32,
    div_mem64,
    idiv_mem8,
    idiv_mem16,
    idiv_mem32,
    idiv_mem64,
    // mul/imul/div/idiv (register)
    mul_reg8,
    mul_reg16,
    mul_reg32,
    mul_reg64,
    imul_reg8,
    imul_reg16,
    imul_reg32,
    imul_reg64,
    div_reg8,
    div_reg16,
    div_reg32,
    div_reg64,
    idiv_reg8,
    idiv_reg16,
    idiv_reg32,
    idiv_reg64,
    // imul r, r/m (0F AF)
    imul_reg64_mem64,
    imul_reg64_reg64,
    imul_reg32_mem32,
    imul_reg32_reg32,
    // imul r, r/m, imm8 (6B)
    imul_reg64_mem64_imm8,
    imul_reg64_reg64_imm8,
    imul_reg32_mem32_imm8,
    imul_reg32_reg32_imm8,
    // stack / calls
    call_rel32,
    ret,
    push_reg,
    push_mem64,
    push_imm,
    pop_reg,
    pop_mem64,
    lods,
    // sign extend
    cbw,
    cwde,
    cdqe,
    cwd,
    cdq,
    cqo,
    // zero/sign extend loads
    movzx_reg32_mem8,
    movzx_reg32_mem16,
    movsx_reg32_mem8,
    movsx_reg32_mem16,
    movsxd_reg64_reg32,
    movsxd_reg64_mem32,
    lea_reg_mem,
    cmovcc_reg_reg,
    cmovcc_reg_mem,
    setcc_reg8,
    setcc_mem8,
    cmpxchg_mem32_reg32,
    cmpxchg_mem64_reg64,
    xchg_mem32_reg32,
    xchg_mem64_reg64,
    xadd_mem32_reg32,
    xadd_mem64_reg64,
    xorps_xmm_xmm,
    movups_xmm_xmm,
    movups_xmm_mem,
    movups_mem_xmm,
    movaps_xmm_xmm,
    movaps_xmm_mem,
    movaps_mem_xmm,
    vmovdqu_xmm_xmm,
    vmovdqu_xmm_mem,
    vmovdqu_mem_xmm,
    vmovdqa_xmm_xmm,
    vmovdqa_xmm_mem,
    vmovdqa_mem_xmm,
    vmovups_xmm_xmm,
    vmovups_xmm_mem,
    vmovups_mem_xmm,
    vmovaps_xmm_xmm,
    vmovaps_xmm_mem,
    vmovaps_mem_xmm,
    vmovupd_xmm_xmm,
    vmovupd_xmm_mem,
    vmovupd_mem_xmm,
    vmovapd_xmm_xmm,
    vmovapd_xmm_mem,
    vmovapd_mem_xmm,
    vmovss_xmm_mem,
    vmovss_mem_xmm,
    vmovsd_xmm_mem,
    vmovsd_mem_xmm,
    vmovdqu_ymm_ymm,
    vmovdqu_ymm_mem,
    vmovdqu_mem_ymm,
    vmovdqa_ymm_ymm,
    vmovdqa_ymm_mem,
    vmovdqa_mem_ymm,
    vmovups_ymm_ymm,
    vmovups_ymm_mem,
    vmovups_mem_ymm,
    vmovaps_ymm_ymm,
    vmovaps_ymm_mem,
    vmovaps_mem_ymm,
    vmovupd_ymm_ymm,
    vmovupd_ymm_mem,
    vmovupd_mem_ymm,
    vmovapd_ymm_ymm,
    vmovapd_ymm_mem,
    vmovapd_mem_ymm,
    vzeroupper,
    vcvtsi2ss_xmm_reg,
    vcvtsi2ss_xmm_mem,
    vcvtsi2sd_xmm_reg,
    vcvtsi2sd_xmm_mem,
    // conditional / unconditional jumps
    jmp_rel8,
    jcc_rel8,
    jcc_rel32,
    jmp_mem64,
    jmp_reg64,
    // syscall
    syscall,
    cpuid,
    xgetbv,
    call_mem64,
    call_reg64,
    hlt,
};

pub const CpuidResult = capabilities.CpuidResult;

pub fn emulatedCpuid(leaf: u32, subleaf: u32) CpuidResult {
    return capabilities.cpuid(.xenia, leaf, subleaf);
}

pub fn emulatedXcr0() u64 {
    return capabilities.xcr0(.xenia);
}

test "emulated CPUID exposes a coherent AVX baseline" {
    const leaf0 = emulatedCpuid(0, 0);
    try std.testing.expectEqual(@as(u32, 7), leaf0.eax);
    try std.testing.expectEqual(@as(u32, 0x756E_6547), leaf0.ebx);

    const leaf1 = emulatedCpuid(1, 0);
    try std.testing.expect(leaf1.ecx & (@as(u32, 1) << 27) != 0);
    try std.testing.expect(leaf1.ecx & (@as(u32, 1) << 28) != 0);
    try std.testing.expectEqual(@as(u64, 0x7), emulatedXcr0());
}

pub const DecodedInsn = struct {
    op: Op = .invalid,
    size: OperandSize = .bits32,
    dst_reg: RegId = .al_ax_eax_rax,
    src_reg: RegId = .al_ax_eax_rax,
    addr: u64 = 0,
    imm: u64 = 0,
    len: u8 = 0,
    sib_has_index: bool = false,
    sib_index_reg: RegId = .al_ax_eax_rax,
    sib_scale: u2 = 0,
    sib_has_base: bool = false,
    sib_base_reg: RegId = .al_ax_eax_rax,
    rip_relative: bool = false,
    has_0x67: bool = false,
    is_reg_form: bool = false,
    cond: Condition = .e,
    xmm_dst: u8 = 0,
    xmm_src: u8 = 0,
};
