const decoder = @import("decoder.zig");

pub const BridgeStatus = enum {
    unsupported,
    metadata_only,
    cleo_route,
    native_route,
};

pub const BridgeResult = struct {
    status: BridgeStatus,
    op: decoder.Op,

    /// Returns true if the decoded instruction can be routed to CLEO
    /// for wide (>128-bit) execution.  The ISA bridge checks this
    /// before falling back to the interpreter.
    ///
    /// Covers all 123 CLEO Operation enum values with corresponding
    /// decoder opcode families.  Missing decoder ops (VSCALEF, VRANGE,
    /// VFIXUPIMM, VCOMPRESS, VEXPAND, VBROADCAST, VCVT*, etc.) must
    /// be added to the decoder.Op enum before they can be routed.
    pub fn canRouteToCleo(self: BridgeResult) bool {
        // Instruction families that CLEO can handle via its wide engine.
        return switch (self.op) {
            // ═══ P0: Arithmetic ═══
            .addps,
            .addpd,
            .subps,
            .subpd,
            .mulps,
            .mulpd,
            .divps,
            .divpd,
            .sqrtps,
            .sqrtpd,
            .vsqrtps,
            .vsqrtpd,
            .vsqrtss,
            .vsqrtsd,
            .addsubps,
            .addsubpd,
            // ═══ Integer Arithmetic ═══
            .vpaddb,
            .vpaddw,
            .vpaddd,
            .vpaddq,
            .vpsubb,
            .vpsubw,
            .vpsubd,
            .vpsubq,
            .vpmullw,
            .vpmulld_38,
            // ═══ SSSE3/AVX2 0x38 ops ═══
            .vpsignb,
            .vpsignw,
            .vpsignd,
            .vpsllvw,
            .vpsravw,
            .vpsrlvw,
            .vpabsb,
            .vpabsw,
            .vpabsd,
            .vpmovsxbw,
            .vpmovsxbd,
            .vpmovsxbq,
            .vpmovsxwd,
            .vpmovsxwq,
            .vpmovsxdq,
            .vpmovzxbw,
            .vpmovzxbd,
            .vpmovzxbq,
            .vpmovzxwd,
            .vpmovzxwq,
            .vpmovzxdq,
            .vpmuldq,
            .vpacksswb,
            .vpackuswb,
            .vpackusdw,
            .vpunpckhqdq,
            .vunpcklps,
            .vunpckhps,
            .vunpcklpd,
            .vunpckhpd,
            .vpermd,
            .vpminsb,
            .vpminsd,
            .vpminuw,
            .vpminud,
            .vpmaxsb,
            .vpmaxsd,
            .vpmaxuw,
            .vpmaxud,
            .vphaddw,
            .vphaddd,
            .vphaddsw,
            .vphsubw,
            .vphsubd,
            .vphsubsw,
            .vphminposuw,
            .vpsrlvd,
            .vpsravd,
            .vpsllvd,
            .vpblendvb,
            .vpalignr,
            .vpermps,
            // ═══ Comparison ═══
            .cmpps,
            .cmppd,
            .vpcmpeqb,
            .vpcmpeqw,
            .vpcmpeqd,
            .vpcmpeqq,
            .vpcmpgtb,
            .vpcmpgtw,
            .vpcmpgtd,
            .vpcmpgtq,
            // ═══ Logical ═══
            .andps,
            .andpd,
            .andnps,
            .andnpd,
            .orps,
            .orpd,
            .xorps,
            .xorpd,
            .vpor,
            .vpand,
            .vpandn,
            .vpxor,
            // ═══ Shuffle / Blend ═══
            .shufps,
            .shufpd,
            .blendps,
            .blendpd,
            .blendvps,
            .blendvpd,
            // ═══ Pack / Unpack ═══
            .packssdw,
            .packsswb,
            .packusdw,
            .packuswb,
            .punpcklbw,
            .punpcklwd,
            .punpckldq,
            .punpcklqdq,
            .punpckhbw,
            .punpckhwd,
            .punpckhdq,
            .punpckhqdq,
            // ═══ Convert ═══
            .cvtpd2ps,
            .cvtps2pd,
            .cvtdq2ps,
            .cvtps2dq,
            .cvttps2dq,
            .cvtpd2dq,
            .cvttpd2dq,
            .cvtdq2pd,
            // ═══ Shift ═══
            .psllw,
            .pslld,
            .psllq,
            .vpslld,
            .vpsllq,
            .vpsllw,
            .vpslldq,
            .psrlw,
            .psrld,
            .psrlq,
            .vpsrld,
            .vpsrlq,
            .vpsrlw,
            .vpsrldq,
            .psraw,
            .psrad,
            // ═══ Min / Max ═══
            .pminsb,
            .pminsw,
            .pminsd,
            .pminsq,
            .pmaxsb,
            .pmaxsw,
            .pmaxsd,
            .pmaxsq,
            .pminub,
            .pminuw,
            .pminud,
            .pminuq,
            .pmaxub,
            .pmaxuw,
            .pmaxud,
            .pmaxuq,
            // ═══ SIMD Float Min/Max ═══
            .vminps,
            .vminpd,
            .vminss,
            .vminsd,
            .vmaxps,
            .vmaxpd,
            .vmaxss,
            .vmaxsd,
            // ═══ Horizontal / Reciprocal ═══
            .vhaddps,
            .vhaddpd,
            .vhsubps,
            .vhsubpd,
            .vrcpps,
            .vrsqrtps,
            // ═══ SIMD Compare ═══
            .vcmpps,
            .vcmppd,
            .vcmpss,
            .vcmpsd,
            // ═══ AES ═══
            .aesenc,
            .aesdec,
            .aesenclast,
            .aesdeclast,
            // ═══ Move / Duplicate ═══
            .movddup,
            .movsldup,
            .movshdup,
            .movaps,
            .movapd,
            .movups,
            .movupd,
            .movntps,
            .movntpd,
            .vmovss_mem32_reg,
            .vmovsd_mem64_reg,
            .vmovlps_mem64_reg,
            .vmovlpd_mem64_reg,
            .vmovhlps,
            .vmovlhps,
            // ═══ Mask operations ═══
            .movmskps,
            .movmskpd,
            .vmovmskps,
            .vmovmskpd,
            // ═══ Dot product ═══
            .dpps,
            // ═══ Permute ═══
            .vpermd,
            .vpermq,
            .vpermilps,
            .vpermilpd,
            // ═══ Insert / Extract ═══
            .vpinsrb_xmm_xmm_reg32,
            .vpinsrb_xmm_xmm_mem8,
            .vpinsrd,
            .vpinsrq,
            .vpinsrw,
            // ═══ COMPUTE (SCALE / RANGE / FIXUP) ═══
            .vscalefps,
            .vscalefpd,
            .vrangeps,
            .vrangepd,
            .vfixupimmps,
            .vfixupimmpd,
            // ═══ COMPRESS / EXPAND ═══
            .vcompressps,
            .vcompresspd,
            .vexpandps,
            .vexpandpd,
            // ═══ BROADCAST ═══
            .vbroadcastss,
            .vbroadcastsd,
            .vbroadcastf128,
            .vbroadcasti128,
            // ═══ Gather / Scatter ═══
            .vgatherdps,
            .vgatherdpd,
            .vgatherqps,
            .vgatherqpd,
            .vpgatherdd,
            .vpgatherdq,
            .vpgatherqd,
            .vpgatherqq,
            .vscatterdps,
            .vscatterdpd,
            .vscatterqps,
            .vscatterqpd,
            .vpscatterdd,
            .vpscatterdq,
            .vpscatterqd,
            .vpscatterqq,
            // ═══ VPERM (2-source) ═══
            .vpermi2d,
            .vpermi2q,
            .vpermi2ps,
            .vpermi2pd,
            .vpermt2d,
            .vpermt2q,
            .vpermt2ps,
            .vpermt2pd,
            // ═══ VCVT ═══
            .vcvtps2ph,
            .vcvtph2ps,
            .vcvtne2ps2bf16,
            .vcvttps2dq,
            .vcvtps2dq,
            .vcvtdq2ps,
            .vcvtps2pd,
            .vcvtpd2ps,
            // ═══ SHUFFLE ═══
            .vshuff32x4,
            .vshuff64x2,
            .vshufi32x4,
            .vshufi64x2,
            // ═══ MASK / MULTISHIFT / CONFLICT ═══
            .vpmovm2d,
            .vpmovd2m,
            .vpmultishiftqb,
            .vpconflictd,
            .vpconflictq,
            // ═══ FMA ═══
            .vfmadd132ps,
            .vfmadd132pd,
            .vfmadd213ps,
            .vfmadd213pd,
            .vfmadd231ps,
            .vfmadd231pd,
            .vfmsub132ps,
            .vfmsub132pd,
            .vfmsub213ps,
            .vfmsub213pd,
            .vfmsub231ps,
            .vfmsub231pd,
            .vfmaddsub132ps,
            .vfmaddsub213ps,
            .vfmaddsub231ps,
            .vfmsubadd132ps,
            .vfmsubadd213ps,
            .vfmsubadd231ps,
            .vfnmadd132ps,
            .vfnmadd132pd,
            .vfnmadd213ps,
            .vfnmadd213pd,
            .vfnmadd231ps,
            .vfnmadd231pd,
            .vfnmsub132ps,
            .vfnmsub132pd,
            .vfnmsub213ps,
            .vfnmsub213pd,
            .vfnmsub231ps,
            .vfnmsub231pd,
            // ═══ Advanced ═══
            .vpternlogd,
            .vpternlogq,
            .valignd,
            .valignq,
            // ═══ SHA ═══
            .sha1msg1,
            .sha1msg2,
            .sha1nexte,
            .sha1rnds4,
            .sha256msg1,
            .sha256msg2,
            .sha256rnds2,
            // ═══ GF(2^8) ═══
            .gf2p8mulb,
            .gf2p8affineqb,
            .gf2p8affineinvqb,
            => true,
            else => false,
        };
    }

    // routableOpCount intentionally omitted: Zig doesn't support
    // comptime switch-arm counting, and a hardcoded constant would
    // silently drift.  Use BridgeResult coverage diagnostics instead.
};

/// Stable adapter point for routing decoded x86-64 instructions into the ISA
/// truth layer as that layer becomes executable/DBT-ready.
///
/// The bridge determines whether a decoded instruction can be:
/// - `unsupported`: not yet implemented in any backend
/// - `metadata_only`: decode produces metadata but no executable handler
/// - `cleo_route`: eligible for CLEO wide-execution (>128-bit vectors)
/// - `native_route`: handled natively by the host CPU
pub fn describe(decoded: decoder.DecodedInsn) BridgeResult {
    var result = BridgeResult{ .status = .metadata_only, .op = decoded.op };
    result.status = if (result.canRouteToCleo()) .cleo_route else .metadata_only;
    return result;
}
